"""Every visible sentence of the page and the PDF, in English, Portuguese and French.

Numbers never appear literally here: ``{placeholders}`` are filled from
``research/thesis.json`` (dated evidence and rules) and the refreshed snapshot,
so the three languages cannot disagree.  Portuguese always says
"commodities", never "matérias-primas".
"""
from __future__ import annotations

TEXT: dict[str, dict] = {}

# ---------------------------------------------------------------------------
# English
TEXT["en"] = {
    "html_lang": "en",
    "language_label": "Language",
    "skip": "Skip to the current view",
    "byline": "EPFL mechanical engineering · Brazilian and French",
    "kicker": "Brazil · interest rates · the real · commodities",
    "title": "Brazil macro, from policy to price.",
    "intro": "A student research log on how Brazilian and U.S. interest rates, the Brazilian real and Brazil’s main exports move together. Each view is dated, backed by linked official data and paired with the rules that would make me act or change my mind.",
    "nav": {"view": "Current view", "review": "Last call reviewed", "evidence": "Evidence", "paths": "Paths", "trade": "Paper trade", "commodities": "Commodities", "method": "Method & data"},
    "nav_label": "Sections",
    "view_label": "My current view",
    "status_no_position": "No position",
    "view_headline": "Flávio Bolsonaro’s first-round lead is a surprise, not a verdict. In two of the last three elections the real gave back most of its post-vote rally before the runoff, so I stay out until {runoff} and act only if prices confirm.",
    "why_label": "Why",
    "why": [
        ("The first round surprised.", "Flávio Bolsonaro took {fl_share} of valid votes to Lula’s {lu_share}. The final Datafolha and Quaest polls had Lula ahead by {dat_lead} and {que_lead} points: they missed the margin by {dat_miss} and {que_miss}, in the same direction."),
        ("The runoff is not a formality.", "{oth_share} of voters chose other candidates. To reach 50%, Flávio needs {need_fl} of them and Lula {need_lu}. No candidate in that group is on the left, so I read this as favouring Flávio, but it is not a forecast."),
        ("The market has been here before.", "USD/BRL fell between {ev_min} and {ev_max} on the first Monday after the 2014, 2018 and 2022 first rounds. By the runoff it had given back {gb_2014} (2014) and {gb_2022} (2022) of the move; in 2018 it kept falling. Long-real positioning was already above past elections (JPMorgan)."),
    ],
    "act_label": "What would make me act",
    "act": "After the runoff, from {earliest}: two daily PTAX closes below {entry} with the U.S. two-year yield at or below {us2y_max}. I would read that as the market paying for a credible fiscal path, and paper-buy the real. Earlier closes, including any first-Monday rally, do not count.",
    "change_label": "What would change my mind",
    "change": "A PTAX close above {abandon} before any entry, Brazil’s two-year rate above {br2y_max}, or the U.S. two-year yield above {us2y_exit}. Each would mean risk is rising, not falling.",
    "monitor_label": "Rule check",
    "monitor_note": "Automatic comparison of the saved PTAX data with the rules above. A mechanical check, not a live position.",
    "monitor": {
        "waiting": "Waiting for the runoff. Latest PTAX {latest} ({latest_date}); no entry is possible before {earliest}.",
        "watching": "Watching. Latest PTAX {latest} ({latest_date}); entry needs two closes below {entry}.",
        "entered": "Entry conditions met on {date} at {value} (paper). Latest PTAX {latest} ({latest_date}).",
        "review": "Paper position reached the review zone on {date} ({value}). Reassess before doing anything else.",
        "exited": "Paper position closed by the exit rule on {date} at {value}.",
        "abandoned": "Idea abandoned: PTAX closed at {value} on {date}, above {abandon}.",
        "expired": "The review date ({review_by}) has passed without an entry. This thesis is due for an update.",
        "unavailable": "Rule check unavailable: the saved PTAX history could not be read.",
    },
    "tape_label": "Latest official data",
    "tape": {
        "selic_target": "Selic target",
        "fed_target_range": "Fed target range",
        "brazil_us_policy_differential": "Brazil–U.S. rate gap",
        "ptax_usd_brl_midpoint": "USD/BRL (PTAX)",
        "us_2_year_treasury": "U.S. 2-year yield",
        "brent": "Brent crude (spot)",
    },
    "fresh": {"fresh": "Up to date", "delayed": "Delayed", "stale": "Stale", "unknown": "Date unknown"},
    "stale_banner": "Some figures are older than usual (marked below). The page shows each value with its own date instead of hiding it.",
    "refresh_banner": "The automatic refresh has not run since {date}. Figures below are shown with their original dates.",
    "unavailable": "Unavailable",
    "na": "n/a",
    "download": "Download the research brief (PDF, English)",
    "download_help": "4 pages, the same dated thesis as this page, generated from the saved files",

    # Review of the previous thesis
    "review_title": "What happened to my 24 September thesis",
    "review_intro": "On 24 September I said the {first_round} election would decide the next move, and planned to buy the real after two PTAX closes below {prev_entry} once the first round was over. No position was opened: no performance to report, only reasoning to check.",
    "review_head": ("What I expected", "What happened", "Verdict"),
    "review_rows": {
        "trigger": ("Act only after the first round, below {prev_entry}; drop the idea above {prev_abandon}.", "Since 24 September PTAX closed between {ptax_low} ({ptax_low_date}) and {ptax_high} ({ptax_high_date}). Neither level was reached; no entry was possible before the vote."),
        "election": ("Too close to call: Datafolha had Lula at {prev_lula}% and Flávio Bolsonaro at {prev_flavio}% in the first round (±{prev_moe}).", "A runoff was needed, but Flávio finished first: the last Datafolha and Quaest polls missed the margin by {dat_miss} and {que_miss}."),
        "cushion": ("The large rate cushion keeps the real supported.", "The gap stayed at {gap}, yet USD/BRL rose to {ptax} ({ptax_chg}), its highest close in four months. The real held its range without strengthening."),
        "premium": ("Brazil’s two-year rate sits well above the economists’ own path: a risk premium.", "The two-year rate went from {prev_br_2y} to {br_2y} between 23 September and 2 October; its gap over the economists’ path stayed near {gap_2y}. The premium did not compress before the vote; the runoff will test it."),
        "us_yields": ("The U.S. two-year yield stays at or below {us2y_max}.", "{us2y_prev} → {us2y}; highest close {us2y_high} ({us2y_high_date}). The condition held."),
    },
    "verdicts": {"confirmed": "Confirmed", "partly": "Partly", "unresolved": "Unresolved", "not_triggered": "Not triggered", "underweighted": "Underweighted"},
    "review_lesson_label": "What I changed",
    "review_lesson": "I treated the polls as roughly right and the first round as decisive. Neither held: the polls leaned the wrong way by several points, and the first round only narrowed the question to a runoff. The new thesis moves the decision to the runoff.",

    # Evidence
    "evidence_title": "The evidence, sorted by type",
    "evidence_intro": "Each item is labelled so facts, prices, forecasts and my own reading stay separate. Values are frozen at the thesis date ({as_of}). Market prices are from 2 October, the last session before the vote; markets reopen on {first_monday}. The refreshed figures are at the top of the page.",
    "kinds": {"fact": "Fact", "pricing": "Market pricing", "survey": "Survey & projections", "interpretation": "My interpretation"},
    "kind_help": {
        "fact": "Something that happened.",
        "pricing": "What prices imply today.",
        "survey": "What forecasters and officials expect.",
        "interpretation": "My reading, which can be wrong.",
    },
    "evidence": {
        "fact": [
            "Brazil voted on {first_round}. With {counted} of ballot boxes counted, Flávio Bolsonaro (PL) has {fl_share} of valid votes and Lula (PT) {lu_share}, {margin_votes} votes apart. No one reached 50%, so the runoff is on {runoff}. The other candidates (Cury, Santos, Caiado, Zema and others) took {oth_share}.",
            "Final polls, valid votes: Datafolha (3 Oct) Lula {dat_lula}%, Flávio {dat_flavio}%; Quaest (2–3 Oct) Lula {que_lula}%, Flávio {que_flavio}%. Both showed a technical tie. Runoff scenarios (total votes), Lula–Flávio: Datafolha {dat_r_lula}–{dat_r_flavio}, Quaest {que_r_lula}–{que_r_flavio}.",
            "Neither central bank has met since 16 September: the Copom cut the Selic by 0.25 pp to {selic} (unanimously, its {cuts_count}th cut in a row and {cuts_total} since March) and the Fed raised its range by 0.25 pp to {fed_range} (12–0). The policy-rate gap is {gap}. Next: Fed {fomc_next}, Copom {copom_next}.",
            "For 2027 the government’s budget bill projects a {fiscal_gov} primary surplus; the Senate’s Independent Fiscal Institution projects a {fiscal_ifi} deficit.",
        ],
        "pricing": [
            "USD/BRL (PTAX) closed at {ptax} on {ptax_date}, the last session before the vote: {ptax_chg} since 24 September and the highest close in the saved four months (low: {low4m}).",
            "The U.S. two-year Treasury yield was {us2y} on {ptax_date} (it was {us2y_prev} on 24 September); the ten-year was {us10y}.",
            "Brazil’s fixed-rate curve (ANBIMA, 2 Oct): one year {br_1y}, two years {br_2y}, about {gap_2y} above the rate implied by economists’ own forecasts ({survey_2y}). Inflation implied by the curve over two years: {be_2y}.",
            "Brent: the EIA spot price was {brent} on {brent_date}, below its {brent_peak} peak of {brent_peak_date} but still above $100.",
        ],
        "survey": [
            "Focus survey medians ({focus_date}): Selic {focus_selic26} at end-2026, {focus_selic27} at end-2027; inflation {focus_ipca26} in 2026, {focus_ipca27} in 2027; USD/BRL {focus_fx26} at end-2026.",
            "Fed officials’ median projection: {fed_proj_2026} at end-2026 (one more 0.25 pp rise), up from {fed_proj_june} in June.",
            "JPMorgan (28 Sep): after the election USD/BRL could trade from about {jpm_low}, on a favourable fiscal signal even if incremental, to about {jpm_high}, if the result is read as bad for fiscal consolidation. It saw the real near fair value, long-real positioning above past elections, options pricing about {jpm_event} of event moves across both rounds, a {jpm_real} real interest rate (against {jpm_real22} in 2022) and gross debt of {jpm_debt} of GDP (against {jpm_debt22}).",
        ],
        "interpretation": [
            "Runoff arithmetic: holding turnout and blank votes constant, Flávio needs {need_fl} of the {oth_share} who voted for others, and Lula {need_lu}. No candidate in that group is on the left, so I read this as favouring Flávio, without attaching a probability.",
            "Past first rounds: after 2014, 2018 and 2022, USD/BRL fell between {ev_min} and {ev_max} on the first business day. By the Friday before the runoff it had given back {gb_2014} (2014) and {gb_2022} (2022) of that move; in 2018 it extended it by a further {gb_2018} of that move. Three elections are a base rate, not a test, but they argue against paying for the first Monday.",
            "Levels against volatility: a 15-session move has a standard deviation of {vol15} ({vol_ann} a year). Entry sits {entry_sigma} σ below Friday’s close and the drop level {abandon_sigma} σ above it, while a typical first-round Monday moved {event_sigma} σ: these are triggers, not stop-losses.",
        ],
    },
    "focus_table_caption": "Focus survey medians, {focus_date}",
    "focus_rows": ("Selic, end of year", "Inflation (IPCA)", "USD/BRL, end of year"),
    "chart_title": "USD/BRL (PTAX): last {n} sessions and my decision levels",
    "chart_desc": "Daily PTAX closes from {start} to {end}. Latest {latest}. Levels: entry below {entry}, exit above {exit}, drop the idea above {abandon}; dotted: economists’ year-end median, {focus_fx26}.",
    "chart_labels": {"entry": "Entry < {entry}", "exit": "Exit > {exit}", "abandon": "Drop > {abandon}", "prev": "Focus end-2026 {focus_fx26}", "event": "16 Sep decisions"},
    "chart_table": "Show the chart data as a table",
    "chart_cols": ("Date", "PTAX"),

    # Paths
    "paths_title": "What could happen before and after {runoff}",
    "paths_intro": "Three paths I can recognise in the data, plus one outside shock. I don’t attach probabilities: the point is to decide in advance what each would mean and what I would do.",
    "path_fields": ("Signals", "What it would mean", "What I would do"),
    "paths": [
        ("Premium compresses after the runoff", "After {runoff}, PTAX closes below {entry} twice; the two-year rate falls a quarter point or more from {br_2y}; the winner shows a credible fiscal path.", "Investors see less fiscal risk, and the carry cushion keeps attracting money.", "Paper-buy the real if the U.S. two-year yield is at or below {us2y_max}."),
        ("The first-round rally fades", "PTAX gives back most of its post-vote move before {runoff} and is back above {exit}; polls tighten.", "The market doubts the first-round signal, as in 2014 and 2022.", "No position. Wait for {runoff}."),
        ("Risk premium rises", "PTAX closes above {abandon}; the two-year rate moves above {br2y_max}; implied inflation rises.", "Fiscal worries dominate; a weaker real plus expensive oil could make the Copom pause its cuts.", "Drop the long-real idea. A dollar trade would need new rules."),
        ("Outside shock: U.S. rates or oil", "The U.S. two-year yield rises above {us2y_exit}, or Brent falls sharply as Hormuz reopens.", "Emerging-market currencies tend to weaken together; cheaper oil removes a support.", "No long-real position; exit if already in one."),
    ],
    "calendar_label": "Dates that matter",
    "calendar": {"election_first": "Brazil election, first round", "election_runoff": "Presidential runoff", "fomc": "Fed decision", "copom": "Copom decision", "both": "Fed and Copom decisions"},

    # Paper trade
    "trade_title": "The paper trade: wait for the runoff, then buy the real only if the market confirms",
    "trade_status": "Inactive, no position · earliest entry {earliest}",
    "trade_rows": [
        ("Expression", "Long the Brazilian real against the U.S. dollar (short USD/BRL), tracked with the official PTAX rate. Paper only: no money, no execution."),
        ("Thesis", "If the election lowers the fiscal risk premium, the real should strengthen and stay stronger, because investors keep collecting a large interest-rate cushion while they wait."),
        ("Why it may not be priced", "The two-year rate sits {gap_2y} above the economists’ own path, and economists expect USD/BRL at {focus_fx26} at year-end, so a durably stronger real is not the consensus. JPMorgan, though, sees the real near fair value with long positioning above past elections: some good news may already be priced."),
        ("Catalysts", "Runoff {runoff}; Fed {fomc_next}; Copom {copom_next}."),
        ("Entry", "From {earliest}, the first PTAX after the runoff: two consecutive daily closes below {entry}, with the U.S. two-year yield at or below {us2y_max}. Earlier closes, including any rally on {first_monday}, do not count."),
        ("Drop the idea (before entry)", "Any PTAX close above {abandon}, higher than every close of the past four months (peak {high4m} on {high4m_date}). The idea is dropped, not reversed."),
        ("Exit (after entry)", "Two consecutive closes above {exit} (the top of the last 20 closes), or the U.S. two-year yield above {us2y_exit}."),
        ("Review", "Around {review_low}–{review_high} (range low minus range width), or on {review_by} at the latest. A review zone, not a target."),
    ],
    "trade_more": "Risks, what would change my view, and the commodity channel",
    "trade_risks_label": "Main risks",
    "trade_risks": [
        "The winner’s fiscal plan is read as negative, whoever wins.",
        "I buy after the move: some good news may already be priced, and long-real positioning was already high.",
        "U.S. yields keep rising and pull money out of emerging markets, or oil falls sharply as Hormuz reopens, leaving less export income and room for faster Copom cuts.",
    ],
    "trade_change_label": "Evidence that would change my view",
    "trade_change": "Beyond the triggers above: a Copom signal of faster cuts, a winner with no credible fiscal plan, or a sharp deterioration in official fiscal numbers.",
    "trade_channels_label": "Commodity and geopolitical channels",
    "trade_channels": "Brazil exports more oil than it imports, so high prices help its external accounts. They also keep inflation risk alive, which keeps the Copom cautious and the cushion wide. A reopening of the Strait of Hormuz would weaken both supports at once. Iron ore and soybeans are unlikely to decide this window (see below).",
    "trade_math_label": "The arithmetic: carry and volatility",
    "trade_math": "Carry: ((1 + {selic}) ÷ (1 + {fed_mid}))^(1/12) − 1 ≈ {carry} per month. A real position earns this through forward prices, not through PTAX, so the decision levels ignore it. Volatility: a daily standard deviation of {vol_daily} over the last 20 sessions, times √15 sessions to the runoff, gives {vol15} (about {vol15_brl} on PTAX). The entry level is {entry_sigma} σ below Friday’s close, the drop level {abandon_sigma} σ above it, and a typical first-round Monday has moved {event_sigma} σ: a gap can jump every level.",

    # Commodities
    "commodities_title": "Brazil’s export prices: which ones matter now?",
    "commodities_intro": "Brazil earns dollars by exporting oil, iron ore, soybeans and sugar. Each series keeps its own date and frequency; they are not combined into one index.",
    "commodity_cols": ("Commodity", "Latest", "Change", "Matters for the next six weeks?"),
    "commodity_names": {"brent": "Oil (Brent spot)", "iron_ore": "Iron ore", "soybeans": "Soybeans", "sugar": "Sugar"},
    "commodity_verdicts": {
        "brent": ("Yes, both ways", "Supports export income and keeps the Copom cautious; a sudden reopening of Hormuz would remove both effects. Spot is still above $100 but below its {brent_peak} peak of mid-September."),
        "iron_ore": ("Not now", "The monthly IMF price slipped in July. Without a clear change in Chinese steel demand it is unlikely to move the real within six weeks, though it matters directly for Vale."),
        "soybeans": ("Limited", "Prices rose in July, but Brazil’s export season peaks between March and July, so fewer soy dollars arrive in the fourth quarter."),
        "sugar": ("Limited", "Mills can switch cane between sugar and ethanol; expensive oil makes ethanol more attractive, which can tighten sugar supply. More a company story than a currency one."),
    },
    "vs": "vs",
    "units": {"USD per barrel": "USD/bbl", "USD per metric ton": "USD/t", "US cents per pound": "US¢/lb"},
    "freq": {"daily": "daily", "weekly": "weekly", "monthly": "monthly", "quarterly": "quarterly"},

    # Equity bridge
    "equity_title": "From a commodity price to a company",
    "equity_intro": "A price move is only a starting point. Before calling a producer an investment, I would test how much of the move reaches revenue, margins, cash and valuation.",
    "equity_steps": [
        ("Revenue exposure", "What does the company actually sell, at what realised price, in which currency, and how much is hedged?"),
        ("Margins and cost curve", "Does a higher price become profit, after energy, freight and currency effects? Where does the producer sit on the industry cost curve?"),
        ("Balance sheet", "Can it use the cash well: leverage, capital spending, dividends and buybacks?"),
        ("Valuation", "Is the opportunity already in the price under normal and bad assumptions, and what would prove the thesis wrong?"),
    ],
    "equity_examples_label": "Where I would start in Brazil",
    "equity_examples": "Petrobras (oil price realisation, and a domestic fuel-pricing policy that is politically sensitive in an election year); Vale (iron ore, China, freight); a sugar-and-ethanol producer (the flexibility to shift between the two). Starting points for questions, not recommendations.",

    # Method & data
    "method_title": "Method, data and limits",
    "method_calc_label": "How the numbers are calculated",
    "method_calc": [
        ("Rate gap", "Selic target minus the midpoint of the Fed’s target range. It compares policy rates; it is not an investment return."),
        ("Carry", "((1 + Selic) ÷ (1 + Fed midpoint))^(1/12) − 1, a rough monthly figure that ignores costs."),
        ("Decision levels", "Taken from the last 20 PTAX closes when the thesis was written ({range_low}–{range_high}), rounded to two decimals. The review zone is the range low minus the range width."),
        ("Market vs. economists", "Economists’ path: a straight line from today’s Selic through the Focus year-end medians, minus 0.10 pp (the usual gap between the overnight CDI rate and the Selic), compounded and annualised over one and two years, then compared with ANBIMA’s fixed-rate zero-coupon yields: one year {survey_1y} vs {br_1y}, two years {survey_2y} vs {br_2y}."),
        ("Freshness", "Daily series are “delayed” after 4 days and “stale” after 7; the weekly Focus survey after 10 and 17; monthly IMF prices after 100 and 130 days from the start of the month they describe."),
        ("Runoff arithmetic", "A finalist at share s of valid votes needs (50 − s) ÷ (share of the other candidates) of those candidates’ voters, holding turnout and blank votes constant."),
        ("Poll miss", "The result’s margin (Flávio minus Lula, valid votes) minus each poll’s margin on the same basis. Datafolha and Quaest publish valid-vote versions; the count was {counted} complete."),
        ("First-round reactions", "PTAX on the first business day after the vote against the last close before it, for 2014, 2018 and 2022; and the share of that move undone by the Friday before the runoff."),
        ("Volatility", "Standard deviation of the last 20 daily log returns of PTAX, scaled by the square root of 15 sessions; levels are expressed in multiples of it."),
    ],
    "data_label": "Data status",
    "data_cols": ("Series", "Value", "Observed", "Frequency", "Source", "Status"),
    "series_names": {
        "selic_target": "Selic target", "fed_target_range": "Fed target range", "brazil_us_policy_differential": "Brazil–U.S. rate gap",
        "ptax_usd_brl_midpoint": "USD/BRL PTAX", "us_2_year_treasury": "U.S. 2-year yield", "us_10_year_treasury": "U.S. 10-year yield",
        "focus_selic": "Focus Selic, end-{year}", "focus_ipca": "Focus inflation, {year}", "focus_fx": "Focus USD/BRL, end-{year}",
        "brent": "Brent spot", "iron_ore": "Iron ore (IMF)", "soybeans": "Soybeans (IMF)", "sugar": "Sugar (IMF)",
    },
    "refresh_label": "How the data is refreshed",
    "refresh_text": "A GitHub Actions job runs after the Brazilian close on weekdays. It fetches each official source separately, validates it and saves a small file that this page reads. Visitors never trigger a data request. A failed source keeps its last good value, with its original date, and the failure is reported. A second step marks the run as failed when key figures are more than a week old.",
    "refresh_status": "Last refresh attempt: {attempted} · {ok} of {total} sources updated.",
    "refresh_failed": "Not refreshed in the last attempt: {names}.",
    "refresh_history": "Until 24 September 2026 this job failed silently on U.S. data and the page kept showing 13 September figures. That has been fixed: sources are now independent, U.S. data has official fallbacks, and stale data turns the job red.",
    "limits_label": "Limits",
    "limits": [
        "PTAX is a reference rate, not a tradable price; costs, spreads and position size are not modelled.",
        "Brazil’s curve (ANBIMA) is collected by hand at the thesis date; it does not refresh.",
        "Market prices are from 2 October, before the result, and the count was {counted} complete, so shares may still move.",
        "Focus is a survey, not a commitment; the market-vs-economists gap mixes expectations and risk premium.",
        "Bank scenarios and option-implied figures come from press reports of JPMorgan’s research, not its note.",
        "No probabilities are assigned. The rules are not back-tested, and the first-round study covers only three elections.",
        "AI tools helped write code, draft research text and translate. The rules and the final judgement are mine, and every figure links to its source.",
    ],
    "sources_label": "Sources",
    "sources_note": "Links point to the official source or, for political and oil-market context, to the reporting used. Dates show when each observation applies.",
    "archive_label": "Previous thesis",
    "archive": "The full 24 September thesis (view, rules and saved data) is preserved unchanged in the repository as research/thesis_2026-09-24.json; the 13 September case is in research/data_snapshot.json.",

    # About
    "about_title": "About this project",
    "about": "I’m Romeo Mugnier de Almeida, a mechanical engineering student at EPFL with Brazilian and French roots. I started this project to understand how Brazil’s rates, currency and commodities interact, and I keep it as a dated research log: every view comes with rules written before the outcome, and every old view gets reviewed, including the parts I got wrong.",
    "about_build": "Built with Python and Streamlit. Official data from the Banco Central do Brasil, the U.S. Treasury, the New York Fed and FRED; a scheduled refresh with per-source validation; automated tests for the calculations, translations, freshness rules and PDFs.",
    "links": {"code": "Code on GitHub", "linkedin": "LinkedIn"},
    "footer": "Educational research, not investment advice. No real positions and no claimed performance. Thesis dated {as_of}; each figure shows its own date.",

    # PDF-only strings
    "pdf_title": "Brazil macro: carry, the election and one conditional trade",
    "pdf_subtitle": "Research brief · thesis dated {as_of}",
    "pdf_page": "Page",
}

# ---------------------------------------------------------------------------
# Portuguese (Brazil)
TEXT["pt"] = {
    "html_lang": "pt-BR",
    "language_label": "Idioma",
    "skip": "Ir para a visão atual",
    "byline": "Engenharia mecânica na EPFL · brasileiro e francês",
    "kicker": "Brasil · juros · real · commodities",
    "title": "Brasil macro: da política monetária aos preços.",
    "intro": "Um diário de pesquisa de estudante sobre como os juros do Brasil e dos EUA, o real e as principais exportações brasileiras se movem juntos. Cada visão tem data, se apoia em dados oficiais com link e vem com as regras que me fariam agir ou mudar de ideia.",
    "nav": {"view": "Visão atual", "review": "Revisão da última tese", "evidence": "Evidências", "paths": "Caminhos", "trade": "Operação simulada", "commodities": "Commodities", "method": "Método e dados"},
    "nav_label": "Seções",
    "view_label": "Minha visão atual",
    "status_no_position": "Sem posição",
    "view_headline": "A liderança de Flávio Bolsonaro no primeiro turno é uma surpresa, não um veredito. Em duas das três últimas eleições, o real devolveu a maior parte da alta pós-votação antes do segundo turno; por isso fico de fora até {runoff} e só ajo se os preços confirmarem.",
    "why_label": "Por quê",
    "why": [
        ("O primeiro turno surpreendeu.", "Flávio Bolsonaro obteve {fl_share} dos votos válidos, contra {lu_share} de Lula. Os últimos Datafolha e Quaest davam Lula à frente por {dat_lead} e {que_lead} pontos: erraram a margem em {dat_miss} e {que_miss}, no mesmo sentido."),
        ("O segundo turno não é formalidade.", "{oth_share} dos eleitores votaram em outros candidatos. Para chegar a 50%, Flávio precisa de {need_fl} deles e Lula de {need_lu}. Nenhum candidato desse grupo é de esquerda; por isso leio isso como favorável a Flávio, mas não é uma previsão."),
        ("O mercado já viu esse filme.", "O USD/BRL caiu entre {ev_min} e {ev_max} na primeira segunda-feira depois dos primeiros turnos de 2014, 2018 e 2022. Até o segundo turno, devolveu {gb_2014} (2014) e {gb_2022} (2022) do movimento; em 2018, continuou caindo. As posições compradas em real já estavam acima das de eleições anteriores (JPMorgan)."),
    ],
    "act_label": "O que me faria agir",
    "act": "Depois do segundo turno, a partir de {earliest}: dois fechamentos diários da PTAX abaixo de {entry}, com o juro americano de dois anos em até {us2y_max}. Eu leria isso como o mercado pagando por um caminho fiscal crível e compraria reais na operação simulada. Fechamentos anteriores, inclusive qualquer alta na primeira segunda-feira, não contam.",
    "change_label": "O que me faria mudar de ideia",
    "change": "Uma PTAX acima de {abandon} antes de qualquer entrada, o juro brasileiro de dois anos acima de {br2y_max} ou o juro americano de dois anos acima de {us2y_exit}. Qualquer um desses sinais indicaria risco em alta, não em queda.",
    "monitor_label": "Verificação das regras",
    "monitor_note": "Comparação automática dos dados salvos da PTAX com as regras acima. Uma verificação mecânica, não uma posição real.",
    "monitor": {
        "waiting": "Aguardando o segundo turno. Última PTAX {latest} ({latest_date}); nenhuma entrada é possível antes de {earliest}.",
        "watching": "Em observação. Última PTAX {latest} ({latest_date}); a entrada exige dois fechamentos abaixo de {entry}.",
        "entered": "Condições de entrada atendidas em {date}, a {value} (simulado). Última PTAX {latest} ({latest_date}).",
        "review": "A posição simulada chegou à zona de reavaliação em {date} ({value}). Reavaliar antes de qualquer outra decisão.",
        "exited": "Posição simulada encerrada pela regra de saída em {date}, a {value}.",
        "abandoned": "Ideia abandonada: a PTAX fechou a {value} em {date}, acima de {abandon}.",
        "expired": "A data de revisão ({review_by}) passou sem entrada. Esta tese precisa ser atualizada.",
        "unavailable": "Verificação indisponível: o histórico salvo da PTAX não pôde ser lido.",
    },
    "tape_label": "Dados oficiais mais recentes",
    "tape": {
        "selic_target": "Meta Selic",
        "fed_target_range": "Juro do Fed (faixa)",
        "brazil_us_policy_differential": "Diferencial Brasil–EUA",
        "ptax_usd_brl_midpoint": "USD/BRL (PTAX)",
        "us_2_year_treasury": "Juro dos EUA, 2 anos",
        "brent": "Petróleo Brent (à vista)",
    },
    "fresh": {"fresh": "Atualizado", "delayed": "Atrasado", "stale": "Desatualizado", "unknown": "Data desconhecida"},
    "stale_banner": "Alguns números estão mais antigos que o normal (marcados abaixo). A página mostra cada valor com a sua data em vez de escondê-lo.",
    "refresh_banner": "A atualização automática não roda desde {date}. Os números abaixo aparecem com as datas originais.",
    "unavailable": "Indisponível",
    "na": "n/d",
    "download": "Baixar o relatório (PDF, português)",
    "download_help": "4 páginas, a mesma tese datada desta página, gerado a partir dos arquivos salvos",

    "review_title": "O que aconteceu com a minha tese de 24 de setembro",
    "review_intro": "Em 24 de setembro eu disse que a eleição de {first_round} decidiria o próximo movimento e planejei comprar reais depois de dois fechamentos da PTAX abaixo de {prev_entry}, passado o primeiro turno. Nenhuma posição chegou a ser aberta: não há desempenho a relatar, só raciocínio a conferir.",
    "review_head": ("O que eu esperava", "O que aconteceu", "Veredito"),
    "review_rows": {
        "trigger": ("Agir só depois do primeiro turno, abaixo de {prev_entry}; abandonar acima de {prev_abandon}.", "Desde 24 de setembro a PTAX fechou entre {ptax_low} ({ptax_low_date}) e {ptax_high} ({ptax_high_date}). Nenhum nível foi atingido; nenhuma entrada era possível antes da votação."),
        "election": ("Indefinida: o Datafolha tinha Lula com {prev_lula}% e Flávio Bolsonaro com {prev_flavio}% no primeiro turno (±{prev_moe}).", "Um segundo turno era necessário, mas Flávio terminou na frente: os últimos Datafolha e Quaest erraram a margem em {dat_miss} e {que_miss}."),
        "cushion": ("O grande colchão de juros sustenta o real.", "O diferencial ficou em {gap}, mas o USD/BRL subiu para {ptax} ({ptax_chg}), o maior fechamento em quatro meses. O real segurou a faixa sem se fortalecer."),
        "premium": ("O juro brasileiro de dois anos está bem acima do caminho dos economistas: um prêmio de risco.", "O juro de dois anos foi de {prev_br_2y} para {br_2y} entre 23/9 e 2/10; a diferença para o caminho dos economistas ficou perto de {gap_2y}. O prêmio não diminuiu antes da votação; o segundo turno vai testá-lo."),
        "us_yields": ("O juro americano de dois anos fica em até {us2y_max}.", "{us2y_prev} → {us2y}; maior fechamento {us2y_high} ({us2y_high_date}). A condição foi mantida."),
    },
    "verdicts": {"confirmed": "Confirmado", "partly": "Em parte", "unresolved": "Em aberto", "not_triggered": "Não acionado", "underweighted": "Subestimado"},
    "review_lesson_label": "O que eu mudei",
    "review_lesson": "Tratei as pesquisas como razoavelmente certas e o primeiro turno como decisivo. Nenhuma das duas coisas se confirmou: as pesquisas erraram por vários pontos, e o primeiro turno apenas reduziu a pergunta a um segundo turno. A nova tese leva a decisão para o segundo turno.",

    "evidence_title": "As evidências, separadas por tipo",
    "evidence_intro": "Cada item tem um rótulo para separar fatos, preços, projeções e a minha leitura. Os valores estão congelados na data da tese ({as_of}). Os preços de mercado são de 2 de outubro, o último pregão antes da votação; os mercados reabrem em {first_monday}. Os números atualizados estão no topo da página.",
    "kinds": {"fact": "Fato", "pricing": "Preço de mercado", "survey": "Pesquisas e projeções", "interpretation": "Minha interpretação"},
    "kind_help": {
        "fact": "Algo que aconteceu.",
        "pricing": "O que os preços indicam hoje.",
        "survey": "O que analistas e autoridades esperam.",
        "interpretation": "A minha leitura, que pode estar errada.",
    },
    "evidence": {
        "fact": [
            "O Brasil votou em {first_round}. Com {counted} das urnas apuradas, Flávio Bolsonaro (PL) tem {fl_share} dos votos válidos e Lula (PT), {lu_share}, uma diferença de {margin_votes} de votos. Ninguém chegou a 50%, então o segundo turno será em {runoff}. Os demais candidatos (Cury, Santos, Caiado, Zema e outros) somaram {oth_share}.",
            "Últimas pesquisas, votos válidos: Datafolha (3/10) Lula {dat_lula}%, Flávio {dat_flavio}%; Quaest (2 e 3/10) Lula {que_lula}%, Flávio {que_flavio}%. Ambas mostravam empate técnico. Cenários de segundo turno (votos totais), Lula–Flávio: Datafolha {dat_r_lula}–{dat_r_flavio}, Quaest {que_r_lula}–{que_r_flavio}.",
            "Nenhum dos dois bancos centrais se reuniu desde 16 de setembro: o Copom cortou a Selic em 0,25 p.p., para {selic} (por unanimidade, o {cuts_count}º corte seguido e {cuts_total} desde março), e o Fed subiu sua faixa em 0,25 p.p., para {fed_range} (12 a 0). O diferencial entre os juros básicos é de {gap}. Próximas decisões: Fed em {fomc_next}, Copom em {copom_next}.",
            "Para 2027, o projeto de Orçamento do governo prevê superávit primário de {fiscal_gov}; a Instituição Fiscal Independente do Senado projeta déficit de {fiscal_ifi}.",
        ],
        "pricing": [
            "O USD/BRL (PTAX) fechou a {ptax} em {ptax_date}, o último pregão antes da votação: {ptax_chg} desde 24 de setembro e o maior fechamento dos quatro meses salvos (mínima: {low4m}).",
            "O juro do Tesouro americano de dois anos estava em {us2y} em {ptax_date} (era {us2y_prev} em 24/9); o de dez anos, em {us10y}.",
            "Curva prefixada brasileira (ANBIMA, 2/10): um ano {br_1y}, dois anos {br_2y}, cerca de {gap_2y} acima da taxa implícita nas próprias projeções dos economistas ({survey_2y}). Inflação implícita na curva em dois anos: {be_2y}.",
            "Brent: o preço à vista da EIA estava em {brent} em {brent_date}, abaixo do pico de {brent_peak} de {brent_peak_date}, mas ainda acima de US$ 100.",
        ],
        "survey": [
            "Medianas da pesquisa Focus ({focus_date}): Selic de {focus_selic26} no fim de 2026 e {focus_selic27} no fim de 2027; inflação de {focus_ipca26} em 2026 e {focus_ipca27} em 2027; USD/BRL a {focus_fx26} no fim de 2026.",
            "Projeção mediana dos dirigentes do Fed: {fed_proj_2026} no fim de 2026 (mais uma alta de 0,25 p.p.), acima dos {fed_proj_june} de junho.",
            "JPMorgan (28/9): depois da eleição, o USD/BRL poderia ir de cerca de {jpm_low}, com um sinal fiscal favorável, mesmo que incremental, a cerca de {jpm_high}, se o resultado for lido como ruim para a consolidação fiscal. O banco via o real perto do valor justo, posições compradas em real acima das de eleições anteriores, opções precificando cerca de {jpm_event} de movimentos de evento nos dois turnos, juro real de {jpm_real} (contra {jpm_real22} em 2022) e dívida bruta de {jpm_debt} do PIB (contra {jpm_debt22}).",
        ],
        "interpretation": [
            "Aritmética do segundo turno: mantidos constantes o comparecimento e os votos em branco, Flávio precisa de {need_fl} dos {oth_share} que votaram em outros candidatos, e Lula de {need_lu}. Nenhum candidato desse grupo é de esquerda; por isso leio isso como favorável a Flávio, sem atribuir probabilidade.",
            "Primeiros turnos passados: depois de 2014, 2018 e 2022, o USD/BRL caiu entre {ev_min} e {ev_max} no primeiro dia útil. Até a sexta-feira anterior ao segundo turno, devolveu {gb_2014} (2014) e {gb_2022} (2022) desse movimento; em 2018, ampliou-o em mais {gb_2018} desse movimento. Três eleições são uma referência, não um teste, mas desaconselham pagar pela primeira segunda-feira.",
            "Níveis frente à volatilidade: um movimento de 15 pregões tem desvio-padrão de {vol15} ({vol_ann} ao ano). A entrada fica {entry_sigma} σ abaixo do fechamento de sexta e o nível de abandono {abandon_sigma} σ acima, enquanto uma primeira segunda-feira típica moveu {event_sigma} σ: são gatilhos, não stop-loss.",
        ],
    },
    "focus_table_caption": "Medianas da pesquisa Focus, {focus_date}",
    "focus_rows": ("Selic, fim do ano", "Inflação (IPCA)", "USD/BRL, fim do ano"),
    "chart_title": "USD/BRL (PTAX): últimos {n} pregões e meus níveis de decisão",
    "chart_desc": "Fechamentos diários da PTAX de {start} a {end}. Último {latest}. Níveis: entrada abaixo de {entry}, saída acima de {exit}, abandono acima de {abandon}; pontilhado: mediana dos economistas para o fim do ano, {focus_fx26}.",
    "chart_labels": {"entry": "Entrada < {entry}", "exit": "Saída > {exit}", "abandon": "Abandono > {abandon}", "prev": "Focus fim de 2026 {focus_fx26}", "event": "Decisões de 16/9"},
    "chart_table": "Ver os dados do gráfico em tabela",
    "chart_cols": ("Data", "PTAX"),

    "paths_title": "O que pode acontecer antes e depois de {runoff}",
    "paths_intro": "Três caminhos que consigo reconhecer nos dados, mais um choque externo. Não atribuo probabilidades: o objetivo é decidir antes o que cada um significaria e o que eu faria.",
    "path_fields": ("Sinais", "O que significaria", "O que eu faria"),
    "paths": [
        ("O prêmio de risco cai depois do segundo turno", "Depois de {runoff}, dois fechamentos da PTAX abaixo de {entry}; o juro de dois anos cai 0,25 ponto ou mais a partir de {br_2y}; o vencedor mostra um caminho fiscal crível.", "Os investidores veem menos risco fiscal e o colchão de juros continua atraindo recursos.", "Comprar reais na operação simulada se o juro americano de dois anos estiver em até {us2y_max}."),
        ("A alta do primeiro turno se desfaz", "A PTAX devolve a maior parte do movimento pós-votação antes de {runoff} e volta acima de {exit}; as pesquisas se apertam.", "O mercado duvida do sinal do primeiro turno, como em 2014 e 2022.", "Sem posição. Esperar {runoff}."),
        ("O prêmio de risco sobe", "A PTAX fecha acima de {abandon}; o juro de dois anos passa de {br2y_max}; a inflação implícita sobe.", "As preocupações fiscais dominam; um real mais fraco com petróleo caro pode levar o Copom a pausar os cortes.", "Abandonar a ideia de comprar reais. Uma operação comprada em dólar exigiria regras novas."),
        ("Choque externo: juros americanos ou petróleo", "O juro americano de dois anos passa de {us2y_exit}, ou o Brent cai com força com a reabertura de Ormuz.", "As moedas emergentes tendem a enfraquecer juntas; petróleo mais barato retira um apoio.", "Nenhuma posição comprada em reais; sair se já estiver posicionado."),
    ],
    "calendar_label": "Datas que importam",
    "calendar": {"election_first": "Eleição, primeiro turno", "election_runoff": "Segundo turno da eleição presidencial", "fomc": "Decisão do Fed", "copom": "Decisão do Copom", "both": "Decisões do Fed e do Copom"},

    "trade_title": "A operação simulada: esperar o segundo turno e comprar reais só com confirmação do mercado",
    "trade_status": "Inativa, sem posição · entrada possível a partir de {earliest}",
    "trade_rows": [
        ("Expressão", "Comprado em reais contra o dólar (vendido em USD/BRL), acompanhado pela PTAX oficial. Apenas simulação: sem dinheiro, sem execução."),
        ("Tese", "Se a eleição reduzir o prêmio de risco fiscal, o real deve se valorizar e continuar mais forte, porque os investidores seguem recebendo um grande colchão de juros enquanto esperam."),
        ("Por que pode não estar no preço", "O juro de dois anos está {gap_2y} acima do caminho dos próprios economistas, que esperam o USD/BRL a {focus_fx26} no fim do ano; um real mais forte de forma duradoura não é o consenso. Mas o JPMorgan vê o real perto do valor justo, com posições compradas elevadas: parte da boa notícia pode já estar no preço."),
        ("Catalisadores", "Segundo turno em {runoff}; Fed em {fomc_next}; Copom em {copom_next}."),
        ("Entrada", "A partir de {earliest}, primeira PTAX depois do segundo turno: dois fechamentos diários seguidos abaixo de {entry}, com o juro americano de dois anos em até {us2y_max}. Fechamentos anteriores, inclusive qualquer alta em {first_monday}, não contam."),
        ("Abandonar a ideia (antes da entrada)", "Qualquer fechamento da PTAX acima de {abandon}, acima de todos os fechamentos dos últimos quatro meses (máxima de {high4m} em {high4m_date}). A ideia é abandonada, não invertida."),
        ("Saída (depois da entrada)", "Dois fechamentos seguidos acima de {exit} (topo dos últimos 20 fechamentos) ou o juro americano de dois anos acima de {us2y_exit}."),
        ("Reavaliação", "Perto de {review_low}–{review_high} (mínima da faixa menos a amplitude da faixa), ou no máximo em {review_by}. Uma zona de reavaliação, não um alvo."),
    ],
    "trade_more": "Riscos, o que mudaria a minha visão e o canal das commodities",
    "trade_risks_label": "Principais riscos",
    "trade_risks": [
        "O plano fiscal do vencedor é lido como negativo, seja quem for.",
        "Compro depois do movimento: parte da boa notícia pode já estar no preço, e as posições compradas em real já eram altas.",
        "Os juros americanos continuam subindo e tiram recursos dos mercados emergentes, ou o petróleo cai com força com a reabertura de Ormuz, reduzindo a receita de exportação e abrindo espaço para cortes mais rápidos do Copom.",
    ],
    "trade_change_label": "Evidências que mudariam a minha visão",
    "trade_change": "Além dos gatilhos acima: sinal do Copom de cortes mais rápidos, vencedor sem plano fiscal crível ou forte piora nos números fiscais oficiais.",
    "trade_channels_label": "Canais das commodities e da geopolítica",
    "trade_channels": "O Brasil exporta mais petróleo do que importa, então preços altos ajudam as contas externas. Eles também mantêm vivo o risco de inflação, o que deixa o Copom cauteloso e o colchão de juros largo. Uma reabertura do Estreito de Ormuz enfraqueceria os dois apoios ao mesmo tempo. Minério de ferro e soja dificilmente vão decidir esta janela (veja abaixo).",
    "trade_math_label": "A conta: carry e volatilidade",
    "trade_math": "Carry: ((1 + {selic}) ÷ (1 + {fed_mid}))^(1/12) − 1 ≈ {carry} por mês. Uma posição real recebe esse ganho pelos preços a termo, não pela PTAX; por isso os níveis de decisão o ignoram. Volatilidade: desvio-padrão diário de {vol_daily} nos últimos 20 pregões, vezes √15 pregões até o segundo turno, dá {vol15} (cerca de {vol15_brl} na PTAX). O nível de entrada está {entry_sigma} σ abaixo do fechamento de sexta, o de abandono {abandon_sigma} σ acima, e uma primeira segunda-feira típica moveu {event_sigma} σ: um salto na abertura pode pular todos os níveis.",

    "commodities_title": "Os preços das exportações brasileiras: quais importam agora?",
    "commodities_intro": "O Brasil recebe dólares exportando petróleo, minério de ferro, soja e açúcar. Cada série mantém a sua data e frequência; elas não são combinadas num índice.",
    "commodity_cols": ("Commodity", "Último", "Variação", "Importa nas próximas seis semanas?"),
    "commodity_names": {"brent": "Petróleo (Brent à vista)", "iron_ore": "Minério de ferro", "soybeans": "Soja", "sugar": "Açúcar"},
    "commodity_verdicts": {
        "brent": ("Sim, nos dois sentidos", "Apoia a receita de exportação e mantém o Copom cauteloso; uma reabertura repentina de Ormuz eliminaria os dois efeitos. O preço à vista continua acima de US$ 100, mas abaixo do pico de {brent_peak} de meados de setembro."),
        "iron_ore": ("Agora, não", "O preço mensal do FMI recuou em julho. Sem mudança clara na demanda chinesa por aço, dificilmente move o real em seis semanas, embora importe diretamente para a Vale."),
        "soybeans": ("Pouco", "Os preços subiram em julho, mas a temporada de exportação brasileira se concentra entre março e julho; menos dólares da soja entram no quarto trimestre."),
        "sugar": ("Pouco", "As usinas podem alternar a cana entre açúcar e etanol; petróleo caro torna o etanol mais atraente, o que pode apertar a oferta de açúcar. É mais uma história de empresas do que de câmbio."),
    },
    "vs": "vs.",
    "units": {"USD per barrel": "US$/barril", "USD per metric ton": "US$/t", "US cents per pound": "¢ US$/lb"},
    "freq": {"daily": "diária", "weekly": "semanal", "monthly": "mensal", "quarterly": "trimestral"},

    "equity_title": "Do preço da commodity à empresa",
    "equity_intro": "Um movimento de preço é só o ponto de partida. Antes de chamar uma produtora de investimento, eu testaria quanto desse movimento chega à receita, às margens, ao caixa e ao valuation.",
    "equity_steps": [
        ("Exposição da receita", "O que a empresa realmente vende, a que preço realizado, em que moeda, e quanto está protegido por hedge?"),
        ("Margens e curva de custos", "Um preço maior vira lucro depois de energia, frete e câmbio? Onde a produtora está na curva de custos do setor?"),
        ("Balanço", "Ela consegue usar bem o caixa: alavancagem, investimentos, dividendos e recompras?"),
        ("Valuation", "A oportunidade já está no preço, com premissas normais e adversas, e o que provaria que a tese está errada?"),
    ],
    "equity_examples_label": "Por onde eu começaria no Brasil",
    "equity_examples": "Petrobras (preço realizado do petróleo e uma política de preços de combustíveis politicamente sensível em ano eleitoral); Vale (minério, China, frete); uma produtora de açúcar e etanol (a flexibilidade entre os dois). Pontos de partida para perguntas, não recomendações.",

    "method_title": "Método, dados e limitações",
    "method_calc_label": "Como os números são calculados",
    "method_calc": [
        ("Diferencial de juros", "Meta Selic menos o ponto médio da faixa do Fed. Compara juros básicos; não é um retorno de investimento."),
        ("Carry", "((1 + Selic) ÷ (1 + ponto médio do Fed))^(1/12) − 1, uma conta mensal aproximada que ignora custos."),
        ("Níveis de decisão", "Tirados dos últimos 20 fechamentos da PTAX na data da tese ({range_low}–{range_high}), arredondados para duas casas. A zona de reavaliação é a mínima da faixa menos a sua amplitude."),
        ("Mercado vs. economistas", "Caminho dos economistas: uma linha reta da Selic atual até as medianas Focus de fim de ano, menos 0,10 p.p. (a diferença usual entre o CDI e a Selic), capitalizada e anualizada em um e dois anos, e comparada com as taxas prefixadas de cupom zero da ANBIMA: um ano {survey_1y} vs. {br_1y}; dois anos {survey_2y} vs. {br_2y}."),
        ("Atualidade", "Séries diárias ficam “atrasadas” após 4 dias e “desatualizadas” após 7; a pesquisa Focus semanal, após 10 e 17; os preços mensais do FMI, após 100 e 130 dias do início do mês a que se referem."),
        ("Aritmética do segundo turno", "Um finalista com parcela s dos votos válidos precisa de (50 − s) ÷ (parcela dos demais candidatos) dos eleitores desses candidatos, mantidos constantes o comparecimento e os votos em branco."),
        ("Erro das pesquisas", "Margem do resultado (Flávio menos Lula, votos válidos) menos a margem de cada pesquisa na mesma base. Datafolha e Quaest publicam versões em votos válidos; a apuração estava {counted} completa."),
        ("Reações aos primeiros turnos", "PTAX no primeiro dia útil depois da votação contra o último fechamento anterior, em 2014, 2018 e 2022; e a parcela desse movimento desfeita até a sexta-feira anterior ao segundo turno."),
        ("Volatilidade", "Desvio-padrão dos últimos 20 retornos logarítmicos diários da PTAX, multiplicado pela raiz de 15 pregões; os níveis são expressos em múltiplos dele."),
    ],
    "data_label": "Situação dos dados",
    "data_cols": ("Série", "Valor", "Observado", "Frequência", "Fonte", "Situação"),
    "series_names": {
        "selic_target": "Meta Selic", "fed_target_range": "Faixa do Fed", "brazil_us_policy_differential": "Diferencial Brasil–EUA",
        "ptax_usd_brl_midpoint": "PTAX USD/BRL", "us_2_year_treasury": "Juro dos EUA, 2 anos", "us_10_year_treasury": "Juro dos EUA, 10 anos",
        "focus_selic": "Focus Selic, fim de {year}", "focus_ipca": "Focus inflação, {year}", "focus_fx": "Focus USD/BRL, fim de {year}",
        "brent": "Brent à vista", "iron_ore": "Minério de ferro (FMI)", "soybeans": "Soja (FMI)", "sugar": "Açúcar (FMI)",
    },
    "refresh_label": "Como os dados são atualizados",
    "refresh_text": "Uma rotina do GitHub Actions roda depois do fechamento do mercado brasileiro em dias úteis. Ela consulta cada fonte oficial separadamente, valida os dados e salva um pequeno arquivo que esta página lê. Os visitantes nunca disparam uma consulta. Uma fonte com falha mantém o último valor válido, com a data original, e a falha é registrada. Uma segunda etapa marca a rotina como falha quando os números principais têm mais de uma semana.",
    "refresh_status": "Última tentativa de atualização: {attempted} · {ok} de {total} fontes atualizadas.",
    "refresh_failed": "Não atualizadas na última tentativa: {names}.",
    "refresh_history": "Até 24 de setembro de 2026, esta rotina falhava sem aviso nos dados americanos e a página continuava mostrando números de 13 de setembro. Isso foi corrigido: as fontes agora são independentes, os dados dos EUA têm alternativas oficiais e dados desatualizados deixam a rotina em vermelho.",
    "limits_label": "Limitações",
    "limits": [
        "A PTAX é uma taxa de referência, não um preço negociável; custos, spreads e tamanho da posição não são modelados.",
        "A curva brasileira (ANBIMA) é coletada manualmente na data da tese; não é atualizada.",
        "Os preços de mercado são de 2 de outubro, antes do resultado, e a apuração estava {counted} completa; as parcelas ainda podem variar.",
        "A Focus é uma pesquisa, não um compromisso; a diferença entre mercado e economistas mistura expectativas e prêmio de risco.",
        "Os cenários de bancos e os números das opções vêm de reportagens sobre a pesquisa do JPMorgan, não da nota original.",
        "Não atribuo probabilidades. As regras não foram testadas em dados históricos, e o estudo dos primeiros turnos cobre só três eleições.",
        "Ferramentas de IA ajudaram a escrever código, rascunhar textos de pesquisa e traduzir. As regras e o julgamento final são meus, e cada número tem link para a fonte.",
    ],
    "sources_label": "Fontes",
    "sources_note": "Os links levam à fonte oficial ou, no contexto político e do petróleo, à reportagem utilizada. As datas indicam a que momento cada observação se refere.",
    "archive_label": "Tese anterior",
    "archive": "A tese completa de 24 de setembro (visão, regras e dados salvos) está preservada sem alterações no repositório, em research/thesis_2026-09-24.json; o estudo de 13 de setembro está em research/data_snapshot.json.",

    "about_title": "Sobre o projeto",
    "about": "Sou Romeo Mugnier de Almeida, estudante de engenharia mecânica na EPFL, com raízes brasileiras e francesas. Comecei este projeto para entender como juros, câmbio e commodities interagem no Brasil, e o mantenho como um diário de pesquisa datado: cada visão vem com regras escritas antes do resultado, e cada visão antiga é revisada, inclusive no que errei.",
    "about_build": "Feito com Python e Streamlit. Dados oficiais do Banco Central do Brasil, do Tesouro americano, do Fed de Nova York e do FRED; atualização programada com validação por fonte; testes automatizados para os cálculos, as traduções, as regras de atualidade e os PDFs.",
    "links": {"code": "Código no GitHub", "linkedin": "LinkedIn"},
    "footer": "Pesquisa educacional, não é recomendação de investimento. Sem posições reais e sem desempenho alegado. Tese datada de {as_of}; cada número mostra a sua data.",

    "pdf_title": "Brasil macro: carry, eleição e uma operação condicional",
    "pdf_subtitle": "Relatório de pesquisa · tese datada de {as_of}",
    "pdf_page": "Página",
}

# ---------------------------------------------------------------------------
# French
TEXT["fr"] = {
    "html_lang": "fr",
    "language_label": "Langue",
    "skip": "Aller à la vue actuelle",
    "byline": "Génie mécanique à l’EPFL · brésilien et français",
    "kicker": "Brésil · taux d’intérêt · real · matières premières",
    "title": "Le Brésil, de la politique monétaire aux marchés.",
    "intro": "Un carnet de recherche d’étudiant sur la façon dont les taux brésiliens et américains, le real et les principales exportations du Brésil évoluent ensemble. Chaque vue est datée, s’appuie sur des données officielles avec lien et s’accompagne des règles qui me feraient agir ou changer d’avis.",
    "nav": {"view": "Vue actuelle", "review": "Bilan de la dernière thèse", "evidence": "Données", "paths": "Scénarios", "trade": "Opération fictive", "commodities": "Matières premières", "method": "Méthode et données"},
    "nav_label": "Sections",
    "view_label": "Ma vue actuelle",
    "status_no_position": "Aucune position",
    "view_headline": "L’avance de Flávio Bolsonaro au premier tour est une surprise, pas un verdict. Lors de deux des trois dernières élections, le real a rendu l’essentiel de sa hausse post-vote avant le second tour ; je reste donc en dehors jusqu’au {runoff} et n’agis que si les prix confirment.",
    "why_label": "Pourquoi",
    "why": [
        ("Le premier tour a surpris.", "Flávio Bolsonaro a recueilli {fl_share} des suffrages exprimés, contre {lu_share} pour Lula. Les derniers sondages Datafolha et Quaest donnaient Lula devant de {dat_lead} et {que_lead} points : ils se sont trompés sur l’écart de {dat_miss} et {que_miss}, dans le même sens."),
        ("Le second tour n’est pas une formalité.", "{oth_share} des électeurs ont voté pour d’autres candidats. Pour atteindre 50 %, Flávio a besoin de {need_fl} d’entre eux et Lula de {need_lu}. Aucun candidat de ce groupe n’est de gauche ; j’y vois un avantage pour Flávio, mais ce n’est pas une prévision."),
        ("Le marché a déjà vu ce film.", "L’USD/BRL a reculé de {ev_min} à {ev_max} le premier lundi après les premiers tours de 2014, 2018 et 2022. Avant le second tour, il avait rendu {gb_2014} (2014) et {gb_2022} (2022) du mouvement ; en 2018, il a continué de baisser. Les positions acheteuses sur le real dépassaient déjà celles des élections passées (JPMorgan)."),
    ],
    "act_label": "Ce qui me ferait agir",
    "act": "Après le second tour, à partir du {earliest} : deux clôtures quotidiennes de la PTAX sous {entry}, avec un taux américain à deux ans inférieur ou égal à {us2y_max}. J’y verrais le marché payer pour une trajectoire budgétaire crédible, et j’achèterais des reais dans l’opération fictive. Les clôtures antérieures, y compris toute hausse du premier lundi, ne comptent pas.",
    "change_label": "Ce qui me ferait changer d’avis",
    "change": "Une clôture de la PTAX au-dessus de {abandon} avant toute entrée, un taux brésilien à deux ans au-dessus de {br2y_max} ou un taux américain à deux ans au-dessus de {us2y_exit}. Chacun signifierait que le risque augmente, et non qu’il diminue.",
    "monitor_label": "Vérification des règles",
    "monitor_note": "Comparaison automatique des données PTAX enregistrées avec les règles ci-dessus. Une vérification mécanique, pas une position réelle.",
    "monitor": {
        "waiting": "En attente du second tour. Dernière PTAX {latest} ({latest_date}) ; aucune entrée n’est possible avant le {earliest}.",
        "watching": "Sous surveillance. Dernière PTAX {latest} ({latest_date}) ; l’entrée exige deux clôtures sous {entry}.",
        "entered": "Conditions d’entrée réunies le {date} à {value} (fictif). Dernière PTAX {latest} ({latest_date}).",
        "review": "La position fictive a atteint la zone de réexamen le {date} ({value}). Réexaminer avant toute autre décision.",
        "exited": "Position fictive clôturée par la règle de sortie le {date} à {value}.",
        "abandoned": "Idée abandonnée : la PTAX a clôturé à {value} le {date}, au-dessus de {abandon}.",
        "expired": "La date de réexamen ({review_by}) est passée sans entrée. Cette thèse doit être mise à jour.",
        "unavailable": "Vérification indisponible : l’historique PTAX enregistré n’a pas pu être lu.",
    },
    "tape_label": "Dernières données officielles",
    "tape": {
        "selic_target": "Taux Selic",
        "fed_target_range": "Fourchette de la Fed",
        "brazil_us_policy_differential": "Écart Brésil–États-Unis",
        "ptax_usd_brl_midpoint": "USD/BRL (PTAX)",
        "us_2_year_treasury": "Taux US à 2 ans",
        "brent": "Brent (comptant)",
    },
    "fresh": {"fresh": "À jour", "delayed": "En retard", "stale": "Périmé", "unknown": "Date inconnue"},
    "stale_banner": "Certains chiffres sont plus anciens que d’habitude (signalés ci-dessous). La page affiche chaque valeur avec sa propre date au lieu de la masquer.",
    "refresh_banner": "La mise à jour automatique n’a pas tourné depuis le {date}. Les chiffres ci-dessous gardent leur date d’origine.",
    "unavailable": "Indisponible",
    "na": "n.d.",
    "download": "Télécharger la note de recherche (PDF, français)",
    "download_help": "4 pages, la même thèse datée que cette page, générée à partir des fichiers enregistrés",

    "review_title": "Ce qu’est devenue ma thèse du 24 septembre",
    "review_intro": "Le 24 septembre, j’ai écrit que l’élection du {first_round} déciderait du prochain mouvement et je prévoyais d’acheter le real après deux clôtures de la PTAX sous {prev_entry}, une fois le premier tour passé. Aucune position n’a été ouverte : pas de performance à présenter, seulement un raisonnement à vérifier.",
    "review_head": ("Ce que j’attendais", "Ce qui s’est passé", "Verdict"),
    "review_rows": {
        "trigger": ("Agir seulement après le premier tour, sous {prev_entry} ; abandonner au-dessus de {prev_abandon}.", "Depuis le 24 septembre, la PTAX a clôturé entre {ptax_low} ({ptax_low_date}) et {ptax_high} ({ptax_high_date}). Aucun niveau n’a été atteint ; aucune entrée n’était possible avant le vote."),
        "election": ("Trop serrée pour être prévue : Datafolha donnait Lula à {prev_lula} % et Flávio Bolsonaro à {prev_flavio} % au premier tour (±{prev_moe}).", "Un second tour était nécessaire, mais Flávio est arrivé en tête : les derniers Datafolha et Quaest se sont trompés sur l’écart de {dat_miss} et {que_miss}."),
        "cushion": ("Le large coussin de taux soutient le real.", "L’écart est resté à {gap}, mais l’USD/BRL a monté à {ptax} ({ptax_chg}), sa plus haute clôture en quatre mois. Le real a tenu sa fourchette sans se renforcer."),
        "premium": ("Le taux brésilien à deux ans est bien au-dessus du chemin des économistes : une prime de risque.", "Le taux à deux ans est passé de {prev_br_2y} à {br_2y} entre le 23 sept. et le 2 oct. ; son écart avec le chemin des économistes est resté proche de {gap_2y}. La prime ne s’est pas comprimée avant le vote ; le second tour la mettra à l’épreuve."),
        "us_yields": ("Le taux américain à deux ans reste inférieur ou égal à {us2y_max}.", "{us2y_prev} → {us2y} ; plus haute clôture {us2y_high} ({us2y_high_date}). La condition a tenu."),
    },
    "verdicts": {"confirmed": "Confirmé", "partly": "En partie", "unresolved": "Non tranché", "not_triggered": "Non déclenché", "underweighted": "Sous-estimé"},
    "review_lesson_label": "Ce que j’ai corrigé",
    "review_lesson": "J’ai traité les sondages comme à peu près justes et le premier tour comme décisif. Aucun des deux ne s’est vérifié : les sondages se sont trompés de plusieurs points, et le premier tour a seulement ramené la question à un second tour. La nouvelle thèse déplace la décision au second tour.",

    "evidence_title": "Les données, classées par nature",
    "evidence_intro": "Chaque élément est étiqueté pour séparer faits, prix, prévisions et ma propre lecture. Les valeurs sont figées à la date de la thèse ({as_of}). Les prix de marché datent du 2 octobre, dernière séance avant le vote ; les marchés rouvrent le {first_monday}. Les chiffres actualisés sont en haut de la page.",
    "kinds": {"fact": "Fait", "pricing": "Prix de marché", "survey": "Enquêtes et projections", "interpretation": "Mon interprétation"},
    "kind_help": {
        "fact": "Quelque chose qui s’est produit.",
        "pricing": "Ce que les prix impliquent aujourd’hui.",
        "survey": "Ce qu’attendent prévisionnistes et responsables.",
        "interpretation": "Ma lecture, qui peut être fausse.",
    },
    "evidence": {
        "fact": [
            "Le Brésil a voté le {first_round}. Avec {counted} des urnes dépouillées, Flávio Bolsonaro (PL) recueille {fl_share} des suffrages exprimés et Lula (PT) {lu_share}, soit {margin_votes} de voix d’écart. Personne n’atteint 50 %, donc le second tour a lieu le {runoff}. Les autres candidats (Cury, Santos, Caiado, Zema et d’autres) totalisent {oth_share}.",
            "Derniers sondages, suffrages exprimés : Datafolha (3 oct.) Lula {dat_lula} %, Flávio {dat_flavio} % ; Quaest (2–3 oct.) Lula {que_lula} %, Flávio {que_flavio} %. Tous deux indiquaient une égalité statistique. Scénarios de second tour (total des voix), Lula–Flávio : Datafolha {dat_r_lula}–{dat_r_flavio}, Quaest {que_r_lula}–{que_r_flavio}.",
            "Aucune des deux banques centrales ne s’est réunie depuis le 16 septembre : le Copom a abaissé le Selic de 0,25 pt à {selic} (à l’unanimité, sa {cuts_count}e baisse consécutive et {cuts_total} depuis mars), et la Fed a relevé sa fourchette de 0,25 pt à {fed_range} (12 voix contre 0). L’écart entre les taux directeurs est de {gap}. Prochaines décisions : Fed le {fomc_next}, Copom le {copom_next}.",
            "Pour 2027, le projet de budget du gouvernement prévoit un excédent primaire de {fiscal_gov} ; l’Institution budgétaire indépendante du Sénat prévoit un déficit de {fiscal_ifi}.",
        ],
        "pricing": [
            "L’USD/BRL (PTAX) a clôturé à {ptax} le {ptax_date}, dernière séance avant le vote : {ptax_chg} depuis le 24 septembre et plus haute clôture des quatre mois enregistrés (plus bas : {low4m}).",
            "Le taux du Trésor américain à deux ans était de {us2y} le {ptax_date} (contre {us2y_prev} le 24 sept.) ; le dix ans était à {us10y}.",
            "Courbe brésilienne à taux fixe (ANBIMA, 2 oct.) : un an {br_1y}, deux ans {br_2y}, soit environ {gap_2y} au-dessus du taux implicite dans les prévisions mêmes des économistes ({survey_2y}). Inflation implicite dans la courbe sur deux ans : {be_2y}.",
            "Brent : le prix au comptant de l’EIA était de {brent} le {brent_date}, sous son pic de {brent_peak} du {brent_peak_date} mais encore au-dessus de 100 $.",
        ],
        "survey": [
            "Médianes de l’enquête Focus ({focus_date}) : Selic à {focus_selic26} fin 2026 et {focus_selic27} fin 2027 ; inflation de {focus_ipca26} en 2026 et {focus_ipca27} en 2027 ; USD/BRL à {focus_fx26} fin 2026.",
            "Projection médiane des responsables de la Fed : {fed_proj_2026} fin 2026 (une hausse supplémentaire de 0,25 pt), contre {fed_proj_june} en juin.",
            "JPMorgan (28 sept.) : après l’élection, l’USD/BRL pourrait aller d’environ {jpm_low}, avec un signal budgétaire favorable même limité, à environ {jpm_high}, si le résultat est jugé mauvais pour la consolidation budgétaire. La banque voyait le real proche de sa juste valeur, des positions acheteuses sur le real supérieures à celles des élections passées, des options valorisant environ {jpm_event} de mouvements d’événement sur les deux tours, un taux réel de {jpm_real} (contre {jpm_real22} en 2022) et une dette brute de {jpm_debt} du PIB (contre {jpm_debt22}).",
        ],
        "interpretation": [
            "Arithmétique du second tour : à participation et votes blancs constants, Flávio a besoin de {need_fl} des {oth_share} qui ont voté pour d’autres candidats, et Lula de {need_lu}. Aucun candidat de ce groupe n’est de gauche ; j’y vois donc un avantage pour Flávio, sans y attacher de probabilité.",
            "Premiers tours passés : après 2014, 2018 et 2022, l’USD/BRL a reculé de {ev_min} à {ev_max} le premier jour ouvré. Le vendredi précédant le second tour, il avait rendu {gb_2014} (2014) et {gb_2022} (2022) de ce mouvement ; en 2018, il l’a prolongé de {gb_2018} de plus. Trois élections : une référence, pas un test ; elles déconseillent de payer le premier lundi.",
            "Niveaux face à la volatilité : un mouvement sur 15 séances a un écart-type de {vol15} ({vol_ann} par an). L’entrée se situe à {entry_sigma} σ sous la clôture de vendredi et le niveau d’abandon à {abandon_sigma} σ au-dessus, alors qu’un premier lundi typique a bougé de {event_sigma} σ : ce sont des déclencheurs, pas des stop-loss.",
        ],
    },
    "focus_table_caption": "Médianes de l’enquête Focus, {focus_date}",
    "focus_rows": ("Selic, fin d’année", "Inflation (IPCA)", "USD/BRL, fin d’année"),
    "chart_title": "USD/BRL (PTAX) : {n} dernières séances et mes niveaux de décision",
    "chart_desc": "Clôtures quotidiennes de la PTAX du {start} au {end}. Dernière valeur {latest}. Niveaux : entrée sous {entry}, sortie au-dessus de {exit}, abandon au-dessus de {abandon} ; en pointillé : la médiane des économistes pour fin d’année, {focus_fx26}.",
    "chart_labels": {"entry": "Entrée < {entry}", "exit": "Sortie > {exit}", "abandon": "Abandon > {abandon}", "prev": "Focus fin 2026 {focus_fx26}", "event": "Décisions du 16 sept."},
    "chart_table": "Afficher les données du graphique sous forme de tableau",
    "chart_cols": ("Date", "PTAX"),

    "paths_title": "Ce qui peut se passer avant et après le {runoff}",
    "paths_intro": "Trois scénarios que je sais reconnaître dans les données, plus un choc extérieur. Je n’attribue pas de probabilités : il s’agit de décider à l’avance ce que chacun signifierait et ce que je ferais.",
    "path_fields": ("Signaux", "Ce que cela signifierait", "Ce que je ferais"),
    "paths": [
        ("La prime de risque baisse après le second tour", "Après le {runoff}, deux clôtures de la PTAX sous {entry} ; le taux à deux ans recule d’au moins 0,25 point depuis {br_2y} ; le vainqueur présente une trajectoire budgétaire crédible.", "Les investisseurs voient moins de risque budgétaire, et le coussin de taux continue d’attirer des capitaux.", "Acheter des reais dans l’opération fictive si le taux américain à deux ans est inférieur ou égal à {us2y_max}."),
        ("La hausse du premier tour s’estompe", "La PTAX rend l’essentiel de son mouvement post-vote avant le {runoff} et repasse au-dessus de {exit} ; les sondages se resserrent.", "Le marché doute du signal du premier tour, comme en 2014 et en 2022.", "Aucune position. Attendre le {runoff}."),
        ("La prime de risque monte", "La PTAX clôture au-dessus de {abandon} ; le taux à deux ans dépasse {br2y_max} ; l’inflation implicite augmente.", "Les inquiétudes budgétaires dominent ; un real plus faible et un pétrole cher pourraient pousser le Copom à suspendre ses baisses.", "Abandonner l’idée d’acheter des reais. Une opération à l’achat de dollars exigerait de nouvelles règles."),
        ("Choc extérieur : taux américains ou pétrole", "Le taux américain à deux ans dépasse {us2y_exit}, ou le Brent chute avec la réouverture d’Ormuz.", "Les devises émergentes ont tendance à baisser ensemble ; un pétrole moins cher retire un soutien.", "Aucune position à l’achat de reais ; sortir si elle est déjà ouverte."),
    ],
    "calendar_label": "Dates clés",
    "calendar": {"election_first": "Élection, premier tour", "election_runoff": "Second tour de l’élection présidentielle", "fomc": "Décision de la Fed", "copom": "Décision du Copom", "both": "Décisions de la Fed et du Copom"},

    "trade_title": "L’opération fictive : attendre le second tour, puis acheter le real seulement si le marché confirme",
    "trade_status": "Inactive, aucune position · entrée possible à partir du {earliest}",
    "trade_rows": [
        ("Expression", "Achat du real contre le dollar américain (vente d’USD/BRL), suivi avec le taux officiel PTAX. Opération fictive : ni argent, ni exécution."),
        ("Thèse", "Si l’élection réduit la prime de risque budgétaire, le real devrait s’apprécier et le rester, car les investisseurs continuent de toucher un large coussin de taux en attendant."),
        ("Pourquoi ce n’est peut-être pas dans les prix", "Le taux à deux ans se situe {gap_2y} au-dessus du chemin des économistes eux-mêmes, qui attendent l’USD/BRL à {focus_fx26} en fin d’année : un real durablement plus fort n’est pas le consensus. Mais JPMorgan juge le real proche de sa juste valeur, avec des positions acheteuses élevées : une partie de la bonne nouvelle est peut-être déjà dans les prix."),
        ("Catalyseurs", "Second tour le {runoff} ; Fed le {fomc_next} ; Copom le {copom_next}."),
        ("Entrée", "À partir du {earliest}, première PTAX après le second tour : deux clôtures quotidiennes consécutives sous {entry}, avec un taux américain à deux ans inférieur ou égal à {us2y_max}. Les clôtures antérieures, y compris toute hausse du {first_monday}, ne comptent pas."),
        ("Abandon (avant l’entrée)", "Toute clôture de la PTAX au-dessus de {abandon}, plus haut que toutes les clôtures des quatre derniers mois (pic de {high4m} le {high4m_date}). L’idée est abandonnée, pas inversée."),
        ("Sortie (après l’entrée)", "Deux clôtures consécutives au-dessus de {exit} (le haut des 20 dernières clôtures), ou un taux américain à deux ans au-dessus de {us2y_exit}."),
        ("Réexamen", "Vers {review_low}–{review_high} (bas de la fourchette moins sa largeur), ou au plus tard le {review_by}. Une zone de réexamen, pas un objectif."),
    ],
    "trade_more": "Risques, ce qui changerait ma vue et le canal des matières premières",
    "trade_risks_label": "Principaux risques",
    "trade_risks": [
        "Le plan budgétaire du vainqueur est jugé négatif, quel qu’il soit.",
        "J’achète après le mouvement : une partie de la bonne nouvelle est peut-être déjà dans les prix, et les positions acheteuses sur le real étaient déjà élevées.",
        "Les taux américains continuent de monter et détournent les capitaux des marchés émergents, ou le pétrole chute avec la réouverture d’Ormuz, ce qui réduit les recettes d’exportation et laisse de la marge à des baisses plus rapides du Copom.",
    ],
    "trade_change_label": "Ce qui changerait ma vue",
    "trade_change": "Au-delà des déclencheurs ci-dessus : un signal du Copom en faveur de baisses plus rapides, un vainqueur sans plan budgétaire crédible ou une nette dégradation des chiffres budgétaires officiels.",
    "trade_channels_label": "Canaux des matières premières et de la géopolitique",
    "trade_channels": "Le Brésil exporte plus de pétrole qu’il n’en importe : des prix élevés aident ses comptes extérieurs. Ils entretiennent aussi le risque d’inflation, ce qui garde le Copom prudent et le coussin de taux large. Une réouverture du détroit d’Ormuz affaiblirait ces deux soutiens à la fois. Le minerai de fer et le soja ont peu de chances de décider cette fenêtre (voir plus bas).",
    "trade_math_label": "Le calcul : carry et volatilité",
    "trade_math": "Carry : ((1 + {selic}) ÷ (1 + {fed_mid}))^(1/12) − 1 ≈ {carry} par mois. Une position réelle le perçoit via les prix à terme, pas via la PTAX ; les niveaux de décision l’ignorent donc. Volatilité : écart-type quotidien de {vol_daily} sur les 20 dernières séances, multiplié par √15 séances jusqu’au second tour, soit {vol15} (environ {vol15_brl} sur la PTAX). Le niveau d’entrée est à {entry_sigma} σ sous la clôture de vendredi, le niveau d’abandon à {abandon_sigma} σ au-dessus, et un premier lundi typique a bougé de {event_sigma} σ : un gap d’ouverture peut sauter tous les niveaux.",

    "commodities_title": "Les prix des exportations brésiliennes : lesquels comptent maintenant ?",
    "commodities_intro": "Le Brésil gagne des dollars en exportant du pétrole, du minerai de fer, du soja et du sucre. Chaque série garde sa propre date et sa fréquence ; elles ne sont pas combinées en un indice.",
    "commodity_cols": ("Matière première", "Dernier", "Variation", "Compte pour les six prochaines semaines ?"),
    "commodity_names": {"brent": "Pétrole (Brent comptant)", "iron_ore": "Minerai de fer", "soybeans": "Soja", "sugar": "Sucre"},
    "commodity_verdicts": {
        "brent": ("Oui, dans les deux sens", "Soutient les recettes d’exportation et garde le Copom prudent ; une réouverture soudaine d’Ormuz supprimerait ces deux effets. Le prix au comptant reste au-dessus de 100 $, mais sous son pic de {brent_peak} de mi-septembre."),
        "iron_ore": ("Pas maintenant", "Le prix mensuel du FMI a reculé en juillet. Sans changement net de la demande chinoise d’acier, il a peu de chances de faire bouger le real en six semaines, même s’il compte directement pour Vale."),
        "soybeans": ("Limité", "Les prix ont monté en juillet, mais la saison d’exportation brésilienne culmine entre mars et juillet : moins de dollars du soja arrivent au quatrième trimestre."),
        "sugar": ("Limité", "Les usines peuvent orienter la canne vers le sucre ou l’éthanol ; un pétrole cher rend l’éthanol plus attractif, ce qui peut resserrer l’offre de sucre. Un sujet d’entreprise plus que de change."),
    },
    "vs": "vs",
    "units": {"USD per barrel": "USD/baril", "USD per metric ton": "USD/t", "US cents per pound": "cents US/lb"},
    "freq": {"daily": "quotidienne", "weekly": "hebdomadaire", "monthly": "mensuelle", "quarterly": "trimestrielle"},

    "equity_title": "Du prix d’une matière première à une entreprise",
    "equity_intro": "Un mouvement de prix n’est qu’un point de départ. Avant de parler d’investissement dans un producteur, je vérifierais quelle part du mouvement atteint le chiffre d’affaires, les marges, la trésorerie et la valorisation.",
    "equity_steps": [
        ("Exposition du chiffre d’affaires", "Que vend réellement l’entreprise, à quel prix réalisé, dans quelle devise, et quelle part est couverte ?"),
        ("Marges et courbe de coûts", "Un prix plus élevé devient-il du profit après l’énergie, le fret et le change ? Où se situe le producteur sur la courbe de coûts du secteur ?"),
        ("Bilan", "Sait-il bien utiliser sa trésorerie : endettement, investissements, dividendes et rachats d’actions ?"),
        ("Valorisation", "L’opportunité est-elle déjà dans le prix, avec des hypothèses normales et défavorables, et qu’est-ce qui prouverait que la thèse est fausse ?"),
    ],
    "equity_examples_label": "Par où je commencerais au Brésil",
    "equity_examples": "Petrobras (prix réalisé du pétrole et politique de prix des carburants politiquement sensible en année électorale) ; Vale (minerai de fer, Chine, fret) ; un producteur de sucre et d’éthanol (la flexibilité entre les deux). Des points de départ pour des questions, pas des recommandations.",

    "method_title": "Méthode, données et limites",
    "method_calc_label": "Comment les chiffres sont calculés",
    "method_calc": [
        ("Écart de taux", "Taux Selic moins le milieu de la fourchette de la Fed. Il compare des taux directeurs ; ce n’est pas un rendement d’investissement."),
        ("Carry", "((1 + Selic) ÷ (1 + milieu de la Fed))^(1/12) − 1, un ordre de grandeur mensuel qui ignore les coûts."),
        ("Niveaux de décision", "Tirés des 20 dernières clôtures de la PTAX à la date de la thèse ({range_low}–{range_high}), arrondis à deux décimales. La zone de réexamen est le bas de la fourchette moins sa largeur."),
        ("Marché contre économistes", "Chemin des économistes : une droite du Selic actuel jusqu’aux médianes Focus de fin d’année, moins 0,10 pt (l’écart habituel entre le taux au jour le jour CDI et le Selic), capitalisée et annualisée sur un et deux ans, puis comparée aux taux zéro-coupon à taux fixe de l’ANBIMA : un an {survey_1y} contre {br_1y} ; deux ans {survey_2y} contre {br_2y}."),
        ("Fraîcheur", "Les séries quotidiennes sont « en retard » après 4 jours et « périmées » après 7 ; l’enquête Focus hebdomadaire après 10 et 17 ; les prix mensuels du FMI après 100 et 130 jours à compter du début du mois concerné."),
        ("Arithmétique du second tour", "Un finaliste à la part s des suffrages exprimés a besoin de (50 − s) ÷ (part des autres candidats) des électeurs de ces candidats, à participation et votes blancs constants."),
        ("Erreur des sondages", "Écart du résultat (Flávio moins Lula, suffrages exprimés) moins l’écart de chaque sondage sur la même base. Datafolha et Quaest publient des versions en suffrages exprimés ; le dépouillement était achevé à {counted}."),
        ("Réactions aux premiers tours", "PTAX le premier jour ouvré après le vote par rapport à la dernière clôture précédente, pour 2014, 2018 et 2022 ; et la part de ce mouvement effacée le vendredi précédant le second tour."),
        ("Volatilité", "Écart-type des 20 derniers rendements logarithmiques quotidiens de la PTAX, multiplié par la racine de 15 séances ; les niveaux sont exprimés en multiples de cet écart-type."),
    ],
    "data_label": "État des données",
    "data_cols": ("Série", "Valeur", "Observée", "Fréquence", "Source", "État"),
    "series_names": {
        "selic_target": "Taux Selic", "fed_target_range": "Fourchette de la Fed", "brazil_us_policy_differential": "Écart Brésil–États-Unis",
        "ptax_usd_brl_midpoint": "PTAX USD/BRL", "us_2_year_treasury": "Taux US à 2 ans", "us_10_year_treasury": "Taux US à 10 ans",
        "focus_selic": "Focus Selic, fin {year}", "focus_ipca": "Focus inflation, {year}", "focus_fx": "Focus USD/BRL, fin {year}",
        "brent": "Brent comptant", "iron_ore": "Minerai de fer (FMI)", "soybeans": "Soja (FMI)", "sugar": "Sucre (FMI)",
    },
    "refresh_label": "Comment les données sont actualisées",
    "refresh_text": "Une tâche GitHub Actions tourne après la clôture brésilienne les jours ouvrés. Elle interroge chaque source officielle séparément, valide les données et enregistre un petit fichier que cette page lit. Les visiteurs ne déclenchent jamais de requête. Une source en échec garde sa dernière valeur valide, avec sa date d’origine, et l’échec est signalé. Une seconde étape marque la tâche en échec lorsque les chiffres clés ont plus d’une semaine.",
    "refresh_status": "Dernière tentative d’actualisation : {attempted} · {ok} sources sur {total} mises à jour.",
    "refresh_failed": "Non actualisées lors de la dernière tentative : {names}.",
    "refresh_history": "Jusqu’au 24 septembre 2026, cette tâche échouait sans alerte sur les données américaines et la page affichait encore les chiffres du 13 septembre. C’est corrigé : les sources sont désormais indépendantes, les données américaines ont des alternatives officielles et des données périmées font échouer la tâche.",
    "limits_label": "Limites",
    "limits": [
        "La PTAX est un taux de référence, pas un prix négociable ; coûts, écarts de cotation et taille de position ne sont pas modélisés.",
        "La courbe brésilienne (ANBIMA) est relevée à la main à la date de la thèse ; elle ne s’actualise pas.",
        "Les prix de marché datent du 2 octobre, avant le résultat, et le dépouillement était achevé à {counted} : les parts peuvent encore bouger.",
        "Focus est une enquête, pas un engagement ; l’écart entre marché et économistes mélange anticipations et prime de risque.",
        "Les scénarios de banques et les chiffres des options viennent d’articles sur l’étude de JPMorgan, pas de la note originale.",
        "Aucune probabilité n’est attribuée. Les règles ne sont pas testées sur l’historique et l’étude des premiers tours ne porte que sur trois élections.",
        "Des outils d’IA ont aidé à écrire le code, à rédiger les textes de recherche et à traduire. Les règles et le jugement final sont les miens, et chaque chiffre renvoie à sa source.",
    ],
    "sources_label": "Sources",
    "sources_note": "Les liens renvoient à la source officielle ou, pour le contexte politique et pétrolier, à l’article utilisé. Les dates indiquent à quel moment chaque observation s’applique.",
    "archive_label": "Thèse précédente",
    "archive": "La thèse complète du 24 septembre (vue, règles et données enregistrées) est conservée telle quelle dans le dépôt, dans research/thesis_2026-09-24.json ; l’étude du 13 septembre est dans research/data_snapshot.json.",

    "about_title": "À propos du projet",
    "about": "Je suis Romeo Mugnier de Almeida, étudiant en génie mécanique à l’EPFL, avec des racines brésiliennes et françaises. J’ai lancé ce projet pour comprendre comment les taux, la devise et les matières premières interagissent au Brésil, et je le tiens comme un carnet de recherche daté : chaque vue s’accompagne de règles écrites avant le résultat, et chaque ancienne vue est réexaminée, y compris ce que j’ai eu faux.",
    "about_build": "Construit avec Python et Streamlit. Données officielles de la Banque centrale du Brésil, du Trésor américain, de la Fed de New York et de FRED ; actualisation programmée avec validation par source ; tests automatisés pour les calculs, les traductions, les règles de fraîcheur et les PDF.",
    "links": {"code": "Code sur GitHub", "linkedin": "LinkedIn"},
    "footer": "Recherche pédagogique, pas un conseil en investissement. Aucune position réelle ni performance revendiquée. Thèse datée du {as_of} ; chaque chiffre affiche sa propre date.",

    "pdf_title": "Brésil macro : carry, élection et une opération conditionnelle",
    "pdf_subtitle": "Note de recherche · thèse datée du {as_of}",
    "pdf_page": "Page",
}

# ---------------------------------------------------------------------------
# Source names: a short tag next to each claim and a full, dated label in the
# source list.  Proper names (BCB, ANBIMA, Datafolha) stay as they are.
_SOURCE_SHORT = {
    "en": {"derived_gap": "calculated", "treasury": "U.S. Treasury", "nyfed": "New York Fed", "fred_iron": "IMF via FRED",
           "fred_soy": "IMF via FRED", "fred_sugar": "IMF via FRED", "ifi_ploa2027": "Senate IFI"},
    "pt": {"derived_gap": "cálculo próprio", "treasury": "Tesouro dos EUA", "nyfed": "Fed de Nova York", "fred_iron": "FMI via FRED",
           "fred_soy": "FMI via FRED", "fred_sugar": "FMI via FRED", "ifi_ploa2027": "IFI do Senado"},
    "fr": {"derived_gap": "calcul propre", "treasury": "Trésor américain", "nyfed": "Fed de New York", "fred_iron": "FMI via FRED",
           "fred_soy": "FMI via FRED", "fred_sugar": "FMI via FRED", "ifi_ploa2027": "IFI du Sénat"},
}
_SOURCE_COMMON = {
    "copom_281": "BCB", "copom_calendar": "BCB", "fomc_statement": "Federal Reserve",
    "fomc_sep": "Federal Reserve", "fomc_calendar": "Federal Reserve", "bcb_ptax": "BCB", "bcb_focus": "BCB",
    "anbima_ettj": "ANBIMA", "fred_brent": "EIA via FRED", "datafolha_1003": "Datafolha / G1", "quaest_1003": "Quaest / G1",
    "jpmorgan_infomoney": "JPMorgan / InfoMoney", "tse_results": "TSE",
}
_SOURCE_LABELS = {
    "en": {
        "copom_281": "BCB · Minutes of the 281st Copom meeting (decision of 16 Sep, published 22 Sep)",
        "copom_calendar": "BCB · 2026 Copom meeting calendar",
        "fomc_statement": "Federal Reserve · FOMC statement of 16 Sep 2026",
        "fomc_sep": "Federal Reserve · Summary of Economic Projections, 16 Sep 2026",
        "fomc_calendar": "Federal Reserve · FOMC meeting calendar",
        "derived_gap": "Calculated · Selic target minus the Fed target-range midpoint",
        "bcb_ptax": "BCB · PTAX exchange rates (open-data API)",
        "bcb_focus": "BCB · Focus market expectations (open-data API)",
        "treasury": "U.S. Treasury · Daily par yield curve rates",
        "nyfed": "New York Fed · Effective federal funds rate and target range",
        "anbima_ettj": "ANBIMA · Term structure of interest rates (ETTJ), 2 Oct 2026",
        "fred_brent": "EIA via FRED · Brent crude spot price (DCOILBRENTEU)",
        "fred_iron": "IMF via FRED · Global iron-ore price (PIORECRUSDM)",
        "fred_soy": "IMF via FRED · Global soybean price, monthly (PSOYBUSDM)",
        "fred_sugar": "IMF via FRED · Sugar No. 11 world price (PSUGAISAUSDM)",
        "datafolha_1003": "Datafolha poll, 3 Oct 2026, via G1",
        "quaest_1003": "Quaest poll, 2–3 Oct 2026, via G1",
        "tse_results": "TSE · First-round results, president",
        "jpmorgan_infomoney": "InfoMoney · JPMorgan dollar scenarios (28 Sep)",
        "ifi_ploa2027": "Senate Independent Fiscal Institution (IFI) · Assessment of the 2027 budget bill",
    },
    "pt": {
        "copom_281": "BCB · Ata da 281ª reunião do Copom (decisão de 16/9, publicada em 22/9)",
        "copom_calendar": "BCB · Calendário de reuniões do Copom em 2026",
        "fomc_statement": "Federal Reserve · Comunicado do FOMC de 16/9/2026",
        "fomc_sep": "Federal Reserve · Projeções econômicas (SEP), 16/9/2026",
        "fomc_calendar": "Federal Reserve · Calendário de reuniões do FOMC",
        "derived_gap": "Cálculo próprio · Meta Selic menos o ponto médio da faixa do Fed",
        "bcb_ptax": "BCB · Cotações PTAX (API de dados abertos)",
        "bcb_focus": "BCB · Expectativas de mercado Focus (API de dados abertos)",
        "treasury": "Tesouro dos EUA · Taxas diárias da curva par",
        "nyfed": "Fed de Nova York · Taxa efetiva dos fed funds e faixa-alvo",
        "anbima_ettj": "ANBIMA · Estrutura a termo das taxas de juros (ETTJ), 2/10/2026",
        "fred_brent": "EIA via FRED · Preço à vista do petróleo Brent (DCOILBRENTEU)",
        "fred_iron": "FMI via FRED · Preço global do minério de ferro (PIORECRUSDM)",
        "fred_soy": "FMI via FRED · Preço global da soja, mensal (PSOYBUSDM)",
        "fred_sugar": "FMI via FRED · Preço mundial do açúcar nº 11 (PSUGAISAUSDM)",
        "datafolha_1003": "Pesquisa Datafolha de 3/10/2026, via G1",
        "quaest_1003": "Pesquisa Quaest de 2–3/10/2026, via G1",
        "tse_results": "TSE · Resultado do 1º turno, presidente",
        "jpmorgan_infomoney": "InfoMoney · Cenários do JPMorgan para o dólar (28/9)",
        "ifi_ploa2027": "Instituição Fiscal Independente do Senado (IFI) · Análise do PLOA 2027",
    },
    "fr": {
        "copom_281": "BCB · Compte rendu de la 281e réunion du Copom (décision du 16 sept., publié le 22 sept.)",
        "copom_calendar": "BCB · Calendrier des réunions du Copom en 2026",
        "fomc_statement": "Federal Reserve · Communiqué du FOMC du 16 sept. 2026",
        "fomc_sep": "Federal Reserve · Projections économiques (SEP), 16 sept. 2026",
        "fomc_calendar": "Federal Reserve · Calendrier des réunions du FOMC",
        "derived_gap": "Calcul propre · Taux Selic moins le milieu de la fourchette de la Fed",
        "bcb_ptax": "BCB · Taux de change PTAX (API de données ouvertes)",
        "bcb_focus": "BCB · Anticipations de marché Focus (API de données ouvertes)",
        "treasury": "Trésor américain · Taux quotidiens de la courbe au pair",
        "nyfed": "Fed de New York · Taux effectif des fed funds et fourchette cible",
        "anbima_ettj": "ANBIMA · Structure par terme des taux d’intérêt (ETTJ), 2 oct. 2026",
        "fred_brent": "EIA via FRED · Prix au comptant du Brent (DCOILBRENTEU)",
        "fred_iron": "FMI via FRED · Prix mondial du minerai de fer (PIORECRUSDM)",
        "fred_soy": "FMI via FRED · Prix mondial du soja, mensuel (PSOYBUSDM)",
        "fred_sugar": "FMI via FRED · Prix mondial du sucre n° 11 (PSUGAISAUSDM)",
        "datafolha_1003": "Sondage Datafolha du 3 oct. 2026, via G1",
        "quaest_1003": "Sondage Quaest du 2–3 oct. 2026, via G1",
        "tse_results": "TSE · Résultats du 1er tour, présidentielle",
        "jpmorgan_infomoney": "InfoMoney · Scénarios JPMorgan sur le dollar (28 sept.)",
        "ifi_ploa2027": "Institution budgétaire indépendante du Sénat (IFI) · Analyse du projet de budget 2027",
    },
}
_PDF_EXTRA = {
    "en": {"pdf_data_label": "Key figures at the thesis date", "pdf_more": "The full evidence list, data status and calculations are on the website:"},
    "pt": {"pdf_data_label": "Números-chave na data da tese", "pdf_more": "A lista completa de evidências, a situação dos dados e os cálculos estão no site:"},
    "fr": {"pdf_data_label": "Chiffres clés à la date de la thèse", "pdf_more": "La liste complète des données, leur état et les calculs sont sur le site :"},
}
for _lang in TEXT:
    TEXT[_lang].update(_PDF_EXTRA[_lang])
    TEXT[_lang]["source_short"] = {**_SOURCE_COMMON, **_SOURCE_SHORT[_lang]}
    TEXT[_lang]["source_labels"] = _SOURCE_LABELS[_lang]


def _french_typography(value):
    """No-break (narrow) spaces before : ; ? ! % and inside « », so they never wrap."""

    if isinstance(value, str):
        for plain, spaced in ((" :", " :"), (" ;", " ;"), (" ?", " ?"), (" !", " !"),
                              (" %", " %"), ("« ", "« "), (" »", " »")):
            value = value.replace(plain, spaced)
        return value
    if isinstance(value, dict):
        return {key: _french_typography(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_french_typography(item) for item in value]
    if isinstance(value, tuple):
        return tuple(_french_typography(item) for item in value)
    return value


TEXT["fr"] = _french_typography(TEXT["fr"])
