"""Every visible sentence of the page and the PDF, in English, Portuguese and French.

Numbers never appear literally here: ``{placeholders}`` are filled from
``research/thesis.json`` (dated evidence and rules) and the refreshed snapshot,
so the three languages cannot disagree.  Portuguese always says
"commodities", never "matérias-primas".
"""
from __future__ import annotations

TEXT: dict[str, dict] = {}

# ---------------------------------------------------------------------------
# English
TEXT["en"] = {
    "html_lang": "en",
    "language_label": "Language",
    "skip": "Skip to the current view",
    "byline": "EPFL mechanical engineering · Brazilian and French",
    "kicker": "Brazil · interest rates · the real · commodities",
    "title": "Brazil macro, from policy to price.",
    "intro": "A student research log on how Brazilian and U.S. interest rates, the Brazilian real and Brazil’s main exports move together. Each view is dated, backed by linked official data and paired with the rules that would make me act or change my mind.",
    "nav": {"view": "Current view", "review": "Last call reviewed", "evidence": "Evidence", "paths": "Paths", "trade": "Paper trade", "commodities": "Commodities", "method": "Method & data"},
    "nav_label": "Sections",
    "view_label": "My current view",
    "status_no_position": "No position",
    "view_headline": "The real is being held up by its large interest-rate cushion. The next big move depends on the {first_round} election, which I can’t forecast, so I’m waiting for the market to show its hand.",
    "why_label": "Why",
    "why": [
        ("The cushion is still large.", "Even after Brazil cut to {selic} and the U.S. raised rates to {fed_range} on 16 September, Brazil’s policy rate is {gap} higher. Holding reais instead of dollars pays roughly {carry} more per month. Traders call this carry."),
        ("Investors are charging for risk.", "Brazil’s two-year market rate is {br_2y}, about {gap_2y} above the average implied by economists’ own rate forecasts ({survey_2y}). I read much of that gap as a premium for fiscal and political uncertainty."),
        ("The election is too close to call.", "Datafolha has Lula at {lula}% and Flávio Bolsonaro at {flavio}% for the first round (margin ±{moe}). The 2027 budget is disputed: the government projects a {fiscal_gov} surplus, the Senate’s fiscal watchdog a {fiscal_ifi} deficit."),
    ],
    "act_label": "What would make me act",
    "act": "After the first round: two daily PTAX closes below {entry} while the U.S. two-year yield stays at or below {us2y_max}. I would read that as investors seeing less fiscal risk, and paper-buy the real.",
    "change_label": "What would change my mind",
    "change": "A PTAX close above {abandon} before any entry, Brazil’s two-year rate above {br2y_max}, or the U.S. two-year yield above {us2y_exit}. Each would mean risk is rising, not falling.",
    "monitor_label": "Rule check",
    "monitor_note": "Automatic comparison of the saved PTAX data with the rules above. A mechanical check, not a live position.",
    "monitor": {
        "waiting": "Waiting for the first round. Latest PTAX {latest} ({latest_date}); no entry is possible before {earliest}.",
        "watching": "Watching. Latest PTAX {latest} ({latest_date}); entry needs two closes below {entry}.",
        "entered": "Entry conditions met on {date} at {value} (paper). Latest PTAX {latest} ({latest_date}).",
        "review": "Paper position reached the review zone on {date} ({value}). Reassess before doing anything else.",
        "exited": "Paper position closed by the exit rule on {date} at {value}.",
        "abandoned": "Idea abandoned: PTAX closed at {value} on {date}, above {abandon}.",
        "expired": "The review date ({review_by}) has passed without an entry. This thesis is due for an update.",
        "unavailable": "Rule check unavailable: the saved PTAX history could not be read.",
    },
    "tape_label": "Latest official data",
    "tape": {
        "selic_target": "Selic target",
        "fed_target_range": "Fed target range",
        "brazil_us_policy_differential": "Brazil–U.S. rate gap",
        "ptax_usd_brl_midpoint": "USD/BRL (PTAX)",
        "us_2_year_treasury": "U.S. 2-year yield",
        "brent": "Brent crude (spot)",
    },
    "fresh": {"fresh": "Up to date", "delayed": "Delayed", "stale": "Stale", "unknown": "Date unknown"},
    "stale_banner": "Some figures are older than usual (marked below). The page shows each value with its own date instead of hiding it.",
    "refresh_banner": "The automatic refresh has not run since {date}. Figures below are shown with their original dates.",
    "unavailable": "Unavailable",
    "na": "n/a",
    "download": "Download the research brief (PDF, English)",
    "download_help": "4 pages, the same dated thesis as this page, generated from the saved files",

    # Review of the previous thesis
    "review_title": "What happened to my 13 September thesis",
    "review_intro": "On 13 September I expected both central banks to deliver what markets priced, and planned to buy dollars only if USD/BRL broke above {prev_trigger}. No position was ever opened, so there is no performance to report, only reasoning to check.",
    "review_head": ("What I expected", "What happened", "Verdict"),
    "review_rows": {
        "decisions": ("Copom cuts 0.25 pp; the Fed raises 0.25 pp.", "Both on 16 September: Selic {selic_prev} → {selic}; Fed {fed_prev_range} → {fed_range}, unanimously."),
        "gap": ("Brazil’s rate lead narrows by about 0.50 pp.", "{gap_prev} → {gap}."),
        "us_yields": ("Higher U.S. yields push the dollar up.", "U.S. two-year {us2y_prev} → {us2y}; USD/BRL {ptax_prev} → {ptax} ({ptax_chg}). Right direction, small move."),
        "oil": ("Oil above $100 supports the real.", "Brent spot peaked at {brent_peak} on {brent_peak_date}, yet the real weakened. Oil may have cushioned the move; the data cannot separate it from U.S. rates and politics."),
        "trigger": ("Act only above {prev_trigger}; drop the idea below {prev_abandon}.", "Highest close {ptax_high} ({ptax_high_date}); lowest {ptax_low} ({ptax_low_date}). Neither level was reached."),
        "election": ("Election news listed as a secondary risk.", "By late September, daily market reporting cited polls alongside U.S. yields as a main driver of the real."),
    },
    "verdicts": {"confirmed": "Confirmed", "partly": "Partly", "unresolved": "Unresolved", "not_triggered": "Not triggered", "underweighted": "Underweighted"},
    "review_lesson_label": "What I changed",
    "review_lesson": "The size of the rate cushion mattered more than its 0.50-point change, and I treated the election as a footnote when it is the main event. The new thesis starts from those two corrections.",

    # Evidence
    "evidence_title": "The evidence, sorted by type",
    "evidence_intro": "Each item is labelled so facts, prices, forecasts and my own reading stay separate. Values are frozen at the thesis date ({as_of}); the refreshed figures are at the top of the page.",
    "kinds": {"fact": "Fact", "pricing": "Market pricing", "survey": "Survey & projections", "interpretation": "My interpretation"},
    "kind_help": {
        "fact": "Something that happened.",
        "pricing": "What prices imply today.",
        "survey": "What forecasters and officials expect.",
        "interpretation": "My reading, which can be wrong.",
    },
    "evidence": {
        "fact": [
            "The Copom cut the Selic by 0.25 pp to {selic} on 16 September, unanimously (its {cuts_count}th cut in a row and {cuts_total} since March). It gave no guidance on the next step, said inflation risks are tilted upward and projects {copom_proj} inflation in early 2028, still above the {target} target.",
            "The Fed raised its target range by 0.25 pp to {fed_range} on 16 September (12–0), saying inflation “remains elevated”.",
            "The gap between the two policy rates fell from {gap_prev} to {gap}.",
            "Brazil votes on {first_round}; a runoff, if needed, is on {runoff}. Datafolha (15–17 Sep): Lula {lula}%, Flávio Bolsonaro {flavio}% in the first round; {runoff_lula}% vs {runoff_flavio}% in a runoff (±{moe}).",
            "For 2027 the government’s budget bill projects a {fiscal_gov} primary surplus; the Senate’s Independent Fiscal Institution projects a {fiscal_ifi} deficit.",
        ],
        "pricing": [
            "USD/BRL (PTAX) was {ptax} on {ptax_date}, {ptax_chg} since 11 September but still inside its four-month range ({low4m}–{high4m}).",
            "The U.S. two-year Treasury yield rose from {us2y_prev} (10 Sep) to {us2y}; the ten-year is {us10y}.",
            "Brazil’s fixed-rate curve (ANBIMA, 23 Sep): one year {br_1y}, two years {br_2y}. Inflation implied by the curve over two years: {be_2y}.",
            "Brent: the EIA spot price was {brent} on {brent_date} after peaking at {brent_peak} on {brent_peak_date} (it was {brent_july} in late July). The November futures contract usually quoted in the news closed at {brent_fut} on {brent_fut_date}.",
        ],
        "survey": [
            "Focus survey medians ({focus_date}): Selic {focus_selic26} at end-2026, {focus_selic27} at end-2027; inflation {focus_ipca26} in 2026, {focus_ipca27} in 2027; USD/BRL {focus_fx26} at end-2026.",
            "Fed officials’ median projection: {fed_proj_2026} at end-2026 (one more 0.25 pp rise), up from {fed_proj_june} in June.",
            "The EIA (9 Sep) expected Brent to average about {eia_2h} in the second half of 2026, before the 11 September attack on Saudi Arabia’s East–West pipeline.",
        ],
        "interpretation": [
            "If policy follows the economists’ path, the average overnight rate over the next two years would be about {survey_2y}; the market’s two-year rate is {br_2y}. The {gap_2y} difference is either a view that the Copom will cut less, or a premium for risk. I read most of it as risk premium because implied inflation ({be_2y}) sits far above forecasts ({focus_ipca27} for 2027), but the data cannot prove that split.",
            "The wide gap between spot and futures oil prices says physical supply is scarce now but the market expects it to ease. Oil’s support for the real may therefore be temporary.",
            "A 0.50-point narrowing of a {gap_round}-point gap barely changes the incentive to hold reais; a change in the risk premium can move the currency much more.",
        ],
    },
    "focus_table_caption": "Focus survey medians, {focus_date}",
    "focus_rows": ("Selic, end of year", "Inflation (IPCA)", "USD/BRL, end of year"),
    "chart_title": "USD/BRL (PTAX): last {n} sessions and my decision levels",
    "chart_desc": "Daily PTAX closes from {start} to {end}. Latest {latest}. Levels: entry below {entry}, exit above {exit}, drop the idea above {abandon}; dotted: September’s unused trigger at {prev_trigger}.",
    "chart_labels": {"entry": "Entry < {entry}", "exit": "Exit > {exit}", "abandon": "Drop > {abandon}", "prev": "Sep trigger {prev_trigger}", "event": "16 Sep decisions"},
    "chart_table": "Show the chart data as a table",
    "chart_cols": ("Date", "PTAX"),

    # Paths
    "paths_title": "What could happen after {first_round}",
    "paths_intro": "Three paths I can recognise in the data, plus one outside shock. I don’t attach probabilities: the point is to decide in advance what each would mean and what I would do.",
    "path_fields": ("Signals", "What it would mean", "What I would do"),
    "paths": [
        ("Risk premium falls", "PTAX closes below {entry} twice; Brazil’s two-year rate falls a quarter point or more from {br_2y}; implied inflation eases.", "Investors see less fiscal risk, and the carry cushion keeps attracting money.", "Paper-buy the real if the U.S. two-year yield is at or below {us2y_max}."),
        ("No verdict until the runoff", "PTAX stays between {entry} and {abandon}; polls remain tight.", "The market waits for {runoff}.", "No position. Reassess after the runoff and the {copom_next} Copom decision."),
        ("Risk premium rises", "PTAX closes above {abandon}; the two-year rate moves above {br2y_max}; implied inflation rises.", "Fiscal worries dominate. A weaker real plus expensive oil could make the Copom pause its cuts.", "Drop the long-real idea. A dollar trade would need new rules; I would not recycle September’s."),
        ("Outside shock: U.S. rates", "The U.S. two-year yield rises above {us2y_exit}, or the ten-year jumps further.", "Emerging-market currencies tend to weaken together, whatever Brazil’s election says.", "No long-real position; exit if already in one."),
    ],
    "calendar_label": "Dates that matter",
    "calendar": {"election_first": "Brazil election, first round", "election_runoff": "Runoff, if needed", "fomc": "Fed decision", "copom": "Copom decision", "both": "Fed and Copom decisions"},

    # Paper trade
    "trade_title": "The paper trade: buy the real only if the market confirms",
    "trade_status": "Inactive, no position · earliest entry {earliest}",
    "trade_rows": [
        ("Expression", "Long the Brazilian real against the U.S. dollar (short USD/BRL), tracked with the official PTAX rate. Paper only: no money, no execution."),
        ("Thesis", "If the election lowers the fiscal risk premium, the real should strengthen and stay stronger, because investors keep collecting a large interest-rate cushion while they wait."),
        ("Why it may not be priced", "The two-year rate sits {gap_2y} above the economists’ own path, and economists expect USD/BRL at {focus_fx26} at year-end. A durably stronger real is not the consensus, and the premium could compress quickly if uncertainty clears."),
        ("Catalysts", "First round {first_round}; possible runoff {runoff}; Fed {fomc_next}; Copom {copom_next}."),
        ("Entry", "From {earliest}: two consecutive daily PTAX closes below {entry}, with the U.S. two-year yield at or below {us2y_max}. {entry} is near the bottom of the last 20 closes ({range_low}–{range_high})."),
        ("Drop the idea (before entry)", "Any PTAX close above {abandon}, higher than every close of the past four months (peak {high4m} on {high4m_date}). The idea is dropped, not reversed."),
        ("Exit (after entry)", "Two consecutive closes above {exit} (the top of the recent range and the economists’ year-end median), or the U.S. two-year yield above {us2y_exit}."),
        ("Review", "Around {review_low}–{review_high} (range low minus range width), or on {review_by} at the latest. A review zone, not a target."),
    ],
    "trade_more": "Risks, what would change my view, and the commodity channel",
    "trade_risks_label": "Main risks",
    "trade_risks": [
        "The election result is read as fiscally negative, whoever wins.",
        "U.S. yields keep rising and pull money out of emerging markets.",
        "Oil falls sharply as Hormuz reopens: less export income for Brazil and room for faster Copom cuts, which would shrink the cushion.",
        "PTAX is a daily reference rate, not a price I could trade. Costs, spreads and position size are not modelled.",
    ],
    "trade_change_label": "Evidence that would change my view",
    "trade_change": "Brazil’s two-year rate above {br2y_max} (checked by hand on ANBIMA), a Copom signal of faster cuts, a sharp deterioration in official fiscal numbers, or the U.S. two-year yield above {us2y_exit}.",
    "trade_channels_label": "Commodity and geopolitical channels",
    "trade_channels": "Brazil exports more oil than it imports, so high prices help its external accounts. They also keep inflation risk alive, which keeps the Copom cautious and the cushion wide. A reopening of the Strait of Hormuz would weaken both supports at once. Iron ore and soybeans are unlikely to decide this six-week window (see below).",
    "trade_math_label": "The carry arithmetic",
    "trade_math": "((1 + {selic}) ÷ (1 + {fed_mid}))^(1/12) − 1 ≈ {carry} per month. A real position earns this through forward prices, not through PTAX, so the decision levels above ignore it.",

    # Commodities
    "commodities_title": "Brazil’s export prices: which ones matter now?",
    "commodities_intro": "Brazil earns dollars by exporting oil, iron ore, soybeans and sugar. Each series keeps its own date and frequency; they are not combined into one index.",
    "commodity_cols": ("Commodity", "Latest", "Change", "Matters for the next six weeks?"),
    "commodity_names": {"brent": "Oil (Brent spot)", "iron_ore": "Iron ore", "soybeans": "Soybeans", "sugar": "Sugar"},
    "commodity_verdicts": {
        "brent": ("Yes, both ways", "Supports export income and keeps the Copom cautious; a sudden reopening of Hormuz would remove both effects. The spot price is well above the futures price quoted in the news."),
        "iron_ore": ("Not now", "The monthly IMF price slipped in July. Without a clear change in Chinese steel demand it is unlikely to move the real within six weeks, though it matters directly for Vale."),
        "soybeans": ("Limited", "Prices rose in July, but Brazil’s export season peaks between March and July, so fewer soy dollars arrive in the fourth quarter."),
        "sugar": ("Limited", "Mills can switch cane between sugar and ethanol; expensive oil makes ethanol more attractive, which can tighten sugar supply. More a company story than a currency one."),
    },
    "vs": "vs",
    "units": {"USD per barrel": "USD/bbl", "USD per metric ton": "USD/t", "US cents per pound": "US¢/lb"},
    "freq": {"daily": "daily", "weekly": "weekly", "monthly": "monthly", "quarterly": "quarterly"},

    # Equity bridge
    "equity_title": "From a commodity price to a company",
    "equity_intro": "A price move is only a starting point. Before calling a producer an investment, I would test how much of the move reaches revenue, margins, cash and valuation.",
    "equity_steps": [
        ("Revenue exposure", "What does the company actually sell, at what realised price, in which currency, and how much is hedged?"),
        ("Margins and cost curve", "Does a higher price become profit, after energy, freight and currency effects? Where does the producer sit on the industry cost curve?"),
        ("Balance sheet", "Can it use the cash well: leverage, capital spending, dividends and buybacks?"),
        ("Valuation", "Is the opportunity already in the price under normal and bad assumptions, and what would prove the thesis wrong?"),
    ],
    "equity_examples_label": "Where I would start in Brazil",
    "equity_examples": "Petrobras (oil price realisation, and a domestic fuel-pricing policy that is politically sensitive in an election year); Vale (iron ore, China, freight); a sugar-and-ethanol producer (the flexibility to shift between the two). Starting points for questions, not recommendations.",

    # Method & data
    "method_title": "Method, data and limits",
    "method_calc_label": "How the numbers are calculated",
    "method_calc": [
        ("Rate gap", "Selic target minus the midpoint of the Fed’s target range. It compares policy rates; it is not an investment return."),
        ("Carry", "((1 + Selic) ÷ (1 + Fed midpoint))^(1/12) − 1, a rough monthly figure that ignores costs."),
        ("Decision levels", "Taken from the last 20 PTAX closes when the thesis was written ({range_low}–{range_high}), rounded to two decimals. The review zone is the range low minus the range width."),
        ("Market vs. economists", "Economists’ path: a straight line from today’s Selic through the Focus year-end medians, minus 0.10 pp (the usual gap between the overnight CDI rate and the Selic), compounded and annualised over one and two years, then compared with ANBIMA’s fixed-rate zero-coupon yields: one year {survey_1y} vs {br_1y}, two years {survey_2y} vs {br_2y}."),
        ("Freshness", "Daily series are “delayed” after 4 days and “stale” after 7; the weekly Focus survey after 10 and 17; monthly IMF prices after 100 and 130 days from the start of the month they describe."),
    ],
    "data_label": "Data status",
    "data_cols": ("Series", "Value", "Observed", "Frequency", "Source", "Status"),
    "series_names": {
        "selic_target": "Selic target", "fed_target_range": "Fed target range", "brazil_us_policy_differential": "Brazil–U.S. rate gap",
        "ptax_usd_brl_midpoint": "USD/BRL PTAX", "us_2_year_treasury": "U.S. 2-year yield", "us_10_year_treasury": "U.S. 10-year yield",
        "focus_selic": "Focus Selic, end-{year}", "focus_ipca": "Focus inflation, {year}", "focus_fx": "Focus USD/BRL, end-{year}",
        "brent": "Brent spot", "iron_ore": "Iron ore (IMF)", "soybeans": "Soybeans (IMF)", "sugar": "Sugar (IMF)",
    },
    "refresh_label": "How the data is refreshed",
    "refresh_text": "A GitHub Actions job runs after the Brazilian close on weekdays. It fetches each official source separately, validates it and saves a small file that this page reads. Visitors never trigger a data request. A failed source keeps its last good value, with its original date, and the failure is reported. A second step marks the run as failed when key figures are more than a week old.",
    "refresh_status": "Last refresh attempt: {attempted} · {ok} of {total} sources updated.",
    "refresh_failed": "Not refreshed in the last attempt: {names}.",
    "refresh_history": "Until 24 September 2026 this job failed silently on U.S. data and the page kept showing 13 September figures. That has been fixed: sources are now independent, U.S. data has official fallbacks, and stale data turns the job red.",
    "limits_label": "Limits",
    "limits": [
        "PTAX is the central bank’s daily reference rate, not a price anyone can trade at.",
        "Brazil’s curve (ANBIMA) and oil futures are dated observations collected by hand for this thesis; they do not refresh.",
        "Focus is a survey, not a policy commitment. The market-vs-economists gap mixes expectations and risk premium.",
        "Commodity series have different frequencies and publication lags and are never combined.",
        "No probabilities are assigned to paths; none of the rules has been tested on history.",
        "AI tools helped write code, draft research text and translate. The rules and the final judgement are mine, and every figure links to its source.",
    ],
    "sources_label": "Sources",
    "sources_note": "Links point to the official source or, for political and oil-market context, to the reporting used. Dates show when each observation applies.",
    "archive_label": "Previous thesis",
    "archive": "The full 13 September case (scenarios, rules and saved pricing) is preserved unchanged in the repository as research/data_snapshot.json.",

    # About
    "about_title": "About this project",
    "about": "I’m Romeo Mugnier de Almeida, a mechanical engineering student at EPFL with Brazilian and French roots. I started this project to understand how Brazil’s rates, currency and commodities interact, and I keep it as a dated research log: every view comes with rules written before the outcome, and every old view gets reviewed, including the parts I got wrong.",
    "about_build": "Built with Python and Streamlit. Official data from the Banco Central do Brasil, the U.S. Treasury, the New York Fed and FRED; a scheduled refresh with per-source validation; automated tests for the calculations, translations, freshness rules and PDFs.",
    "links": {"code": "Code on GitHub", "linkedin": "LinkedIn"},
    "footer": "Educational research, not investment advice. No real positions and no claimed performance. Thesis dated {as_of}; each figure shows its own date.",

    # PDF-only strings
    "pdf_title": "Brazil macro: carry, the election and one conditional trade",
    "pdf_subtitle": "Research brief · thesis dated {as_of}",
    "pdf_page": "Page",
}

# ---------------------------------------------------------------------------
# Portuguese (Brazil)
TEXT["pt"] = {
    "html_lang": "pt-BR",
    "language_label": "Idioma",
    "skip": "Ir para a visão atual",
    "byline": "Engenharia mecânica na EPFL · brasileiro e francês",
    "kicker": "Brasil · juros · real · commodities",
    "title": "Brasil macro: da política monetária aos preços.",
    "intro": "Um diário de pesquisa de estudante sobre como os juros do Brasil e dos EUA, o real e as principais exportações brasileiras se movem juntos. Cada visão tem data, se apoia em dados oficiais com link e vem com as regras que me fariam agir ou mudar de ideia.",
    "nav": {"view": "Visão atual", "review": "Revisão da última tese", "evidence": "Evidências", "paths": "Caminhos", "trade": "Operação simulada", "commodities": "Commodities", "method": "Método e dados"},
    "nav_label": "Seções",
    "view_label": "Minha visão atual",
    "status_no_position": "Sem posição",
    "view_headline": "O real está sustentado pelo grande colchão de juros. O próximo grande movimento depende da eleição de {first_round}, que não consigo prever; por isso espero o mercado mostrar a direção.",
    "why_label": "Por quê",
    "why": [
        ("O colchão ainda é grande.", "Mesmo depois de o Brasil cortar para {selic} e de os EUA subirem para {fed_range} em 16 de setembro, o juro básico brasileiro está {gap} acima. Manter reais em vez de dólares rende cerca de {carry} a mais por mês. É o chamado carry."),
        ("Os investidores cobram pelo risco.", "O juro de mercado de dois anos no Brasil está em {br_2y}, cerca de {gap_2y} acima da média implícita nas próprias projeções dos economistas ({survey_2y}). Leio boa parte dessa diferença como prêmio pela incerteza fiscal e política."),
        ("A eleição está indefinida.", "O Datafolha mostra Lula com {lula}% e Flávio Bolsonaro com {flavio}% no primeiro turno (margem de ±{moe}). O Orçamento de 2027 é contestado: o governo projeta superávit de {fiscal_gov}; a IFI do Senado, déficit de {fiscal_ifi}."),
    ],
    "act_label": "O que me faria agir",
    "act": "Depois do primeiro turno: dois fechamentos diários da PTAX abaixo de {entry}, com o juro americano de dois anos em até {us2y_max}. Eu leria isso como menor percepção de risco fiscal e compraria reais na operação simulada.",
    "change_label": "O que me faria mudar de ideia",
    "change": "Uma PTAX acima de {abandon} antes de qualquer entrada, o juro brasileiro de dois anos acima de {br2y_max} ou o juro americano de dois anos acima de {us2y_exit}. Qualquer um desses sinais indicaria risco em alta, não em queda.",
    "monitor_label": "Verificação das regras",
    "monitor_note": "Comparação automática dos dados salvos da PTAX com as regras acima. Uma verificação mecânica, não uma posição real.",
    "monitor": {
        "waiting": "Aguardando o primeiro turno. Última PTAX {latest} ({latest_date}); nenhuma entrada é possível antes de {earliest}.",
        "watching": "Em observação. Última PTAX {latest} ({latest_date}); a entrada exige dois fechamentos abaixo de {entry}.",
        "entered": "Condições de entrada atendidas em {date}, a {value} (simulado). Última PTAX {latest} ({latest_date}).",
        "review": "A posição simulada chegou à zona de reavaliação em {date} ({value}). Reavaliar antes de qualquer outra decisão.",
        "exited": "Posição simulada encerrada pela regra de saída em {date}, a {value}.",
        "abandoned": "Ideia abandonada: a PTAX fechou a {value} em {date}, acima de {abandon}.",
        "expired": "A data de revisão ({review_by}) passou sem entrada. Esta tese precisa ser atualizada.",
        "unavailable": "Verificação indisponível: o histórico salvo da PTAX não pôde ser lido.",
    },
    "tape_label": "Dados oficiais mais recentes",
    "tape": {
        "selic_target": "Meta Selic",
        "fed_target_range": "Juro do Fed (faixa)",
        "brazil_us_policy_differential": "Diferencial Brasil–EUA",
        "ptax_usd_brl_midpoint": "USD/BRL (PTAX)",
        "us_2_year_treasury": "Juro dos EUA, 2 anos",
        "brent": "Petróleo Brent (à vista)",
    },
    "fresh": {"fresh": "Atualizado", "delayed": "Atrasado", "stale": "Desatualizado", "unknown": "Data desconhecida"},
    "stale_banner": "Alguns números estão mais antigos que o normal (marcados abaixo). A página mostra cada valor com a sua data em vez de escondê-lo.",
    "refresh_banner": "A atualização automática não roda desde {date}. Os números abaixo aparecem com as datas originais.",
    "unavailable": "Indisponível",
    "na": "n/d",
    "download": "Baixar o relatório (PDF, português)",
    "download_help": "4 páginas, a mesma tese datada desta página, gerado a partir dos arquivos salvos",

    "review_title": "O que aconteceu com a minha tese de 13 de setembro",
    "review_intro": "Em 13 de setembro eu esperava que os dois bancos centrais fizessem o que o mercado precificava, e só compraria dólares se o USD/BRL rompesse {prev_trigger}. Nenhuma posição chegou a ser aberta; portanto, não há desempenho a relatar, só raciocínio a conferir.",
    "review_head": ("O que eu esperava", "O que aconteceu", "Veredito"),
    "review_rows": {
        "decisions": ("Copom corta 0,25 p.p.; o Fed sobe 0,25 p.p.", "Ambos em 16 de setembro: Selic {selic_prev} → {selic}; Fed {fed_prev_range} → {fed_range}, por unanimidade."),
        "gap": ("O diferencial de juros cai cerca de 0,50 p.p.", "{gap_prev} → {gap}."),
        "us_yields": ("Juros americanos mais altos fortalecem o dólar.", "Juro de dois anos dos EUA {us2y_prev} → {us2y}; USD/BRL {ptax_prev} → {ptax} ({ptax_chg}). Direção certa, movimento pequeno."),
        "oil": ("Petróleo acima de US$ 100 apoia o real.", "O Brent à vista chegou a {brent_peak} em {brent_peak_date} e, ainda assim, o real se desvalorizou. O petróleo pode ter amortecido o movimento; os dados não permitem separá-lo dos juros americanos e da política."),
        "trigger": ("Agir só acima de {prev_trigger}; abandonar abaixo de {prev_abandon}.", "Maior fechamento {ptax_high} ({ptax_high_date}); menor {ptax_low} ({ptax_low_date}). Nenhum dos níveis foi atingido."),
        "election": ("Notícias eleitorais tratadas como risco secundário.", "No fim de setembro, o noticiário diário de mercado citava as pesquisas, ao lado dos juros americanos, como um dos principais fatores para o real."),
    },
    "verdicts": {"confirmed": "Confirmado", "partly": "Em parte", "unresolved": "Em aberto", "not_triggered": "Não acionado", "underweighted": "Subestimado"},
    "review_lesson_label": "O que eu mudei",
    "review_lesson": "O tamanho do colchão de juros importou mais do que a sua redução de 0,50 ponto, e tratei a eleição como nota de rodapé quando ela é o evento principal. A nova tese parte dessas duas correções.",

    "evidence_title": "As evidências, separadas por tipo",
    "evidence_intro": "Cada item tem um rótulo para separar fatos, preços, projeções e a minha leitura. Os valores estão congelados na data da tese ({as_of}); os números atualizados estão no topo da página.",
    "kinds": {"fact": "Fato", "pricing": "Preço de mercado", "survey": "Pesquisas e projeções", "interpretation": "Minha interpretação"},
    "kind_help": {
        "fact": "Algo que aconteceu.",
        "pricing": "O que os preços indicam hoje.",
        "survey": "O que analistas e autoridades esperam.",
        "interpretation": "A minha leitura, que pode estar errada.",
    },
    "evidence": {
        "fact": [
            "O Copom cortou a Selic em 0,25 p.p., para {selic}, em 16 de setembro, por unanimidade (o {cuts_count}º corte seguido e {cuts_total} desde março). Não sinalizou o próximo passo, disse que os riscos para a inflação são assimétricos para cima e projeta inflação de {copom_proj} no início de 2028, ainda acima da meta de {target}.",
            "O Fed subiu sua faixa de juros em 0,25 p.p., para {fed_range}, em 16 de setembro (12 a 0), afirmando que a inflação “continua elevada”.",
            "O diferencial entre os dois juros básicos caiu de {gap_prev} para {gap}.",
            "O Brasil vota em {first_round}; um eventual segundo turno será em {runoff}. Datafolha (15 a 17/9): Lula {lula}%, Flávio Bolsonaro {flavio}% no primeiro turno; {runoff_lula}% contra {runoff_flavio}% no segundo (±{moe}).",
            "Para 2027, o projeto de Orçamento do governo prevê superávit primário de {fiscal_gov}; a Instituição Fiscal Independente do Senado projeta déficit de {fiscal_ifi}.",
        ],
        "pricing": [
            "O USD/BRL (PTAX) estava em {ptax} em {ptax_date}, {ptax_chg} desde 11 de setembro, mas ainda dentro da faixa dos últimos quatro meses ({low4m}–{high4m}).",
            "O juro do Tesouro americano de dois anos subiu de {us2y_prev} (10/9) para {us2y}; o de dez anos está em {us10y}.",
            "Curva prefixada brasileira (ANBIMA, 23/9): um ano {br_1y}, dois anos {br_2y}. Inflação implícita na curva em dois anos: {be_2y}.",
            "Brent: o preço à vista da EIA estava em {brent} em {brent_date}, depois de atingir {brent_peak} em {brent_peak_date} (era {brent_july} no fim de julho). O contrato futuro de novembro, o mais citado no noticiário, fechou a {brent_fut} em {brent_fut_date}.",
        ],
        "survey": [
            "Medianas da pesquisa Focus ({focus_date}): Selic de {focus_selic26} no fim de 2026 e {focus_selic27} no fim de 2027; inflação de {focus_ipca26} em 2026 e {focus_ipca27} em 2027; USD/BRL a {focus_fx26} no fim de 2026.",
            "Projeção mediana dos dirigentes do Fed: {fed_proj_2026} no fim de 2026 (mais uma alta de 0,25 p.p.), acima dos {fed_proj_june} de junho.",
            "A EIA (9/9) esperava Brent médio de cerca de {eia_2h} no segundo semestre de 2026, antes do ataque de 11 de setembro ao oleoduto Leste–Oeste da Arábia Saudita.",
        ],
        "interpretation": [
            "Se os juros seguirem o caminho dos economistas, a taxa média de um dia nos próximos dois anos seria de cerca de {survey_2y}; o juro de mercado de dois anos está em {br_2y}. A diferença de {gap_2y} indica que o mercado espera menos cortes do Copom ou cobra um prêmio de risco. Leio a maior parte como prêmio de risco, porque a inflação implícita ({be_2y}) está muito acima das projeções ({focus_ipca27} para 2027), mas os dados não comprovam essa divisão.",
            "A grande diferença entre o petróleo à vista e o futuro indica escassez física agora, mas expectativa de normalização. O apoio do petróleo ao real pode, portanto, ser temporário.",
            "Uma queda de 0,50 ponto num diferencial de {gap_round} pontos quase não muda o incentivo para manter reais; uma mudança no prêmio de risco pode mover o câmbio muito mais.",
        ],
    },
    "focus_table_caption": "Medianas da pesquisa Focus, {focus_date}",
    "focus_rows": ("Selic, fim do ano", "Inflação (IPCA)", "USD/BRL, fim do ano"),
    "chart_title": "USD/BRL (PTAX): últimos {n} pregões e meus níveis de decisão",
    "chart_desc": "Fechamentos diários da PTAX de {start} a {end}. Último {latest}. Níveis: entrada abaixo de {entry}, saída acima de {exit}, abandono acima de {abandon}; pontilhado: o gatilho não usado de setembro, {prev_trigger}.",
    "chart_labels": {"entry": "Entrada < {entry}", "exit": "Saída > {exit}", "abandon": "Abandono > {abandon}", "prev": "Gatilho de set. {prev_trigger}", "event": "Decisões de 16/9"},
    "chart_table": "Ver os dados do gráfico em tabela",
    "chart_cols": ("Data", "PTAX"),

    "paths_title": "O que pode acontecer depois de {first_round}",
    "paths_intro": "Três caminhos que consigo reconhecer nos dados, mais um choque externo. Não atribuo probabilidades: o objetivo é decidir antes o que cada um significaria e o que eu faria.",
    "path_fields": ("Sinais", "O que significaria", "O que eu faria"),
    "paths": [
        ("O prêmio de risco cai", "Dois fechamentos da PTAX abaixo de {entry}; o juro de dois anos cai 0,25 ponto ou mais a partir de {br_2y}; a inflação implícita recua.", "Os investidores veem menos risco fiscal e o colchão de juros continua atraindo recursos.", "Comprar reais na operação simulada se o juro americano de dois anos estiver em até {us2y_max}."),
        ("Sem veredito até o segundo turno", "A PTAX fica entre {entry} e {abandon}; as pesquisas seguem apertadas.", "O mercado espera {runoff}.", "Sem posição. Reavaliar depois do segundo turno e da decisão do Copom de {copom_next}."),
        ("O prêmio de risco sobe", "A PTAX fecha acima de {abandon}; o juro de dois anos passa de {br2y_max}; a inflação implícita sobe.", "As preocupações fiscais dominam. Um real mais fraco com petróleo caro pode levar o Copom a pausar os cortes.", "Abandonar a ideia de comprar reais. Uma operação comprada em dólar exigiria regras novas; eu não reaproveitaria as de setembro."),
        ("Choque externo: juros americanos", "O juro americano de dois anos passa de {us2y_exit} ou o de dez anos sobe ainda mais.", "As moedas emergentes tendem a enfraquecer juntas, qualquer que seja o resultado da eleição.", "Nenhuma posição comprada em reais; sair se já estiver posicionado."),
    ],
    "calendar_label": "Datas que importam",
    "calendar": {"election_first": "Eleição, primeiro turno", "election_runoff": "Segundo turno, se houver", "fomc": "Decisão do Fed", "copom": "Decisão do Copom", "both": "Decisões do Fed e do Copom"},

    "trade_title": "A operação simulada: comprar reais só com confirmação do mercado",
    "trade_status": "Inativa, sem posição · entrada possível a partir de {earliest}",
    "trade_rows": [
        ("Expressão", "Comprado em reais contra o dólar (vendido em USD/BRL), acompanhado pela PTAX oficial. Apenas simulação: sem dinheiro, sem execução."),
        ("Tese", "Se a eleição reduzir o prêmio de risco fiscal, o real deve se valorizar e continuar mais forte, porque os investidores seguem recebendo um grande colchão de juros enquanto esperam."),
        ("Por que pode não estar no preço", "O juro de dois anos está {gap_2y} acima do caminho dos próprios economistas, que esperam o USD/BRL a {focus_fx26} no fim do ano. Um real mais forte de forma duradoura não é o consenso, e o prêmio pode cair rápido se a incerteza se dissipar."),
        ("Catalisadores", "Primeiro turno em {first_round}; possível segundo turno em {runoff}; Fed em {fomc_next}; Copom em {copom_next}."),
        ("Entrada", "A partir de {earliest}: dois fechamentos diários seguidos da PTAX abaixo de {entry}, com o juro americano de dois anos em até {us2y_max}. {entry} está perto da mínima dos últimos 20 fechamentos ({range_low}–{range_high})."),
        ("Abandonar a ideia (antes da entrada)", "Qualquer fechamento da PTAX acima de {abandon}, acima de todos os fechamentos dos últimos quatro meses (máxima de {high4m} em {high4m_date}). A ideia é abandonada, não invertida."),
        ("Saída (depois da entrada)", "Dois fechamentos seguidos acima de {exit} (topo da faixa recente e mediana Focus para o fim do ano) ou o juro americano de dois anos acima de {us2y_exit}."),
        ("Reavaliação", "Perto de {review_low}–{review_high} (mínima da faixa menos a amplitude da faixa), ou no máximo em {review_by}. Uma zona de reavaliação, não um alvo."),
    ],
    "trade_more": "Riscos, o que mudaria a minha visão e o canal das commodities",
    "trade_risks_label": "Principais riscos",
    "trade_risks": [
        "O resultado da eleição é lido como negativo para as contas públicas, seja quem for o vencedor.",
        "Os juros americanos continuam subindo e tiram recursos dos mercados emergentes.",
        "O petróleo cai com força com a reabertura de Ormuz: menos receita de exportação para o Brasil e espaço para cortes mais rápidos do Copom, o que reduziria o colchão.",
        "A PTAX é uma taxa de referência diária, não um preço negociável. Custos, spreads e tamanho da posição não são modelados.",
    ],
    "trade_change_label": "Evidências que mudariam a minha visão",
    "trade_change": "Juro brasileiro de dois anos acima de {br2y_max} (verificado manualmente na ANBIMA), sinal do Copom de cortes mais rápidos, forte piora nos números fiscais oficiais ou juro americano de dois anos acima de {us2y_exit}.",
    "trade_channels_label": "Canais das commodities e da geopolítica",
    "trade_channels": "O Brasil exporta mais petróleo do que importa, então preços altos ajudam as contas externas. Eles também mantêm vivo o risco de inflação, o que deixa o Copom cauteloso e o colchão de juros largo. Uma reabertura do Estreito de Ormuz enfraqueceria os dois apoios ao mesmo tempo. Minério de ferro e soja dificilmente vão decidir esta janela de seis semanas (veja abaixo).",
    "trade_math_label": "A conta do carry",
    "trade_math": "((1 + {selic}) ÷ (1 + {fed_mid}))^(1/12) − 1 ≈ {carry} por mês. Uma posição real recebe esse ganho pelos preços a termo, não pela PTAX; por isso os níveis de decisão acima o ignoram.",

    "commodities_title": "Os preços das exportações brasileiras: quais importam agora?",
    "commodities_intro": "O Brasil recebe dólares exportando petróleo, minério de ferro, soja e açúcar. Cada série mantém a sua data e frequência; elas não são combinadas num índice.",
    "commodity_cols": ("Commodity", "Último", "Variação", "Importa nas próximas seis semanas?"),
    "commodity_names": {"brent": "Petróleo (Brent à vista)", "iron_ore": "Minério de ferro", "soybeans": "Soja", "sugar": "Açúcar"},
    "commodity_verdicts": {
        "brent": ("Sim, nos dois sentidos", "Apoia a receita de exportação e mantém o Copom cauteloso; uma reabertura repentina de Ormuz eliminaria os dois efeitos. O preço à vista está bem acima do futuro citado no noticiário."),
        "iron_ore": ("Agora, não", "O preço mensal do FMI recuou em julho. Sem mudança clara na demanda chinesa por aço, dificilmente move o real em seis semanas, embora importe diretamente para a Vale."),
        "soybeans": ("Pouco", "Os preços subiram em julho, mas a temporada de exportação brasileira se concentra entre março e julho; menos dólares da soja entram no quarto trimestre."),
        "sugar": ("Pouco", "As usinas podem alternar a cana entre açúcar e etanol; petróleo caro torna o etanol mais atraente, o que pode apertar a oferta de açúcar. É mais uma história de empresas do que de câmbio."),
    },
    "vs": "vs.",
    "units": {"USD per barrel": "US$/barril", "USD per metric ton": "US$/t", "US cents per pound": "¢ US$/lb"},
    "freq": {"daily": "diária", "weekly": "semanal", "monthly": "mensal", "quarterly": "trimestral"},

    "equity_title": "Do preço da commodity à empresa",
    "equity_intro": "Um movimento de preço é só o ponto de partida. Antes de chamar uma produtora de investimento, eu testaria quanto desse movimento chega à receita, às margens, ao caixa e ao valuation.",
    "equity_steps": [
        ("Exposição da receita", "O que a empresa realmente vende, a que preço realizado, em que moeda, e quanto está protegido por hedge?"),
        ("Margens e curva de custos", "Um preço maior vira lucro depois de energia, frete e câmbio? Onde a produtora está na curva de custos do setor?"),
        ("Balanço", "Ela consegue usar bem o caixa: alavancagem, investimentos, dividendos e recompras?"),
        ("Valuation", "A oportunidade já está no preço, com premissas normais e adversas, e o que provaria que a tese está errada?"),
    ],
    "equity_examples_label": "Por onde eu começaria no Brasil",
    "equity_examples": "Petrobras (preço realizado do petróleo e uma política de preços de combustíveis politicamente sensível em ano eleitoral); Vale (minério, China, frete); uma produtora de açúcar e etanol (a flexibilidade entre os dois). Pontos de partida para perguntas, não recomendações.",

    "method_title": "Método, dados e limitações",
    "method_calc_label": "Como os números são calculados",
    "method_calc": [
        ("Diferencial de juros", "Meta Selic menos o ponto médio da faixa do Fed. Compara juros básicos; não é um retorno de investimento."),
        ("Carry", "((1 + Selic) ÷ (1 + ponto médio do Fed))^(1/12) − 1, uma conta mensal aproximada que ignora custos."),
        ("Níveis de decisão", "Tirados dos últimos 20 fechamentos da PTAX na data da tese ({range_low}–{range_high}), arredondados para duas casas. A zona de reavaliação é a mínima da faixa menos a sua amplitude."),
        ("Mercado vs. economistas", "Caminho dos economistas: uma linha reta da Selic atual até as medianas Focus de fim de ano, menos 0,10 p.p. (a diferença usual entre o CDI e a Selic), capitalizada e anualizada em um e dois anos, e comparada com as taxas prefixadas de cupom zero da ANBIMA: um ano {survey_1y} vs. {br_1y}; dois anos {survey_2y} vs. {br_2y}."),
        ("Atualidade", "Séries diárias ficam “atrasadas” após 4 dias e “desatualizadas” após 7; a pesquisa Focus semanal, após 10 e 17; os preços mensais do FMI, após 100 e 130 dias do início do mês a que se referem."),
    ],
    "data_label": "Situação dos dados",
    "data_cols": ("Série", "Valor", "Observado", "Frequência", "Fonte", "Situação"),
    "series_names": {
        "selic_target": "Meta Selic", "fed_target_range": "Faixa do Fed", "brazil_us_policy_differential": "Diferencial Brasil–EUA",
        "ptax_usd_brl_midpoint": "PTAX USD/BRL", "us_2_year_treasury": "Juro dos EUA, 2 anos", "us_10_year_treasury": "Juro dos EUA, 10 anos",
        "focus_selic": "Focus Selic, fim de {year}", "focus_ipca": "Focus inflação, {year}", "focus_fx": "Focus USD/BRL, fim de {year}",
        "brent": "Brent à vista", "iron_ore": "Minério de ferro (FMI)", "soybeans": "Soja (FMI)", "sugar": "Açúcar (FMI)",
    },
    "refresh_label": "Como os dados são atualizados",
    "refresh_text": "Uma rotina do GitHub Actions roda depois do fechamento do mercado brasileiro em dias úteis. Ela consulta cada fonte oficial separadamente, valida os dados e salva um pequeno arquivo que esta página lê. Os visitantes nunca disparam uma consulta. Uma fonte com falha mantém o último valor válido, com a data original, e a falha é registrada. Uma segunda etapa marca a rotina como falha quando os números principais têm mais de uma semana.",
    "refresh_status": "Última tentativa de atualização: {attempted} · {ok} de {total} fontes atualizadas.",
    "refresh_failed": "Não atualizadas na última tentativa: {names}.",
    "refresh_history": "Até 24 de setembro de 2026, esta rotina falhava sem aviso nos dados americanos e a página continuava mostrando números de 13 de setembro. Isso foi corrigido: as fontes agora são independentes, os dados dos EUA têm alternativas oficiais e dados desatualizados deixam a rotina em vermelho.",
    "limits_label": "Limitações",
    "limits": [
        "A PTAX é a taxa de referência diária do Banco Central, não um preço negociável.",
        "A curva brasileira (ANBIMA) e os futuros de petróleo são observações datadas coletadas manualmente para esta tese; não são atualizados.",
        "A Focus é uma pesquisa, não um compromisso de política monetária. A diferença entre mercado e economistas mistura expectativas e prêmio de risco.",
        "As séries de commodities têm frequências e defasagens diferentes e nunca são combinadas.",
        "Não atribuo probabilidades aos caminhos; nenhuma das regras foi testada em dados históricos.",
        "Ferramentas de IA ajudaram a escrever código, rascunhar textos de pesquisa e traduzir. As regras e o julgamento final são meus, e cada número tem link para a fonte.",
    ],
    "sources_label": "Fontes",
    "sources_note": "Os links levam à fonte oficial ou, no contexto político e do petróleo, à reportagem utilizada. As datas indicam a que momento cada observação se refere.",
    "archive_label": "Tese anterior",
    "archive": "O estudo completo de 13 de setembro (cenários, regras e preços salvos) está preservado sem alterações no repositório, em research/data_snapshot.json.",

    "about_title": "Sobre o projeto",
    "about": "Sou Romeo Mugnier de Almeida, estudante de engenharia mecânica na EPFL, com raízes brasileiras e francesas. Comecei este projeto para entender como juros, câmbio e commodities interagem no Brasil, e o mantenho como um diário de pesquisa datado: cada visão vem com regras escritas antes do resultado, e cada visão antiga é revisada, inclusive no que errei.",
    "about_build": "Feito com Python e Streamlit. Dados oficiais do Banco Central do Brasil, do Tesouro americano, do Fed de Nova York e do FRED; atualização programada com validação por fonte; testes automatizados para os cálculos, as traduções, as regras de atualidade e os PDFs.",
    "links": {"code": "Código no GitHub", "linkedin": "LinkedIn"},
    "footer": "Pesquisa educacional, não é recomendação de investimento. Sem posições reais e sem desempenho alegado. Tese datada de {as_of}; cada número mostra a sua data.",

    "pdf_title": "Brasil macro: carry, eleição e uma operação condicional",
    "pdf_subtitle": "Relatório de pesquisa · tese datada de {as_of}",
    "pdf_page": "Página",
}

# ---------------------------------------------------------------------------
# French
TEXT["fr"] = {
    "html_lang": "fr",
    "language_label": "Langue",
    "skip": "Aller à la vue actuelle",
    "byline": "Génie mécanique à l’EPFL · brésilien et français",
    "kicker": "Brésil · taux d’intérêt · real · matières premières",
    "title": "Le Brésil, de la politique monétaire aux marchés.",
    "intro": "Un carnet de recherche d’étudiant sur la façon dont les taux brésiliens et américains, le real et les principales exportations du Brésil évoluent ensemble. Chaque vue est datée, s’appuie sur des données officielles avec lien et s’accompagne des règles qui me feraient agir ou changer d’avis.",
    "nav": {"view": "Vue actuelle", "review": "Bilan de la dernière thèse", "evidence": "Données", "paths": "Scénarios", "trade": "Opération fictive", "commodities": "Matières premières", "method": "Méthode et données"},
    "nav_label": "Sections",
    "view_label": "Ma vue actuelle",
    "status_no_position": "Aucune position",
    "view_headline": "Le real tient grâce à son important coussin de taux. Le prochain grand mouvement dépend de l’élection du {first_round}, que je ne sais pas prévoir, donc j’attends que le marché montre sa direction.",
    "why_label": "Pourquoi",
    "why": [
        ("Le coussin reste large.", "Même après la baisse du Brésil à {selic} et la hausse américaine à {fed_range} le 16 septembre, le taux directeur brésilien reste {gap} au-dessus. Détenir des reais plutôt que des dollars rapporte environ {carry} de plus par mois. C’est ce qu’on appelle le carry."),
        ("Les investisseurs font payer le risque.", "Le taux de marché brésilien à deux ans est de {br_2y}, environ {gap_2y} au-dessus de la moyenne implicite dans les propres prévisions des économistes ({survey_2y}). J’y vois surtout une prime pour l’incertitude budgétaire et politique."),
        ("L’élection est trop serrée pour être prévue.", "Datafolha donne Lula à {lula} % et Flávio Bolsonaro à {flavio} % au premier tour (marge de ±{moe}). Le budget 2027 est contesté : le gouvernement prévoit un excédent de {fiscal_gov}, l’institution budgétaire indépendante du Sénat un déficit de {fiscal_ifi}."),
    ],
    "act_label": "Ce qui me ferait agir",
    "act": "Après le premier tour : deux clôtures quotidiennes de la PTAX sous {entry}, avec un taux américain à deux ans inférieur ou égal à {us2y_max}. J’y verrais une baisse du risque budgétaire perçu, et j’achèterais des reais dans l’opération fictive.",
    "change_label": "Ce qui me ferait changer d’avis",
    "change": "Une clôture de la PTAX au-dessus de {abandon} avant toute entrée, un taux brésilien à deux ans au-dessus de {br2y_max} ou un taux américain à deux ans au-dessus de {us2y_exit}. Chacun signifierait que le risque augmente, et non qu’il diminue.",
    "monitor_label": "Vérification des règles",
    "monitor_note": "Comparaison automatique des données PTAX enregistrées avec les règles ci-dessus. Une vérification mécanique, pas une position réelle.",
    "monitor": {
        "waiting": "En attente du premier tour. Dernière PTAX {latest} ({latest_date}) ; aucune entrée n’est possible avant le {earliest}.",
        "watching": "Sous surveillance. Dernière PTAX {latest} ({latest_date}) ; l’entrée exige deux clôtures sous {entry}.",
        "entered": "Conditions d’entrée réunies le {date} à {value} (fictif). Dernière PTAX {latest} ({latest_date}).",
        "review": "La position fictive a atteint la zone de réexamen le {date} ({value}). Réexaminer avant toute autre décision.",
        "exited": "Position fictive clôturée par la règle de sortie le {date} à {value}.",
        "abandoned": "Idée abandonnée : la PTAX a clôturé à {value} le {date}, au-dessus de {abandon}.",
        "expired": "La date de réexamen ({review_by}) est passée sans entrée. Cette thèse doit être mise à jour.",
        "unavailable": "Vérification indisponible : l’historique PTAX enregistré n’a pas pu être lu.",
    },
    "tape_label": "Dernières données officielles",
    "tape": {
        "selic_target": "Taux Selic",
        "fed_target_range": "Fourchette de la Fed",
        "brazil_us_policy_differential": "Écart Brésil–États-Unis",
        "ptax_usd_brl_midpoint": "USD/BRL (PTAX)",
        "us_2_year_treasury": "Taux US à 2 ans",
        "brent": "Brent (comptant)",
    },
    "fresh": {"fresh": "À jour", "delayed": "En retard", "stale": "Périmé", "unknown": "Date inconnue"},
    "stale_banner": "Certains chiffres sont plus anciens que d’habitude (signalés ci-dessous). La page affiche chaque valeur avec sa propre date au lieu de la masquer.",
    "refresh_banner": "La mise à jour automatique n’a pas tourné depuis le {date}. Les chiffres ci-dessous gardent leur date d’origine.",
    "unavailable": "Indisponible",
    "na": "n.d.",
    "download": "Télécharger la note de recherche (PDF, français)",
    "download_help": "4 pages, la même thèse datée que cette page, générée à partir des fichiers enregistrés",

    "review_title": "Ce qu’est devenue ma thèse du 13 septembre",
    "review_intro": "Le 13 septembre, je m’attendais à ce que les deux banques centrales fassent ce que le marché anticipait, et je n’aurais acheté des dollars que si l’USD/BRL franchissait {prev_trigger}. Aucune position n’a été ouverte : il n’y a donc pas de performance à présenter, seulement un raisonnement à vérifier.",
    "review_head": ("Ce que j’attendais", "Ce qui s’est passé", "Verdict"),
    "review_rows": {
        "decisions": ("Le Copom baisse de 0,25 pt ; la Fed monte de 0,25 pt.", "Les deux le 16 septembre : Selic {selic_prev} → {selic} ; Fed {fed_prev_range} → {fed_range}, à l’unanimité."),
        "gap": ("L’écart de taux se réduit d’environ 0,50 pt.", "{gap_prev} → {gap}."),
        "us_yields": ("Des taux américains plus hauts renforcent le dollar.", "Taux américain à deux ans {us2y_prev} → {us2y} ; USD/BRL {ptax_prev} → {ptax} ({ptax_chg}). Bonne direction, faible amplitude."),
        "oil": ("Un pétrole au-dessus de 100 $ soutient le real.", "Le Brent au comptant a culminé à {brent_peak} le {brent_peak_date}, et pourtant le real s’est affaibli. Le pétrole a peut-être amorti le mouvement ; les données ne permettent pas de le distinguer des taux américains et de la politique."),
        "trigger": ("Agir seulement au-dessus de {prev_trigger} ; abandonner sous {prev_abandon}.", "Plus haute clôture {ptax_high} ({ptax_high_date}) ; plus basse {ptax_low} ({ptax_low_date}). Aucun des deux niveaux n’a été atteint."),
        "election": ("L’élection traitée comme un risque secondaire.", "Fin septembre, les comptes rendus quotidiens des marchés citaient les sondages, aux côtés des taux américains, parmi les principaux moteurs du real."),
    },
    "verdicts": {"confirmed": "Confirmé", "partly": "En partie", "unresolved": "Non tranché", "not_triggered": "Non déclenché", "underweighted": "Sous-estimé"},
    "review_lesson_label": "Ce que j’ai corrigé",
    "review_lesson": "La taille du coussin de taux a compté davantage que sa baisse de 0,50 point, et j’ai traité l’élection comme une note de bas de page alors qu’elle est l’événement principal. La nouvelle thèse part de ces deux corrections.",

    "evidence_title": "Les données, classées par nature",
    "evidence_intro": "Chaque élément porte une étiquette pour séparer les faits, les prix, les prévisions et ma propre lecture. Les valeurs sont figées à la date de la thèse ({as_of}) ; les chiffres actualisés figurent en haut de la page.",
    "kinds": {"fact": "Fait", "pricing": "Prix de marché", "survey": "Enquêtes et projections", "interpretation": "Mon interprétation"},
    "kind_help": {
        "fact": "Quelque chose qui s’est produit.",
        "pricing": "Ce que les prix impliquent aujourd’hui.",
        "survey": "Ce qu’attendent prévisionnistes et responsables.",
        "interpretation": "Ma lecture, qui peut être fausse.",
    },
    "evidence": {
        "fact": [
            "Le Copom a abaissé le Selic de 0,25 pt à {selic} le 16 septembre, à l’unanimité (sa {cuts_count}e baisse consécutive et {cuts_total} depuis mars). Il n’a donné aucune indication sur la suite, juge les risques d’inflation orientés à la hausse et prévoit une inflation de {copom_proj} début 2028, encore au-dessus de la cible de {target}.",
            "La Fed a relevé sa fourchette de 0,25 pt à {fed_range} le 16 septembre (12 voix contre 0), estimant que l’inflation « reste élevée ».",
            "L’écart entre les deux taux directeurs est passé de {gap_prev} à {gap}.",
            "Le Brésil vote le {first_round} ; un éventuel second tour aura lieu le {runoff}. Datafolha (15–17 sept.) : Lula {lula} %, Flávio Bolsonaro {flavio} % au premier tour ; {runoff_lula} % contre {runoff_flavio} % au second (±{moe}).",
            "Pour 2027, le projet de budget du gouvernement prévoit un excédent primaire de {fiscal_gov} ; l’Institution budgétaire indépendante du Sénat prévoit un déficit de {fiscal_ifi}.",
        ],
        "pricing": [
            "L’USD/BRL (PTAX) valait {ptax} le {ptax_date}, {ptax_chg} depuis le 11 septembre, mais reste dans sa fourchette des quatre derniers mois ({low4m}–{high4m}).",
            "Le taux du Trésor américain à deux ans est passé de {us2y_prev} (10 sept.) à {us2y} ; le dix ans est à {us10y}.",
            "Courbe brésilienne à taux fixe (ANBIMA, 23 sept.) : un an {br_1y}, deux ans {br_2y}. Inflation implicite dans la courbe sur deux ans : {be_2y}.",
            "Brent : le prix au comptant de l’EIA était de {brent} le {brent_date} après un pic à {brent_peak} le {brent_peak_date} (il était à {brent_july} fin juillet). Le contrat à terme de novembre, le plus cité dans la presse, a clôturé à {brent_fut} le {brent_fut_date}.",
        ],
        "survey": [
            "Médianes de l’enquête Focus ({focus_date}) : Selic à {focus_selic26} fin 2026 et {focus_selic27} fin 2027 ; inflation de {focus_ipca26} en 2026 et {focus_ipca27} en 2027 ; USD/BRL à {focus_fx26} fin 2026.",
            "Projection médiane des responsables de la Fed : {fed_proj_2026} fin 2026 (une hausse supplémentaire de 0,25 pt), contre {fed_proj_june} en juin.",
            "L’EIA (9 sept.) prévoyait un Brent moyen d’environ {eia_2h} au second semestre 2026, avant l’attaque du 11 septembre contre l’oléoduc Est–Ouest saoudien.",
        ],
        "interpretation": [
            "Si la politique monétaire suit le chemin des économistes, le taux au jour le jour moyen sur deux ans serait d’environ {survey_2y} ; le taux de marché à deux ans est de {br_2y}. L’écart de {gap_2y} signifie soit que le marché attend moins de baisses du Copom, soit qu’il exige une prime de risque. J’y vois surtout une prime de risque, car l’inflation implicite ({be_2y}) dépasse largement les prévisions ({focus_ipca27} pour 2027), mais les données ne permettent pas de le prouver.",
            "Le fort écart entre le pétrole au comptant et à terme indique une pénurie physique immédiate, mais une détente attendue. Le soutien du pétrole au real pourrait donc être temporaire.",
            "Une baisse de 0,50 point d’un écart de {gap_round} points change à peine l’intérêt de détenir des reais ; une variation de la prime de risque peut faire bouger la devise bien davantage.",
        ],
    },
    "focus_table_caption": "Médianes de l’enquête Focus, {focus_date}",
    "focus_rows": ("Selic, fin d’année", "Inflation (IPCA)", "USD/BRL, fin d’année"),
    "chart_title": "USD/BRL (PTAX) : {n} dernières séances et mes niveaux de décision",
    "chart_desc": "Clôtures quotidiennes de la PTAX du {start} au {end}. Dernière valeur {latest}. Niveaux : entrée sous {entry}, sortie au-dessus de {exit}, abandon au-dessus de {abandon} ; en pointillé : le déclencheur inutilisé de septembre, {prev_trigger}.",
    "chart_labels": {"entry": "Entrée < {entry}", "exit": "Sortie > {exit}", "abandon": "Abandon > {abandon}", "prev": "Seuil de sept. {prev_trigger}", "event": "Décisions du 16 sept."},
    "chart_table": "Afficher les données du graphique sous forme de tableau",
    "chart_cols": ("Date", "PTAX"),

    "paths_title": "Ce qui peut se passer après le {first_round}",
    "paths_intro": "Trois scénarios que je sais reconnaître dans les données, plus un choc extérieur. Je n’attribue pas de probabilités : il s’agit de décider à l’avance ce que chacun signifierait et ce que je ferais.",
    "path_fields": ("Signaux", "Ce que cela signifierait", "Ce que je ferais"),
    "paths": [
        ("La prime de risque baisse", "Deux clôtures de la PTAX sous {entry} ; le taux à deux ans recule d’au moins 0,25 point depuis {br_2y} ; l’inflation implicite se détend.", "Les investisseurs voient moins de risque budgétaire, et le coussin de taux continue d’attirer des capitaux.", "Acheter des reais dans l’opération fictive si le taux américain à deux ans est inférieur ou égal à {us2y_max}."),
        ("Pas de verdict avant le second tour", "La PTAX reste entre {entry} et {abandon} ; les sondages restent serrés.", "Le marché attend le {runoff}.", "Aucune position. Réexaminer après le second tour et la décision du Copom du {copom_next}."),
        ("La prime de risque monte", "La PTAX clôture au-dessus de {abandon} ; le taux à deux ans dépasse {br2y_max} ; l’inflation implicite augmente.", "Les inquiétudes budgétaires dominent. Un real plus faible et un pétrole cher pourraient pousser le Copom à suspendre ses baisses.", "Abandonner l’idée d’acheter des reais. Une opération à l’achat de dollars exigerait de nouvelles règles ; je ne recyclerais pas celles de septembre."),
        ("Choc extérieur : les taux américains", "Le taux américain à deux ans dépasse {us2y_exit}, ou le dix ans grimpe encore.", "Les devises émergentes ont tendance à baisser ensemble, quel que soit le résultat de l’élection brésilienne.", "Aucune position à l’achat de reais ; sortir si elle est déjà ouverte."),
    ],
    "calendar_label": "Dates clés",
    "calendar": {"election_first": "Élection, premier tour", "election_runoff": "Second tour, si nécessaire", "fomc": "Décision de la Fed", "copom": "Décision du Copom", "both": "Décisions de la Fed et du Copom"},

    "trade_title": "L’opération fictive : acheter le real seulement si le marché confirme",
    "trade_status": "Inactive, aucune position · entrée possible à partir du {earliest}",
    "trade_rows": [
        ("Expression", "Achat du real contre le dollar américain (vente d’USD/BRL), suivi avec le taux officiel PTAX. Opération fictive : ni argent, ni exécution."),
        ("Thèse", "Si l’élection réduit la prime de risque budgétaire, le real devrait s’apprécier et le rester, car les investisseurs continuent de toucher un large coussin de taux en attendant."),
        ("Pourquoi ce n’est peut-être pas dans les prix", "Le taux à deux ans se situe {gap_2y} au-dessus du chemin des économistes eux-mêmes, qui attendent l’USD/BRL à {focus_fx26} en fin d’année. Un real durablement plus fort n’est pas le consensus, et la prime pourrait se comprimer vite si l’incertitude se dissipe."),
        ("Catalyseurs", "Premier tour le {first_round} ; second tour éventuel le {runoff} ; Fed le {fomc_next} ; Copom le {copom_next}."),
        ("Entrée", "À partir du {earliest} : deux clôtures quotidiennes consécutives de la PTAX sous {entry}, avec un taux américain à deux ans inférieur ou égal à {us2y_max}. {entry} est proche du bas des 20 dernières clôtures ({range_low}–{range_high})."),
        ("Abandon (avant l’entrée)", "Toute clôture de la PTAX au-dessus de {abandon}, plus haut que toutes les clôtures des quatre derniers mois (pic de {high4m} le {high4m_date}). L’idée est abandonnée, pas inversée."),
        ("Sortie (après l’entrée)", "Deux clôtures consécutives au-dessus de {exit} (le haut de la fourchette récente et la médiane Focus de fin d’année), ou un taux américain à deux ans au-dessus de {us2y_exit}."),
        ("Réexamen", "Vers {review_low}–{review_high} (bas de la fourchette moins sa largeur), ou au plus tard le {review_by}. Une zone de réexamen, pas un objectif."),
    ],
    "trade_more": "Risques, ce qui changerait ma vue et le canal des matières premières",
    "trade_risks_label": "Principaux risques",
    "trade_risks": [
        "Le résultat de l’élection est jugé négatif pour les finances publiques, quel que soit le vainqueur.",
        "Les taux américains continuent de monter et détournent les capitaux des marchés émergents.",
        "Le pétrole chute avec la réouverture d’Ormuz : moins de recettes d’exportation pour le Brésil et de la marge pour des baisses plus rapides du Copom, ce qui réduirait le coussin.",
        "La PTAX est un taux de référence quotidien, pas un prix négociable. Coûts, écarts de cotation et taille de position ne sont pas modélisés.",
    ],
    "trade_change_label": "Ce qui changerait ma vue",
    "trade_change": "Un taux brésilien à deux ans au-dessus de {br2y_max} (vérifié à la main sur l’ANBIMA), un signal du Copom en faveur de baisses plus rapides, une nette dégradation des chiffres budgétaires officiels, ou un taux américain à deux ans au-dessus de {us2y_exit}.",
    "trade_channels_label": "Canaux des matières premières et de la géopolitique",
    "trade_channels": "Le Brésil exporte plus de pétrole qu’il n’en importe : des prix élevés aident ses comptes extérieurs. Ils entretiennent aussi le risque d’inflation, ce qui garde le Copom prudent et le coussin de taux large. Une réouverture du détroit d’Ormuz affaiblirait ces deux soutiens à la fois. Le minerai de fer et le soja ont peu de chances de décider cette fenêtre de six semaines (voir plus bas).",
    "trade_math_label": "Le calcul du carry",
    "trade_math": "((1 + {selic}) ÷ (1 + {fed_mid}))^(1/12) − 1 ≈ {carry} par mois. Une position réelle le perçoit via les prix à terme, pas via la PTAX ; les niveaux de décision ci-dessus l’ignorent donc.",

    "commodities_title": "Les prix des exportations brésiliennes : lesquels comptent maintenant ?",
    "commodities_intro": "Le Brésil gagne des dollars en exportant du pétrole, du minerai de fer, du soja et du sucre. Chaque série garde sa propre date et sa fréquence ; elles ne sont pas combinées en un indice.",
    "commodity_cols": ("Matière première", "Dernier", "Variation", "Compte pour les six prochaines semaines ?"),
    "commodity_names": {"brent": "Pétrole (Brent comptant)", "iron_ore": "Minerai de fer", "soybeans": "Soja", "sugar": "Sucre"},
    "commodity_verdicts": {
        "brent": ("Oui, dans les deux sens", "Soutient les recettes d’exportation et garde le Copom prudent ; une réouverture soudaine d’Ormuz supprimerait ces deux effets. Le prix au comptant est bien au-dessus du prix à terme cité dans la presse."),
        "iron_ore": ("Pas maintenant", "Le prix mensuel du FMI a reculé en juillet. Sans changement net de la demande chinoise d’acier, il a peu de chances de faire bouger le real en six semaines, même s’il compte directement pour Vale."),
        "soybeans": ("Limité", "Les prix ont monté en juillet, mais la saison d’exportation brésilienne culmine entre mars et juillet : moins de dollars du soja arrivent au quatrième trimestre."),
        "sugar": ("Limité", "Les usines peuvent orienter la canne vers le sucre ou l’éthanol ; un pétrole cher rend l’éthanol plus attractif, ce qui peut resserrer l’offre de sucre. Un sujet d’entreprise plus que de change."),
    },
    "vs": "vs",
    "units": {"USD per barrel": "USD/baril", "USD per metric ton": "USD/t", "US cents per pound": "cents US/lb"},
    "freq": {"daily": "quotidienne", "weekly": "hebdomadaire", "monthly": "mensuelle", "quarterly": "trimestrielle"},

    "equity_title": "Du prix d’une matière première à une entreprise",
    "equity_intro": "Un mouvement de prix n’est qu’un point de départ. Avant de parler d’investissement dans un producteur, je vérifierais quelle part du mouvement atteint le chiffre d’affaires, les marges, la trésorerie et la valorisation.",
    "equity_steps": [
        ("Exposition du chiffre d’affaires", "Que vend réellement l’entreprise, à quel prix réalisé, dans quelle devise, et quelle part est couverte ?"),
        ("Marges et courbe de coûts", "Un prix plus élevé devient-il du profit après l’énergie, le fret et le change ? Où se situe le producteur sur la courbe de coûts du secteur ?"),
        ("Bilan", "Sait-il bien utiliser sa trésorerie : endettement, investissements, dividendes et rachats d’actions ?"),
        ("Valorisation", "L’opportunité est-elle déjà dans le prix, avec des hypothèses normales et défavorables, et qu’est-ce qui prouverait que la thèse est fausse ?"),
    ],
    "equity_examples_label": "Par où je commencerais au Brésil",
    "equity_examples": "Petrobras (prix réalisé du pétrole et politique de prix des carburants politiquement sensible en année électorale) ; Vale (minerai de fer, Chine, fret) ; un producteur de sucre et d’éthanol (la flexibilité entre les deux). Des points de départ pour des questions, pas des recommandations.",

    "method_title": "Méthode, données et limites",
    "method_calc_label": "Comment les chiffres sont calculés",
    "method_calc": [
        ("Écart de taux", "Taux Selic moins le milieu de la fourchette de la Fed. Il compare des taux directeurs ; ce n’est pas un rendement d’investissement."),
        ("Carry", "((1 + Selic) ÷ (1 + milieu de la Fed))^(1/12) − 1, un ordre de grandeur mensuel qui ignore les coûts."),
        ("Niveaux de décision", "Tirés des 20 dernières clôtures de la PTAX à la date de la thèse ({range_low}–{range_high}), arrondis à deux décimales. La zone de réexamen est le bas de la fourchette moins sa largeur."),
        ("Marché contre économistes", "Chemin des économistes : une droite du Selic actuel jusqu’aux médianes Focus de fin d’année, moins 0,10 pt (l’écart habituel entre le taux au jour le jour CDI et le Selic), capitalisée et annualisée sur un et deux ans, puis comparée aux taux zéro-coupon à taux fixe de l’ANBIMA : un an {survey_1y} contre {br_1y} ; deux ans {survey_2y} contre {br_2y}."),
        ("Fraîcheur", "Les séries quotidiennes sont « en retard » après 4 jours et « périmées » après 7 ; l’enquête Focus hebdomadaire après 10 et 17 ; les prix mensuels du FMI après 100 et 130 jours à compter du début du mois concerné."),
    ],
    "data_label": "État des données",
    "data_cols": ("Série", "Valeur", "Observée", "Fréquence", "Source", "État"),
    "series_names": {
        "selic_target": "Taux Selic", "fed_target_range": "Fourchette de la Fed", "brazil_us_policy_differential": "Écart Brésil–États-Unis",
        "ptax_usd_brl_midpoint": "PTAX USD/BRL", "us_2_year_treasury": "Taux US à 2 ans", "us_10_year_treasury": "Taux US à 10 ans",
        "focus_selic": "Focus Selic, fin {year}", "focus_ipca": "Focus inflation, {year}", "focus_fx": "Focus USD/BRL, fin {year}",
        "brent": "Brent comptant", "iron_ore": "Minerai de fer (FMI)", "soybeans": "Soja (FMI)", "sugar": "Sucre (FMI)",
    },
    "refresh_label": "Comment les données sont actualisées",
    "refresh_text": "Une tâche GitHub Actions tourne après la clôture brésilienne les jours ouvrés. Elle interroge chaque source officielle séparément, valide les données et enregistre un petit fichier que cette page lit. Les visiteurs ne déclenchent jamais de requête. Une source en échec garde sa dernière valeur valide, avec sa date d’origine, et l’échec est signalé. Une seconde étape marque la tâche en échec lorsque les chiffres clés ont plus d’une semaine.",
    "refresh_status": "Dernière tentative d’actualisation : {attempted} · {ok} sources sur {total} mises à jour.",
    "refresh_failed": "Non actualisées lors de la dernière tentative : {names}.",
    "refresh_history": "Jusqu’au 24 septembre 2026, cette tâche échouait sans alerte sur les données américaines et la page affichait encore les chiffres du 13 septembre. C’est corrigé : les sources sont désormais indépendantes, les données américaines ont des alternatives officielles et des données périmées font échouer la tâche.",
    "limits_label": "Limites",
    "limits": [
        "La PTAX est le taux de référence quotidien de la banque centrale, pas un prix auquel on peut traiter.",
        "La courbe brésilienne (ANBIMA) et les contrats à terme sur le pétrole sont des observations datées, relevées à la main pour cette thèse ; elles ne s’actualisent pas.",
        "Focus est une enquête, pas un engagement de politique monétaire. L’écart entre marché et économistes mélange anticipations et prime de risque.",
        "Les séries de matières premières ont des fréquences et des délais de publication différents et ne sont jamais combinées.",
        "Aucune probabilité n’est attribuée aux scénarios ; aucune des règles n’a été testée sur l’historique.",
        "Des outils d’IA ont aidé à écrire le code, à rédiger les textes de recherche et à traduire. Les règles et le jugement final sont les miens, et chaque chiffre renvoie à sa source.",
    ],
    "sources_label": "Sources",
    "sources_note": "Les liens renvoient à la source officielle ou, pour le contexte politique et pétrolier, à l’article utilisé. Les dates indiquent à quel moment chaque observation s’applique.",
    "archive_label": "Thèse précédente",
    "archive": "L’étude complète du 13 septembre (scénarios, règles et prix enregistrés) est conservée telle quelle dans le dépôt, dans research/data_snapshot.json.",

    "about_title": "À propos du projet",
    "about": "Je suis Romeo Mugnier de Almeida, étudiant en génie mécanique à l’EPFL, avec des racines brésiliennes et françaises. J’ai lancé ce projet pour comprendre comment les taux, la devise et les matières premières interagissent au Brésil, et je le tiens comme un carnet de recherche daté : chaque vue s’accompagne de règles écrites avant le résultat, et chaque ancienne vue est réexaminée, y compris ce que j’ai eu faux.",
    "about_build": "Construit avec Python et Streamlit. Données officielles de la Banque centrale du Brésil, du Trésor américain, de la Fed de New York et de FRED ; actualisation programmée avec validation par source ; tests automatisés pour les calculs, les traductions, les règles de fraîcheur et les PDF.",
    "links": {"code": "Code sur GitHub", "linkedin": "LinkedIn"},
    "footer": "Recherche pédagogique, pas un conseil en investissement. Aucune position réelle ni performance revendiquée. Thèse datée du {as_of} ; chaque chiffre affiche sa propre date.",

    "pdf_title": "Brésil macro : carry, élection et une opération conditionnelle",
    "pdf_subtitle": "Note de recherche · thèse datée du {as_of}",
    "pdf_page": "Page",
}

# ---------------------------------------------------------------------------
# Source names: a short tag next to each claim and a full, dated label in the
# source list.  Proper names (BCB, ANBIMA, Datafolha) stay as they are.
_SOURCE_SHORT = {
    "en": {"derived_gap": "calculated", "treasury": "U.S. Treasury", "nyfed": "New York Fed", "fred_iron": "IMF via FRED",
           "fred_soy": "IMF via FRED", "fred_sugar": "IMF via FRED", "ifi_ploa2027": "Senate IFI"},
    "pt": {"derived_gap": "cálculo próprio", "treasury": "Tesouro dos EUA", "nyfed": "Fed de Nova York", "fred_iron": "FMI via FRED",
           "fred_soy": "FMI via FRED", "fred_sugar": "FMI via FRED", "ifi_ploa2027": "IFI do Senado"},
    "fr": {"derived_gap": "calcul propre", "treasury": "Trésor américain", "nyfed": "Fed de New York", "fred_iron": "FMI via FRED",
           "fred_soy": "FMI via FRED", "fred_sugar": "FMI via FRED", "ifi_ploa2027": "IFI du Sénat"},
}
_SOURCE_COMMON = {
    "copom_281": "BCB", "copom_statements": "BCB", "copom_calendar": "BCB", "fomc_statement": "Federal Reserve",
    "fomc_sep": "Federal Reserve", "fomc_calendar": "Federal Reserve", "bcb_ptax": "BCB", "bcb_focus": "BCB",
    "anbima_ettj": "ANBIMA", "fred_brent": "EIA via FRED", "eia_steo": "EIA", "aljazeera_pipeline": "Al Jazeera",
    "advfn_estadao_0923": "Estadão / ADVFN", "datafolha_0917": "Datafolha / O Povo", "tse": "TSE",
}
_SOURCE_LABELS = {
    "en": {
        "copom_281": "BCB · Minutes of the 281st Copom meeting (decision of 16 Sep, published 22 Sep)",
        "copom_statements": "BCB · Copom statements",
        "copom_calendar": "BCB · 2026 Copom meeting calendar",
        "fomc_statement": "Federal Reserve · FOMC statement of 16 Sep 2026",
        "fomc_sep": "Federal Reserve · Summary of Economic Projections, 16 Sep 2026",
        "fomc_calendar": "Federal Reserve · FOMC meeting calendar",
        "derived_gap": "Calculated · Selic target minus the Fed target-range midpoint",
        "bcb_ptax": "BCB · PTAX exchange rates (open-data API)",
        "bcb_focus": "BCB · Focus market expectations (open-data API)",
        "treasury": "U.S. Treasury · Daily par yield curve rates",
        "nyfed": "New York Fed · Effective federal funds rate and target range",
        "anbima_ettj": "ANBIMA · Term structure of interest rates (ETTJ), 23 Sep 2026",
        "fred_brent": "EIA via FRED · Brent crude spot price (DCOILBRENTEU)",
        "fred_iron": "IMF via FRED · Global iron-ore price (PIORECRUSDM)",
        "fred_soy": "IMF via FRED · Global soybean price, monthly (PSOYBUSDM)",
        "fred_sugar": "IMF via FRED · Sugar No. 11 world price (PSUGAISAUSDM)",
        "eia_steo": "EIA · Short-Term Energy Outlook, 9 Sep 2026",
        "aljazeera_pipeline": "Al Jazeera · Saudi Arabia shuts East–West pipeline after drone attack",
        "advfn_estadao_0923": "Estadão Conteúdo via ADVFN · Dollar, Treasuries, oil and polls (23 Sep)",
        "datafolha_0917": "Datafolha poll, 15–17 Sep 2026, reported by O Povo (TSE BR-04029/2026)",
        "tse": "TSE · 2026 elections",
        "ifi_ploa2027": "Senate Independent Fiscal Institution (IFI) · Assessment of the 2027 budget bill",
    },
    "pt": {
        "copom_281": "BCB · Ata da 281ª reunião do Copom (decisão de 16/9, publicada em 22/9)",
        "copom_statements": "BCB · Comunicados do Copom",
        "copom_calendar": "BCB · Calendário de reuniões do Copom em 2026",
        "fomc_statement": "Federal Reserve · Comunicado do FOMC de 16/9/2026",
        "fomc_sep": "Federal Reserve · Projeções econômicas (SEP), 16/9/2026",
        "fomc_calendar": "Federal Reserve · Calendário de reuniões do FOMC",
        "derived_gap": "Cálculo próprio · Meta Selic menos o ponto médio da faixa do Fed",
        "bcb_ptax": "BCB · Cotações PTAX (API de dados abertos)",
        "bcb_focus": "BCB · Expectativas de mercado Focus (API de dados abertos)",
        "treasury": "Tesouro dos EUA · Taxas diárias da curva par",
        "nyfed": "Fed de Nova York · Taxa efetiva dos fed funds e faixa-alvo",
        "anbima_ettj": "ANBIMA · Estrutura a termo das taxas de juros (ETTJ), 23/9/2026",
        "fred_brent": "EIA via FRED · Preço à vista do petróleo Brent (DCOILBRENTEU)",
        "fred_iron": "FMI via FRED · Preço global do minério de ferro (PIORECRUSDM)",
        "fred_soy": "FMI via FRED · Preço global da soja, mensal (PSOYBUSDM)",
        "fred_sugar": "FMI via FRED · Preço mundial do açúcar nº 11 (PSUGAISAUSDM)",
        "eia_steo": "EIA · Short-Term Energy Outlook, 9/9/2026",
        "aljazeera_pipeline": "Al Jazeera · Arábia Saudita fecha oleoduto Leste–Oeste após ataque de drones",
        "advfn_estadao_0923": "Estadão Conteúdo via ADVFN · Dólar, Treasuries, petróleo e pesquisas (23/9)",
        "datafolha_0917": "Pesquisa Datafolha de 15 a 17/9/2026, divulgada pelo O Povo (TSE BR-04029/2026)",
        "tse": "TSE · Eleições 2026",
        "ifi_ploa2027": "Instituição Fiscal Independente do Senado (IFI) · Análise do PLOA 2027",
    },
    "fr": {
        "copom_281": "BCB · Compte rendu de la 281e réunion du Copom (décision du 16 sept., publié le 22 sept.)",
        "copom_statements": "BCB · Communiqués du Copom",
        "copom_calendar": "BCB · Calendrier des réunions du Copom en 2026",
        "fomc_statement": "Federal Reserve · Communiqué du FOMC du 16 sept. 2026",
        "fomc_sep": "Federal Reserve · Projections économiques (SEP), 16 sept. 2026",
        "fomc_calendar": "Federal Reserve · Calendrier des réunions du FOMC",
        "derived_gap": "Calcul propre · Taux Selic moins le milieu de la fourchette de la Fed",
        "bcb_ptax": "BCB · Taux de change PTAX (API de données ouvertes)",
        "bcb_focus": "BCB · Anticipations de marché Focus (API de données ouvertes)",
        "treasury": "Trésor américain · Taux quotidiens de la courbe au pair",
        "nyfed": "Fed de New York · Taux effectif des fed funds et fourchette cible",
        "anbima_ettj": "ANBIMA · Structure par terme des taux d’intérêt (ETTJ), 23 sept. 2026",
        "fred_brent": "EIA via FRED · Prix au comptant du Brent (DCOILBRENTEU)",
        "fred_iron": "FMI via FRED · Prix mondial du minerai de fer (PIORECRUSDM)",
        "fred_soy": "FMI via FRED · Prix mondial du soja, mensuel (PSOYBUSDM)",
        "fred_sugar": "FMI via FRED · Prix mondial du sucre n° 11 (PSUGAISAUSDM)",
        "eia_steo": "EIA · Short-Term Energy Outlook, 9 sept. 2026",
        "aljazeera_pipeline": "Al Jazeera · L’Arabie saoudite ferme l’oléoduc Est–Ouest après une attaque de drones",
        "advfn_estadao_0923": "Estadão Conteúdo via ADVFN · Dollar, Treasuries, pétrole et sondages (23 sept.)",
        "datafolha_0917": "Sondage Datafolha du 15 au 17 sept. 2026, publié par O Povo (TSE BR-04029/2026)",
        "tse": "TSE · Élections 2026",
        "ifi_ploa2027": "Institution budgétaire indépendante du Sénat (IFI) · Analyse du projet de budget 2027",
    },
}
_PDF_EXTRA = {
    "en": {"pdf_data_label": "Key figures at the thesis date", "pdf_more": "The full evidence list, data status and calculations are on the website:"},
    "pt": {"pdf_data_label": "Números-chave na data da tese", "pdf_more": "A lista completa de evidências, a situação dos dados e os cálculos estão no site:"},
    "fr": {"pdf_data_label": "Chiffres clés à la date de la thèse", "pdf_more": "La liste complète des données, leur état et les calculs sont sur le site :"},
}
for _lang in TEXT:
    TEXT[_lang].update(_PDF_EXTRA[_lang])
    TEXT[_lang]["source_short"] = {**_SOURCE_COMMON, **_SOURCE_SHORT[_lang]}
    TEXT[_lang]["source_labels"] = _SOURCE_LABELS[_lang]


def _french_typography(value):
    """No-break (narrow) spaces before : ; ? ! % and inside « », so they never wrap."""

    if isinstance(value, str):
        for plain, spaced in ((" :", " :"), (" ;", " ;"), (" ?", " ?"), (" !", " !"),
                              (" %", " %"), ("« ", "« "), (" »", " »")):
            value = value.replace(plain, spaced)
        return value
    if isinstance(value, dict):
        return {key: _french_typography(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_french_typography(item) for item in value]
    if isinstance(value, tuple):
        return tuple(_french_typography(item) for item in value)
    return value


TEXT["fr"] = _french_typography(TEXT["fr"])
