"""Work-sample and risk-lab copy; all three languages share the same structure."""
from src.content import _french_typography

TEXT = {
    "en": {
        "kicker": "Independent research / Brazil",
        "intro": "I turn official market data into reproducible Python studies, test the assumptions, and translate a view into rates, FX and commodity risk.",
        "scope": "EPFL engineering · Rates / FX / Commodities",
        "lab_cta": "Explore the risk lab",
        "code_cta": "Inspect the research",
        "reasoning": "Read the reasoning and decision rules",
        "dated": "Dated research · not a live recommendation",
        "scope_labels": ["Daily FX observations", "Commodity months", "Completed elections"],
        "scope_note": "Saved inputs. Reproducible calculations. No claimed trading performance.",
        "lab_nav": "Risk lab",
        "risk_nav": "Model validation",
        "lab_title": "From a market view to a risk number.",
        "lab_intro": "Change the assumptions. See how rates affect a bond, currency affects a funded real position, and both FX and commodity prices affect a producer.",
        "lab_modes": ["Rates · DV01", "FX · carry", "Producer · hedge"],
        "rate_intro": "A hypothetical zero-coupon bond, valued with a dated ANBIMA zero rate. Higher yields lower its price; longer maturity increases its sensitivity.",
        "rate_intro_fallback": "A hypothetical zero-coupon bond. Available yields use the saved ANBIMA curve; missing maturities start from an editable 13% example.",
        "maturity": "Maturity (years)",
        "principal": "Face value (R$)",
        "yield": "Annual zero yield (%)",
        "rate_shock": "Yield shock (basis points)",
        "rate_metrics": ["Present value", "DV01 · R$ per bp", "Exact price change"],
        "rate_detail": "Duration approximation",
        "rate_gap": "Exact minus approximation",
        "rate_note": "Annual compounding; 252 business days per year. Face value is repaid at maturity. Immediate parallel yield shock, no passage of time. This is a teaching bond, not a DI futures contract.",
        "rate_cols": ["Yield shock", "Exact P&L (R$)", "Duration P&L (R$)"],
        "fx_intro": "Illustrative long BRL financed in USD: local interest accrues, USD funding is paid, and the exchange rate determines the USD value. Policy rates are proxies, not executable funding quotes.",
        "br_rate": "BRL annual rate (%)",
        "us_rate": "USD annual funding (%)",
        "days": "Holding period (business days)",
        "fx_shock": "USD/BRL change (%) · positive = weaker real",
        "fx_metrics": ["Rate advantage", "FX-only return", "Return relative to USD cash"],
        "fx_note": "Fixed rates, annual compounding, 252 business days. BRL investment growth divided by USD cash growth, then adjusted for FX; no fees, basis or rollover. A policy-rate gap does not determine a traded forward quote.",
        "producer_intro": "A producer with fixed export volume receives dollars. Stress its BRL revenue and compare an unhedged sale with a share of USD receipts sold forward at an illustrative fixed rate.",
        "revenue": "Baseline export receipts (US$)",
        "spot": "Baseline USD/BRL",
        "commodity_shock": "Commodity price change (%)",
        "hedge": "Share of actual USD receipts hedged (%)",
        "forward": "Illustrative forward rate (BRL per USD)",
        "producer_metrics": ["Baseline BRL revenue", "Unhedged revenue change", "Revenue with FX hedge"],
        "hedge_difference": "Hedge minus unhedged revenue",
        "producer_cols": ["Commodity / USD/BRL", "−5%", "Unchanged", "+5%"],
        "producer_note": "Revenue, not profit. Fixed volume; no costs, commodity hedge or basis risk. Hedge percentage applies to scenario receipts, so the USD hedge notional changes when the commodity price changes. A fixed-notional forward would leave a different residual exposure. The forward input is illustrative, not a quote.",
        "matrix_label": "Unhedged BRL revenue sensitivity",
        "scenario_source": "Default rates are frozen at the research date; changing an input creates your own hypothetical scenario.",
        "download_scenario": "Download this scenario (CSV)",
        "risk_title": "A model should earn your trust.",
        "risk_intro": "I checked three one-day FX risk models against historical losses. Each day uses only returns already available at the previous close. This tests risk calibration, not a trading strategy.",
        "risk_take": "A 99% risk estimate is a threshold, not a worst-case loss.",
        "risk_date": "Research added 7 October 2026 · frozen PTAX through",
        "risk_scope": "Historical evaluation",
        "risk_target": "Target breach rate",
        "risk_cols": ["Model", "Breaches / days", "Breach rate", "Coverage test p-value"],
        "model_names": {"rolling_normal": "Normal · trailing 20 sessions", "ewma_normal": "Normal · EWMA 0.94", "historical": "Empirical · trailing 250 sessions"},
        "risk_note": "Long BRL measured in USD; one-day spot loss, no carry. 99% VaR should be exceeded on about 1% of days under its assumptions. The Kupiec test checks that frequency only: a high p-value does not validate independence or tail severity. Historical walk-forward reconstruction, published after the sample; methods were not prospectively deployed.",
        "tail_title": "Latest model estimates, from frozen data",
        "tail_cols": ["Model", "99% VaR · loss", "99% expected shortfall"],
        "tail_note": "Forecast horizon: next observed session after the saved close. Expected shortfall is the model’s mean loss in its worst 1% tail. These estimates stay frozen when the market tape refreshes.",
        "risk_method": "Assumptions & method",
        "risk_inputs": "Saved source inputs",
        "risk_code": "Python implementation",
        "risk_download": "Download daily forecasts (CSV)",
        "risk_failure": "Risk study unavailable. The dated market research below remains available.",
        "result_label": "Your scenario",
        "error": "This scenario could not be calculated. Check the inputs.",
        "about_lab": "The risk lab connects that research to explicit exposures; the model check compares trailing forecasts with realised losses and preserves every forecast for inspection.",
    },
    "pt": {
        "kicker": "Pesquisa independente / Brasil",
        "intro": "Transformo dados oficiais de mercado em estudos reproduzíveis em Python, testo as premissas e traduzo uma visão em risco de juros, câmbio e commodities.",
        "scope": "Engenharia na EPFL · Juros / Câmbio / Commodities",
        "lab_cta": "Explorar o laboratório de risco",
        "code_cta": "Examinar a pesquisa",
        "reasoning": "Ler os argumentos e as regras de decisão",
        "dated": "Pesquisa datada · não é uma recomendação em tempo real",
        "scope_labels": ["Observações diárias de câmbio", "Meses de commodities", "Eleições concluídas"],
        "scope_note": "Dados salvos. Cálculos reproduzíveis. Nenhum desempenho de trading alegado.",
        "lab_nav": "Laboratório de risco",
        "risk_nav": "Validação dos modelos",
        "lab_title": "Da visão de mercado ao número de risco.",
        "lab_intro": "Mude as premissas. Veja como juros afetam um título, câmbio afeta uma posição financiada em reais e câmbio e commodities afetam um produtor.",
        "lab_modes": ["Juros · DV01", "Câmbio · carry", "Produtor · hedge"],
        "rate_intro": "Um título hipotético sem cupom, avaliado com uma taxa zero datada da ANBIMA. Juros maiores reduzem seu preço; um prazo maior aumenta a sensibilidade.",
        "rate_intro_fallback": "Um título hipotético sem cupom. Taxas disponíveis usam a curva salva da ANBIMA; prazos ausentes partem de um exemplo editável de 13%.",
        "maturity": "Prazo (anos)",
        "principal": "Valor de face (R$)",
        "yield": "Taxa zero anual (%)",
        "rate_shock": "Choque de juros (pontos-base)",
        "rate_metrics": ["Valor presente", "DV01 · R$ por pb", "Variação exata de preço"],
        "rate_detail": "Aproximação pela duração",
        "rate_gap": "Exato menos aproximação",
        "rate_note": "Capitalização anual; 252 dias úteis por ano. O valor de face é pago no vencimento. Choque paralelo imediato, sem passagem do tempo. É um título didático, não um contrato futuro de DI.",
        "rate_cols": ["Choque de juros", "P&L exato (R$)", "P&L por duração (R$)"],
        "fx_intro": "Posição ilustrativa comprada em reais e financiada em dólares: juros locais acumulam, o financiamento em USD é pago e o câmbio determina o valor em dólares. As taxas de política são aproximações, não cotações de financiamento.",
        "br_rate": "Taxa anual em BRL (%)",
        "us_rate": "Financiamento anual em USD (%)",
        "days": "Prazo (dias úteis)",
        "fx_shock": "Variação do USD/BRL (%) · positiva = real mais fraco",
        "fx_metrics": ["Vantagem de juros", "Retorno apenas do câmbio", "Retorno relativo ao caixa em USD"],
        "fx_note": "Taxas fixas, capitalização anual, 252 dias úteis. Crescimento do investimento em BRL dividido pelo crescimento do caixa em USD, ajustado pelo câmbio; sem tarifas, basis ou rolagem. O diferencial de política monetária não determina uma cotação a termo negociada.",
        "producer_intro": "Um produtor com volume exportado fixo recebe dólares. Teste sua receita em reais e compare uma venda sem hedge com parte dos recebimentos em USD vendida a termo a uma taxa fixa ilustrativa.",
        "revenue": "Recebimentos-base de exportação (US$)",
        "spot": "USD/BRL de referência",
        "commodity_shock": "Variação do preço da commodity (%)",
        "hedge": "Parcela dos recebimentos efetivos em USD com hedge (%)",
        "forward": "Taxa a termo ilustrativa (BRL por USD)",
        "producer_metrics": ["Receita-base em BRL", "Variação da receita sem hedge", "Receita com hedge cambial"],
        "hedge_difference": "Receita com hedge menos receita sem hedge",
        "producer_cols": ["Commodity / USD/BRL", "−5%", "Sem mudança", "+5%"],
        "producer_note": "Receita, não lucro. Volume fixo; sem custos, hedge da commodity ou risco de basis. A parcela com hedge incide sobre os recebimentos do cenário, então o nocional em USD muda com o preço da commodity. Um termo de nocional fixo deixaria outra exposição residual. A taxa a termo é ilustrativa, não uma cotação.",
        "matrix_label": "Sensibilidade da receita em BRL sem hedge",
        "scenario_source": "As taxas iniciais estão congeladas na data da pesquisa; alterar um campo cria seu próprio cenário hipotético.",
        "download_scenario": "Baixar este cenário (CSV)",
        "risk_title": "Um modelo precisa merecer confiança.",
        "risk_intro": "Comparei três modelos de risco cambial de um dia com perdas históricas. Cada dia usa apenas retornos disponíveis no fechamento anterior. É um teste de calibração do risco, não de uma estratégia de trading.",
        "risk_take": "Uma estimativa de risco de 99% é um limite, não a perda máxima possível.",
        "risk_date": "Pesquisa adicionada em 7 de outubro de 2026 · PTAX congelada até",
        "risk_scope": "Avaliação histórica",
        "risk_target": "Taxa-alvo de violações",
        "risk_cols": ["Modelo", "Violações / dias", "Taxa de violações", "Valor-p do teste de cobertura"],
        "model_names": {"rolling_normal": "Normal · 20 sessões anteriores", "ewma_normal": "Normal · EWMA 0,94", "historical": "Empírico · 250 sessões anteriores"},
        "risk_note": "Posição comprada em BRL medida em USD; perda à vista de um dia, sem carry. Sob suas premissas, o VaR de 99% deve ser excedido em cerca de 1% dos dias. O teste de Kupiec avalia apenas essa frequência: um valor-p alto não valida independência ou gravidade da cauda. Reconstrução histórica publicada após a amostra; os métodos não foram operados prospectivamente.",
        "tail_title": "Últimas estimativas dos modelos, com dados congelados",
        "tail_cols": ["Modelo", "VaR de 99% · perda", "Expected shortfall de 99%"],
        "tail_note": "Horizonte: próxima sessão observada após o fechamento salvo. Expected shortfall é a perda média na pior cauda de 1% do modelo. Estas estimativas ficam congeladas quando o painel de mercado é atualizado.",
        "risk_method": "Premissas e método",
        "risk_inputs": "Dados-fonte salvos",
        "risk_code": "Implementação em Python",
        "risk_download": "Baixar previsões diárias (CSV)",
        "risk_failure": "Estudo de risco indisponível. A pesquisa de mercado datada continua disponível abaixo.",
        "result_label": "Seu cenário",
        "error": "Não foi possível calcular este cenário. Confira os campos.",
        "about_lab": "O laboratório de risco conecta a pesquisa a exposições explícitas; a avaliação dos modelos compara previsões anteriores com perdas realizadas e preserva cada previsão para consulta.",
    },
    "fr": {
        "kicker": "Recherche indépendante / Brésil",
        "intro": "Je transforme les données officielles de marché en études Python reproductibles, teste les hypothèses et traduis une vue en risques de taux, de change et de matières premières.",
        "scope": "Ingénierie à l’EPFL · Taux / Change / Matières premières",
        "lab_cta": "Explorer le laboratoire de risque",
        "code_cta": "Examiner la recherche",
        "reasoning": "Lire le raisonnement et les règles de décision",
        "dated": "Recherche datée · pas une recommandation en temps réel",
        "scope_labels": ["Observations de change quotidiennes", "Mois de matières premières", "Élections terminées"],
        "scope_note": "Données conservées. Calculs reproductibles. Aucune performance de trading revendiquée.",
        "lab_nav": "Laboratoire de risque",
        "risk_nav": "Validation des modèles",
        "lab_title": "De la vue de marché au chiffre de risque.",
        "lab_intro": "Modifiez les hypothèses. Voyez l’effet des taux sur une obligation, du change sur une position en real financée, et du change et des matières premières sur un producteur.",
        "lab_modes": ["Taux · DV01", "Change · carry", "Producteur · couverture"],
        "rate_intro": "Une obligation zéro-coupon hypothétique, valorisée avec un taux zéro daté d’ANBIMA. Un taux plus élevé réduit son prix ; une échéance plus longue augmente sa sensibilité.",
        "rate_intro_fallback": "Une obligation zéro-coupon hypothétique. Les taux disponibles viennent de la courbe ANBIMA conservée ; les échéances absentes partent d’un exemple modifiable de 13 %.",
        "maturity": "Échéance (années)",
        "principal": "Valeur nominale (R$)",
        "yield": "Taux zéro annuel (%)",
        "rate_shock": "Choc de taux (points de base)",
        "rate_metrics": ["Valeur actuelle", "DV01 · R$ par pb", "Variation exacte du prix"],
        "rate_detail": "Approximation par la duration",
        "rate_gap": "Exact moins approximation",
        "rate_note": "Capitalisation annuelle ; 252 jours ouvrés par an. Le nominal est remboursé à l’échéance. Choc parallèle immédiat, sans écoulement du temps. Il s’agit d’une obligation pédagogique, pas d’un future DI.",
        "rate_cols": ["Choc de taux", "P&L exact (R$)", "P&L par duration (R$)"],
        "fx_intro": "Position illustrative longue en BRL financée en USD : les intérêts locaux s’accumulent, le financement USD est payé et le change détermine la valeur en dollars. Les taux directeurs sont des approximations, pas des cotations de financement.",
        "br_rate": "Taux annuel BRL (%)",
        "us_rate": "Financement annuel USD (%)",
        "days": "Durée (jours ouvrés)",
        "fx_shock": "Variation USD/BRL (%) · positive = real plus faible",
        "fx_metrics": ["Avantage de taux", "Rendement du change seul", "Rendement relatif au cash USD"],
        "fx_note": "Taux fixes, capitalisation annuelle, 252 jours ouvrés. Croissance de l’investissement BRL divisée par celle du cash USD, puis ajustée du change ; sans frais, basis ni renouvellement. L’écart de taux directeurs ne détermine pas une cotation à terme négociée.",
        "producer_intro": "Un producteur à volume d’exportation fixe reçoit des dollars. Testez son revenu en BRL et comparez une vente sans couverture avec une part des recettes USD vendue à terme à un taux fixe illustratif.",
        "revenue": "Recettes d’exportation de référence (US$)",
        "spot": "USD/BRL de référence",
        "commodity_shock": "Variation du prix de la matière première (%)",
        "hedge": "Part des recettes USD effectives couverte (%)",
        "forward": "Taux à terme illustratif (BRL par USD)",
        "producer_metrics": ["Revenu BRL de référence", "Variation sans couverture", "Revenu avec couverture FX"],
        "hedge_difference": "Revenu couvert moins revenu non couvert",
        "producer_cols": ["Matière première / USD/BRL", "−5%", "Inchangé", "+5%"],
        "producer_note": "Revenu, pas bénéfice. Volume fixe ; sans coûts, couverture de la matière première ni risque de basis. La part couverte porte sur les recettes du scénario : le nominal USD varie donc avec le prix. Un contrat à nominal fixe laisserait une autre exposition résiduelle. Le taux à terme est illustratif, pas une cotation.",
        "matrix_label": "Sensibilité du revenu BRL sans couverture",
        "scenario_source": "Les taux initiaux sont figés à la date de recherche ; modifier un champ crée votre propre scénario hypothétique.",
        "download_scenario": "Télécharger ce scénario (CSV)",
        "risk_title": "Un modèle doit mériter votre confiance.",
        "risk_intro": "J’ai confronté trois modèles de risque de change à un jour aux pertes historiques. Chaque jour utilise uniquement les rendements disponibles à la clôture précédente. Il s’agit de calibration du risque, pas d’une stratégie de trading.",
        "risk_take": "Une estimation de risque à 99% est un seuil, pas une perte maximale.",
        "risk_date": "Recherche ajoutée le 7 octobre 2026 · PTAX figée jusqu’au",
        "risk_scope": "Évaluation historique",
        "risk_target": "Fréquence de dépassement cible",
        "risk_cols": ["Modèle", "Dépassements / jours", "Fréquence", "Valeur-p du test de couverture"],
        "model_names": {"rolling_normal": "Normale · 20 séances précédentes", "ewma_normal": "Normale · EWMA 0,94", "historical": "Empirique · 250 séances précédentes"},
        "risk_note": "Position longue BRL mesurée en USD ; perte au comptant à un jour, sans carry. Sous ses hypothèses, la VaR à 99% devrait être dépassée environ 1% du temps. Le test de Kupiec vérifie cette fréquence seule : une valeur-p élevée ne valide ni l’indépendance ni la gravité des pertes extrêmes. Reconstruction historique publiée après l’échantillon ; méthodes non déployées prospectivement.",
        "tail_title": "Dernières estimations, sur données figées",
        "tail_cols": ["Modèle", "VaR à 99% · perte", "Expected shortfall à 99%"],
        "tail_note": "Horizon : séance observée suivant la clôture conservée. L’expected shortfall est la perte moyenne dans la pire queue de 1% du modèle. Ces estimations restent figées lors de l’actualisation du marché.",
        "risk_method": "Hypothèses et méthode",
        "risk_inputs": "Données sources conservées",
        "risk_code": "Implémentation Python",
        "risk_download": "Télécharger les prévisions quotidiennes (CSV)",
        "risk_failure": "Étude de risque indisponible. La recherche de marché datée reste disponible ci-dessous.",
        "result_label": "Votre scénario",
        "error": "Ce scénario n’a pas pu être calculé. Vérifiez les champs.",
        "about_lab": "Le laboratoire de risque relie la recherche à des expositions explicites ; la validation compare les prévisions antérieures aux pertes réalisées et conserve chaque prévision pour examen.",
    },
}
TEXT["fr"] = _french_typography(TEXT["fr"])
