from __future__ import annotations


UI_FR = {
    "Brazil rates / FX / commodities": "Taux brésiliens / change / commodities",
    "Brazil macro, from policy to price.": "Le Brésil, de la politique monétaire aux marchés.",
    "A clear view of what Brazilian interest rates, U.S. rates and export prices could mean for the real.": "Une lecture claire de ce que les taux brésiliens, les taux américains et les prix à l'exportation peuvent signifier pour le real.",
    "Brazil interest rate": "Taux d'intérêt au Brésil",
    "Selic target": "Taux directeur Selic",
    "One U.S. dollar": "Un dollar américain",
    "Brazilian reais": "reals brésiliens",
    "Brazil's rate lead": "Avantage de taux du Brésil",
    "above the U.S.": "au-dessus des États-Unis",
    "pp": "pt",
    "U.S. two-year rate": "Taux américain à deux ans",
    "government bond": "obligation d'État",
    "The short version": "En bref",
    "What I expect, why it matters, when I would act and when I would admit the idea is wrong.": "Ce que j'anticipe, pourquoi cela compte, quand j'agirais et quand je reconnaîtrais que l'idée est fausse.",
    "1 / Starting point": "1 / Point de départ",
    "BRAZIL CUTS / U.S. RAISES": "LE BRÉSIL BAISSE / LES ÉTATS-UNIS MONTENT",
    "Markets currently point to a small Brazilian rate cut and a small U.S. rate increase.": "Les marchés anticipent actuellement une légère baisse des taux brésiliens et une légère hausse des taux américains.",
    "2 / Market mechanism": "2 / Mécanisme de marché",
    "THE REAL LOSES SOME SUPPORT": "LE REAL PERD UNE PARTIE DE SON SOUTIEN",
    "3 / Confirmation": "3 / Confirmation",
    "I would buy dollars against reais only after USD/BRL breaks above its recent range.": "Je n'achèterais des dollars contre des reals qu'après une sortie de l'USD/BRL au-dessus de sa fourchette récente.",
    "4 / Risk control": "4 / Gestion du risque",
    "I would abandon the idea if the price move fails or Brazil keeps its rate lead.": "J'abandonnerais l'idée si le mouvement de prix échoue ou si le Brésil conserve son avantage de taux.",
    "The saved decision frame is temporarily unavailable.": "Le cadre de décision enregistré est temporairement indisponible.",
    "Why these numbers matter": "Pourquoi ces chiffres comptent",
    "Rates": "Taux",
    "Currency": "Change",
    "Inflation": "Inflation",
    "Commodities": "Commodities",
    "Oil, iron ore, soybeans and sugar affect Brazil's export income and therefore help shape the outlook for the real and inflation.": "Le pétrole, le minerai de fer, le soja et le sucre influencent les recettes d'exportation du Brésil et, par conséquent, les perspectives du real et de l'inflation.",
    "The saved market snapshot is temporarily unavailable.": "L'instantané de marché enregistré est temporairement indisponible.",
    "Why interest rates matter for the real": "Pourquoi les taux comptent pour le real",
    "Brazil–U.S. rate gap": "Écart de taux Brésil–États-Unis",
    "The simple link": "Le lien, simplement",
    "Brazil pays much higher interest than the U.S. That can support the real because investors earn more by holding Brazilian assets. The trade-off is that rates are high because inflation is still uncomfortable.": "Le Brésil offre des taux bien plus élevés que les États-Unis. Cela peut soutenir le real, car les investisseurs sont davantage rémunérés pour détenir des actifs brésiliens. En contrepartie, ces taux élevés reflètent une inflation encore préoccupante.",
    "The saved Focus survey shows 2026 inflation expectations easing over the latest month, but still above the central bank's target.": "L'enquête Focus enregistrée montre un recul des anticipations d'inflation pour 2026 sur le dernier mois, mais elles restent supérieures à l'objectif de la banque centrale.",
    "What economists expect next": "Ce que les économistes anticipent",
    "FORECAST": "PRÉVISION",
    "What markets expect in September": "Ce que les marchés anticipent en septembre",
    "Brazil / B3 interest-rate futures": "Brésil / contrats à terme de taux B3",
    "Close to a 0.25-point cut": "Près d'une baisse de 0,25 point",
    "This estimate comes from market prices around Brazil's September central-bank meeting.": "Cette estimation provient des prix de marché autour de la réunion de septembre de la banque centrale brésilienne.",
    "United States / CME FedWatch": "États-Unis / CME FedWatch",
    "CME's official tool gave this outcome the highest weight in the saved observation.": "L'outil officiel de la CME accordait le poids le plus élevé à ce résultat dans l'observation enregistrée.",
    "The real against the dollar": "Le real face au dollar",
    "Official reference": "Référence officielle",
    "What changed": "Ce qui a changé",
    "Where USD/BRL sits in its recent range": "Position de l'USD/BRL dans sa fourchette récente",
    "PTAX range / saved observations": "Fourchette PTAX / observations enregistrées",
    "LOW": "BAS",
    "CURRENT": "ACTUEL",
    "HIGH": "HAUT",
    "Brazil's export backdrop": "Le contexte des exportations brésiliennes",
    "Brazil earns dollars by exporting products such as oil, iron ore, soybeans and sugar. Their prices can therefore affect the real, company earnings and inflation.": "Le Brésil reçoit des dollars en exportant du pétrole, du minerai de fer, du soja et du sucre. Leurs prix peuvent donc influencer le real, les bénéfices des entreprises et l'inflation.",
    "External channel": "Canal externe",
    "Commodity cross-check for the trade": "Vérification de l'idée par les commodities",
    "Higher export prices can help the real—but the inflation channel can push the other way.": "Des prix d'exportation plus élevés peuvent soutenir le real, mais leur effet sur l'inflation peut agir en sens inverse.",
    "External support": "Soutien externe",
    "Broad, sustained strength in oil, iron ore, soy and sugar can increase export dollars and support BRL.": "Une hausse large et durable du pétrole, du minerai de fer, du soja et du sucre peut accroître les recettes en dollars et soutenir le real.",
    "Inflation tension": "Pression inflationniste",
    "Oil, food and ethanol channels can raise domestic prices, making faster BCB rate cuts less likely.": "Le pétrole, l'alimentation et l'éthanol peuvent faire monter les prix intérieurs et rendre des baisses rapides de taux moins probables.",
    "Global demand": "Demande mondiale",
    "Iron ore and soy also reveal demand conditions—especially in China—that can outweigh the rate story.": "Le minerai de fer et le soja renseignent aussi sur la demande mondiale, notamment chinoise, qui peut dominer l'effet des taux.",
    "Trade implication: ": "Conséquence pour l'idée : ",
    "A broad commodity rally would weaken the long-USD/short-BRL case. Falling export prices alongside firm U.S. yields would strengthen it. Mixed signals reinforce the decision to wait for USD/BRL confirmation.": "Une hausse généralisée des commodities affaiblirait l'idée d'achat de dollars contre le real. Des prix d'exportation en baisse et des taux américains fermes la renforceraient. Des signaux mitigés justifient d'attendre une confirmation de l'USD/BRL.",
    "The saved commodity snapshot is temporarily unavailable.": "L'instantané des commodities est temporairement indisponible.",
    "From a commodity move to an investment case": "Du mouvement d'une commodity à une thèse d'investissement",
    "A commodity price move is only the starting point. Before judging a producer as an investment, I would test how much of that move reaches its revenue, margins, cash flow and valuation.": "Le mouvement du prix d'une commodity n'est qu'un point de départ. Avant d'évaluer un producteur, j'examinerais dans quelle mesure ce mouvement atteint son chiffre d'affaires, ses marges, sa trésorerie et sa valorisation.",
    "1 / Revenue exposure": "1 / Exposition du chiffre d'affaires",
    "What does the company actually sell?": "Que vend réellement l'entreprise ?",
    "Check production volumes, product mix, realized prices, hedging and the currencies in which revenue is earned.": "Examiner les volumes produits, le mix de produits, les prix réalisés, les couvertures et les devises dans lesquelles les revenus sont perçus.",
    "2 / Margin and cost curve": "2 / Marges et courbe de coûts",
    "Does a higher price become higher profit?": "Une hausse du prix devient-elle une hausse du bénéfice ?",
    "Compare operating costs, energy and freight exposure, FX sensitivity and the producer's position on the industry cost curve.": "Comparer les coûts d'exploitation, l'exposition à l'énergie et au fret, la sensibilité au change et la position du producteur sur la courbe de coûts du secteur.",
    "3 / Balance sheet": "3 / Bilan",
    "Can the company use the cash well?": "L'entreprise utilise-t-elle bien sa trésorerie ?",
    "Review leverage, liquidity, capital spending and the discipline behind dividends, buybacks and new projects.": "Étudier l'endettement, la liquidité, les investissements et la discipline qui guide les dividendes, rachats d'actions et nouveaux projets.",
    "4 / Valuation and decision": "4 / Valorisation et décision",
    "Is the opportunity already in the price?": "L'opportunité est-elle déjà intégrée dans le prix ?",
    "Value the business under normalized and downside assumptions, then identify the catalyst and the evidence that would invalidate the thesis.": "Valoriser l'entreprise avec des hypothèses normales et défavorables, puis identifier le catalyseur et les éléments qui invalideraient la thèse.",
    "Research discipline: ": "Discipline d'analyse : ",
    "The dashboard identifies macro and commodity signals; a stock recommendation would still require company filings, management evidence, competitive analysis and a valuation with a margin of safety.": "Le tableau de bord repère des signaux macroéconomiques et liés aux commodities ; une recommandation d'action exigerait encore l'étude des publications de l'entreprise, de sa direction, de la concurrence et une valorisation offrant une marge de sécurité.",
    "Three ways the September meetings could go": "Trois scénarios pour les réunions de septembre",
    "Three simple stories: Brazil stays tougher, follows the expected path or cuts faster.": "Trois scénarios simples : le Brésil reste plus restrictif, suit les attentes ou baisse ses taux plus vite.",
    "Brazil stays tougher": "Le Brésil reste plus restrictif",
    "The real would probably strengthen": "Le real se renforcerait probablement",
    "Most expected path": "Scénario le plus attendu",
    "The real would probably weaken slightly": "Le real s'affaiblirait probablement légèrement",
    "Brazil cuts faster": "Le Brésil baisse ses taux plus vite",
    "The real would probably weaken more": "Le real s'affaiblirait probablement davantage",
    "Likely unchanged near 10.38 pp": "Probablement stable près de 10,38 points",
    "Likely narrows 50 bp to 9.88 pp": "Baisse probable de 0,50 point à 9,88 points",
    "Likely narrows 75 bp to 9.63 pp": "Baisse probable de 0,75 point à 9,63 points",
    "Scenario": "Scénario",
    "Brazil-US differential": "Écart Brésil–États-Unis",
    "Likely initial FX pressure": "Effet initial probable sur le change",
    "Confirmation": "Confirmation",
    "See the exact decisions, evidence and risks": "Voir les décisions, éléments de confirmation et risques",
    "**Policy path**": "**Trajectoire des taux**",
    "Unavailable": "Indisponible",
    "**Why it differs from pricing**": "**Pourquoi ce scénario diffère des prix de marché**",
    "**What should confirm it**": "**Ce qui devrait le confirmer**",
    "**Principal risk**": "**Risque principal**",
    "The saved three-scenario comparison is temporarily unavailable.": "La comparaison des trois scénarios est temporairement indisponible.",
    "What the numbers cannot decide": "Ce que les chiffres ne peuvent pas décider seuls",
    "What is already priced": "Ce qui est déjà intégré dans les prix",
    "A small Brazilian cut and a small U.S. increase are already expected. The reaction depends on the surprise, not only the decision.": "Une légère baisse au Brésil et une légère hausse aux États-Unis sont déjà attendues. La réaction dépend de la surprise, pas seulement de la décision.",
    "Policy tone": "Ton des banques centrales",
    "Guidance about what comes next can matter more than the rate change announced on the day.": "Les indications sur la suite peuvent compter davantage que le changement de taux annoncé le jour même.",
    "News that can overpower it": "Informations pouvant dominer le scénario",
    "Brazilian fiscal news, U.S. inflation and jobs data, export prices and global risk appetite can reverse the currency move.": "Les nouvelles budgétaires brésiliennes, l'inflation et l'emploi américains, les prix à l'exportation et l'appétit mondial pour le risque peuvent inverser le mouvement de change.",
    "Why price confirmation matters": "Pourquoi attendre une confirmation du prix",
    "Waiting for USD/BRL to break its recent range tests whether the market agrees before taking the risk.": "Attendre que l'USD/BRL sorte de sa fourchette récente permet de vérifier si le marché confirme l'idée avant de prendre le risque.",
    "A paper trade - only if the market confirms it": "Une opération simulée - uniquement si le marché la confirme",
    "Conditional / no position at snapshot": "Conditionnelle / aucune position à la date des données",
    "If Brazil cuts interest rates while the U.S. raises them, holding reais becomes slightly less attractive. Because much of that path is already expected, I would act only if price confirms it; fiscal news, export prices and global risk can still dominate.": "Si le Brésil baisse ses taux pendant que les États-Unis les relèvent, détenir des reals devient légèrement moins attractif. Comme ce scénario est déjà largement attendu, je n'agirais que si le prix le confirme ; les nouvelles budgétaires, les prix à l'exportation et le risque mondial peuvent encore dominer.",
    "Wait for confirmation": "Attendre la confirmation",
    "Admit it is wrong": "Reconnaître que l'idée est fausse",
    "Reassess the reward": "Réévaluer le potentiel",
    "Why September matters": "Pourquoi septembre compte",
    "Brazil's and the U.S. central banks announce their decisions on the same two days, creating a clear test of the idea.": "Les banques centrales du Brésil et des États-Unis annoncent leurs décisions pendant les mêmes deux jours, offrant un test clair de l'idée.",
    "Educational exercise only: no real money, no claimed performance and no position at the saved snapshot.": "Exercice pédagogique uniquement : aucun argent réel, aucune performance revendiquée et aucune position à la date des données.",
    "#### Why the idea is plausible": "#### Pourquoi l'idée est plausible",
    "The dollar rose about 1.6% against the real over the latest month in the saved data.": "Le dollar a progressé d'environ 1,6 % face au real sur le dernier mois des données enregistrées.",
    "Brazil's interest-rate lead over the U.S. already narrowed by 0.25 percentage point.": "L'avantage de taux du Brésil sur les États-Unis s'est déjà réduit de 0,25 point.",
    "If the expected September decisions happen, that lead narrows by another 0.50 point.": "Si les décisions attendues en septembre se réalisent, cet avantage se réduit encore de 0,50 point.",
    "#### Catalyst": "#### Catalyseur",
    "The Brazilian and U.S. central-bank decisions on 15-16 September.": "Les décisions des banques centrales brésilienne et américaine des 15 et 16 septembre.",
    "#### What could go wrong": "#### Ce qui pourrait mal tourner",
    "Brazil keeps rates unchanged or signals that high rates will last longer.": "Le Brésil maintient ses taux ou indique qu'ils resteront élevés plus longtemps.",
    "The U.S. does not raise rates or signals lower rates ahead.": "Les États-Unis ne relèvent pas leurs taux ou annoncent de futures baisses.",
    "Better fiscal news, stronger exports or a global rally strengthens the real instead.": "De meilleures nouvelles budgétaires, des exportations plus fortes ou une hausse mondiale renforcent le real.",
    "What would make me change my mind": "Ce qui me ferait changer d'avis",
    "See the calculations and full trade rules": "Voir les calculs et toutes les règles de l'opération",
    "**Original thesis**": "**Thèse initiale**",
    "**Entry rule**": "**Règle d'entrée**",
    "**Invalidation rule**": "**Règle d'invalidation**",
    "**Review-zone calculation**": "**Calcul de la zone de réévaluation**",
    "The saved conditional paper trade is temporarily unavailable.": "L'opération simulée enregistrée est temporairement indisponible.",
    "Download the one-page market brief (PDF)": "Télécharger la note de marché d'une page (PDF)",
    "How I approached the question": "Ma méthode",
    "Start with public evidence. Compare a few plausible outcomes. Form one view. Decide what would prove it wrong before acting. The calculations come afterward so anyone can check the reasoning.": "Partir de données publiques. Comparer quelques scénarios plausibles. Formuler une idée. Définir avant d'agir ce qui prouverait qu'elle est fausse. Les calculs viennent ensuite pour rendre le raisonnement vérifiable.",
    "market series": "séries de marché",
    "export benchmarks": "références d'exportation",
    "decision scenarios": "scénarios",
    "conditional trade": "opération conditionnelle",
    "01 / Evidence": "01 / Données",
    "Use primary sources": "Utiliser des sources primaires",
    "Start with central-bank and exchange data, and keep every date visible.": "Commencer par les données des banques centrales et des marchés, en gardant chaque date visible.",
    "02 / Scenarios": "02 / Scénarios",
    "Separate the paths": "Distinguer les scénarios",
    "Ask what changes if Brazil stays tougher, follows expectations or cuts faster.": "Demander ce qui change si le Brésil reste plus restrictif, suit les attentes ou baisse ses taux plus vite.",
    "03 / Decision": "03 / Décision",
    "Set the entry, exit and risks before any trade would begin.": "Définir l'entrée, la sortie et les risques avant toute opération.",
    "04 / Challenge": "04 / Mise à l'épreuve",
    "Try to break it": "Chercher à réfuter l'idée",
    "Check the numbers, test the rules and keep the page working when a data feed fails.": "Vérifier les chiffres, tester les règles et garder la page fonctionnelle lorsqu'une source de données échoue.",
    "Project author": "Auteur du projet",
    "EPFL Mechanical Engineering student based between São Paulo and Lausanne. I built this project to show how I approach an ambiguous market question: find primary data, separate expectations from outcomes, trace commodity signals into company-level questions and state in advance what would prove a view wrong. Every conclusion is linked to evidence and a rule another reader can check.": "Étudiant en génie mécanique à l'EPFL, entre São Paulo et Lausanne. J'ai créé ce projet pour montrer comment j'aborde une question de marché incertaine : trouver les données primaires, distinguer les attentes des résultats, relier les signaux des commodities aux entreprises et définir à l'avance ce qui réfuterait une idée. Chaque conclusion repose sur des données et une règle vérifiable.",
    "Inspect the code": "Voir le code",
    "LinkedIn profile": "Profil LinkedIn",
    "Data and method": "Données et méthode",
    "For readers who want to check the work: the page uses a saved copy of public data so it can be reproduced even when a source is temporarily unavailable. Commodity observations keep their real publication dates rather than being forced into a false like-for-like index.": "Pour vérifier le travail : la page utilise une copie enregistrée de données publiques afin de rester reproductible lorsqu'une source est temporairement indisponible. Les observations sur les commodities conservent leurs véritables dates de publication au lieu d'être forcées dans un indice artificiellement comparable.",
    "See source": "Voir la source",
    "source": "source",
    "Official source links": "Sources officielles",
    "Official source": "Source officielle",
    "Commodity source": "Source de la commodity",
    "Official source links are temporarily unavailable.": "Les liens vers les sources officielles sont temporairement indisponibles.",
}


SCENARIO_FR = {
    "Hawkish relative to expectations": {
        "name": "Plus restrictif que prévu",
        "copom_outcome_and_guidance": "La banque centrale brésilienne maintient le taux Selic à 14,00 % et souligne que de nouvelles baisses exigent une amélioration plus nette des anticipations d'inflation.",
        "fomc_outcome_and_guidance": "La Réserve fédérale maintient sa fourchette à 3,50 %-3,75 % au lieu de relever les taux, tout en conservant un ton ferme sur l'inflation.",
        "difference_from_current_expectations": "Le maintien au Brésil est plus restrictif que la baisse d'environ 0,22 point intégrée dans les prix de marché. Le maintien américain est plus accommodant que la hausse de 0,25 point privilégiée par l'observation CME. Ensemble, ils laissent l'écart de taux 0,50 point au-dessus du scénario central.",
        "confirmation_signals": [
            "La prévision médiane du taux Selic pour 2026 remonte de 13,75 % vers 14,00 %.",
            "L'USD/BRL passe sous environ 5,09 tandis que le taux américain à deux ans recule depuis 4,34 %.",
        ],
        "principal_risk": "Une aversion mondiale au risque ou un choc sur les prix des commodities pourrait affaiblir le real malgré un écart de taux plus favorable.",
        "brief_summary": {
            "copom": "Maintien à 14,00 % ; ton restrictif",
            "fomc": "Maintien à 3,50 %-3,75 % ; ton ferme",
            "differential": "Resterait proche de 10,38 points",
            "brl_usd_pressure": "Hausse probable du real / baisse de l'USD/BRL",
            "confirmation": "Selic attendu vers 14,00 % ; USD/BRL sous 5,09 et taux américain à deux ans en baisse",
        },
    },
    "Base case": {
        "name": "Scénario central",
        "copom_outcome_and_guidance": "La banque centrale brésilienne baisse le taux de 0,25 point à 13,75 %, conformément à la prévision médiane pour 2026, et conserve un ton prudent.",
        "fomc_outcome_and_guidance": "La Réserve fédérale relève sa fourchette de 0,25 point à 3,75 %-4,00 % et souligne que les décisions suivantes dépendront de l'inflation et de l'emploi.",
        "difference_from_current_expectations": "La baisse brésilienne de 0,25 point est proche de celle intégrée dans les prix de marché. La hausse américaine de 0,25 point est le résultat auquel l'observation CME accordait le poids le plus élevé. Aucune probabilité conjointe n'est déduite.",
        "confirmation_signals": [
            "Les taux directeurs passent à 13,75 % au Brésil et à un point médian de 3,875 % aux États-Unis, soit un écart proche de 9,88 points.",
            "L'USD/BRL clôture au-dessus d'environ 5,22 tandis que le taux américain à deux ans reste proche ou au-dessus de 4,34 %.",
        ],
        "principal_risk": "Les deux décisions peuvent déjà être intégrées dans les prix, laissant le budget brésilien, les commodities ou l'appétit mondial pour le risque dominer le change.",
        "brief_summary": {
            "copom": "Baisse de 0,25 point à 13,75 % ; prudent",
            "fomc": "Hausse de 0,25 point à 3,75 %-4,00 %",
            "differential": "Baisse de 0,50 point à 9,88 points",
            "brl_usd_pressure": "Baisse probable du real / hausse de l'USD/BRL",
            "confirmation": "Écart proche de 9,88 points ; USD/BRL au-dessus de 5,22 et taux américain ferme",
        },
    },
    "Dovish relative to expectations": {
        "name": "Plus accommodant que prévu",
        "copom_outcome_and_guidance": "La banque centrale brésilienne baisse le taux de 0,50 point à 13,50 % et indique que d'autres baisses graduelles sont possibles si les anticipations d'inflation continuent de s'améliorer.",
        "fomc_outcome_and_guidance": "La Réserve fédérale relève sa fourchette de 0,25 point à 3,75 %-4,00 % et conserve un ton ferme face à une inflation encore élevée.",
        "difference_from_current_expectations": "La baisse brésilienne de 0,50 point dépasse d'environ 0,28 point celle intégrée dans les prix de marché et termine sous la prévision médiane du Selic pour 2026. Avec la hausse américaine attendue, le résultat est plus accommodant pour le Brésil.",
        "confirmation_signals": [
            "La prévision médiane du Selic pour 2026 passe sous 13,75 % sans hausse de la prévision d'inflation.",
            "L'USD/BRL dépasse environ 5,22 et le taux américain à deux ans monte depuis 4,34 %.",
        ],
        "principal_risk": "Une baisse plus forte peut être interprétée comme une erreur de politique, accroître la prime de risque et faire monter les taux courts brésiliens.",
        "brief_summary": {
            "copom": "Baisse de 0,50 point à 13,50 %",
            "fomc": "Hausse de 0,25 point à 3,75 %-4,00 %",
            "differential": "Baisse de 0,75 point à 9,63 points",
            "brl_usd_pressure": "Baisse probable du real / hausse de l'USD/BRL",
            "confirmation": "Selic attendu sous 13,75 % ; USD/BRL au-dessus de 5,22 et taux américain en hausse",
        },
    },
}


TRADE_FR = {
    "thesis": "N'envisager l'opération qu'après une hausse confirmée de l'USD/BRL : le scénario central réduit l'avantage de taux du Brésil et les mouvements récents vont dans la même direction.",
    "entry_logic": "Aucune position à 5,1567. Envisager l'opération simulée uniquement après une clôture quotidienne de l'USD/BRL au-dessus d'environ 5,22, avec le taux américain à deux ans proche ou au-dessus de 4,34 %.",
    "invalidation_condition": "Après l'entrée, abandonner l'idée après deux observations quotidiennes consécutives sous environ 5,16, ou si l'écart de taux entre le Brésil et les États-Unis ne diminue pas.",
    "profit_taking_logic": "Le calcul de l'amplitude récente donne 5,3561 ; utiliser 5,35-5,36 comme zone de réévaluation, pas comme objectif garanti, et revoir l'idée plus tôt si les taux ou les nouvelles données changent.",
}


COMMODITY_FR = {
    "brent": {
        "label": "Pétrole",
        "benchmark": "Pétrole brut Brent",
        "frequency": "Quotidienne",
        "signal": "en hausse",
        "channel": "Le Brésil est un grand producteur de pétrole : son prix influence les recettes d'exportation et les revenus des producteurs, tandis que les carburants peuvent aussi affecter l'inflation intérieure.",
    },
    "iron_ore": {
        "label": "Minerai de fer",
        "benchmark": "Prix mondial du minerai de fer - FMI",
        "frequency": "Mensuelle",
        "signal": "en baisse",
        "channel": "Le minerai de fer est une exportation majeure du Brésil. La demande mondiale peut donc modifier les recettes en dollars et le contexte extérieur du real.",
    },
    "soybeans": {
        "label": "Soja",
        "benchmark": "Prix mondial du soja - FMI",
        "frequency": "Trimestrielle",
        "signal": "en hausse",
        "channel": "Les exportations de soja génèrent d'importantes recettes en devises pour le Brésil, avec des flux influencés par la récolte et la saison d'exportation.",
    },
    "sugar": {
        "label": "Sucre",
        "benchmark": "Prix mondial du sucre no 11 - FMI",
        "frequency": "Mensuelle",
        "signal": "en hausse",
        "channel": "Les producteurs brésiliens peuvent orienter la canne vers le sucre ou l'éthanol, reliant ainsi le marché d'exportation à l'économie intérieure des carburants.",
    },
}


SERIES_FR = {
    "focus_selic": ("Prévision médiane du taux Selic annuel", "% par an"),
    "focus_ipca": ("Prévision médiane de l'inflation annuelle", "% par an"),
    "ptax_usd_brl_midpoint": ("Taux de référence USD/BRL PTAX", "reals par dollar"),
    "selic_target": ("Taux directeur Selic", "% par an"),
    "fed_target_range": ("Fourchette des taux américains et point médian calculé", "% par an"),
    "brazil_us_policy_differential": ("Selic moins le point médian des taux américains", "points de pourcentage"),
    "us_2_year_treasury": ("Taux de l'obligation américaine à deux ans", "% par an"),
    "us_10_year_treasury": ("Taux de l'obligation américaine à dix ans", "% par an"),
}


SOURCE_FR = {
    "BCB 2026 Copom calendar": "Calendrier 2026 de la banque centrale brésilienne",
    "BCB August 2026 Copom statement": "Communiqué d'août 2026 de la banque centrale brésilienne",
    "BCB August 2026 Copom minutes": "Compte rendu d'août 2026 de la banque centrale brésilienne",
    "BCB Focus Expectations OData": "Enquête Focus - banque centrale brésilienne",
    "BCB PTAX OData": "Taux PTAX - banque centrale brésilienne",
    "BCB SGS 432 Selic target": "Taux Selic, série SGS 432 - banque centrale brésilienne",
    "Federal Reserve 2026 FOMC calendar": "Calendrier 2026 de la Réserve fédérale",
    "Federal Reserve July 2026 FOMC statement": "Communiqué de juillet 2026 de la Réserve fédérale",
    "Federal Reserve July 2026 FOMC minutes": "Compte rendu de juillet 2026 de la Réserve fédérale",
    "FRED federal-funds target lower limit": "Borne basse des taux américains - FRED",
    "FRED federal-funds target upper limit": "Borne haute des taux américains - FRED",
    "FRED US 2-year Treasury yield": "Taux américain à deux ans - FRED",
    "FRED US 10-year Treasury yield": "Taux américain à dix ans - FRED",
    "CME FedWatch - September 2026 meeting pricing": "CME FedWatch - prix de marché pour septembre 2026",
    "CME FedWatch methodology": "Méthode CME FedWatch",
    "B3 daily-file search - BVBG.187.01 derivatives report": "Fichiers quotidiens B3 - rapport sur les dérivés",
    "B3 DI1 contract specification": "Spécification du contrat de taux DI1 - B3",
}
