[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#3CC6B0"
backgroundColor = "#08131C"
secondaryBackgroundColor = "#0C1B26"
textColor = "#EEF4F2"
font = "sans serif"
